// Code generated by ent, DO NOT EDIT.

package openai5hwaketaskitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the openai5hwaketaskitem type in the database.
	Label = "open_ai5h_wake_task_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTaskID holds the string denoting the task_id field in the database.
	FieldTaskID = "task_id"
	// FieldIdentityHash holds the string denoting the identity_hash field in the database.
	FieldIdentityHash = "identity_hash"
	// FieldMemberAccountIds holds the string denoting the member_account_ids field in the database.
	FieldMemberAccountIds = "member_account_ids"
	// FieldAttemptedAccountIds holds the string denoting the attempted_account_ids field in the database.
	FieldAttemptedAccountIds = "attempted_account_ids"
	// FieldSuccessfulAccountID holds the string denoting the successful_account_id field in the database.
	FieldSuccessfulAccountID = "successful_account_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAttemptCount holds the string denoting the attempt_count field in the database.
	FieldAttemptCount = "attempt_count"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldResetAt holds the string denoting the reset_at field in the database.
	FieldResetAt = "reset_at"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the openai5hwaketaskitem in the database.
	Table = "openai_5h_wake_task_items"
)

// Columns holds all SQL columns for openai5hwaketaskitem fields.
var Columns = []string{
	FieldID,
	FieldTaskID,
	FieldIdentityHash,
	FieldMemberAccountIds,
	FieldAttemptedAccountIds,
	FieldSuccessfulAccountID,
	FieldStatus,
	FieldAttemptCount,
	FieldErrorCode,
	FieldResetAt,
	FieldStartedAt,
	FieldFinishedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IdentityHashValidator is a validator for the "identity_hash" field. It is called by the builders before save.
	IdentityHashValidator func(string) error
	// DefaultAttemptedAccountIds holds the default value on creation for the "attempted_account_ids" field.
	DefaultAttemptedAccountIds func() []int64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultAttemptCount holds the default value on creation for the "attempt_count" field.
	DefaultAttemptCount int
	// ErrorCodeValidator is a validator for the "error_code" field. It is called by the builders before save.
	ErrorCodeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the OpenAI5hWakeTaskItem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTaskID orders the results by the task_id field.
func ByTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskID, opts...).ToFunc()
}

// ByIdentityHash orders the results by the identity_hash field.
func ByIdentityHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdentityHash, opts...).ToFunc()
}

// BySuccessfulAccountID orders the results by the successful_account_id field.
func BySuccessfulAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccessfulAccountID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAttemptCount orders the results by the attempt_count field.
func ByAttemptCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptCount, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByResetAt orders the results by the reset_at field.
func ByResetAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResetAt, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
