// Code generated by ent, DO NOT EDIT.

package openai5hwaketaskitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLTE(FieldID, id))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldTaskID, v))
}

// IdentityHash applies equality check predicate on the "identity_hash" field. It's identical to IdentityHashEQ.
func IdentityHash(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldIdentityHash, v))
}

// SuccessfulAccountID applies equality check predicate on the "successful_account_id" field. It's identical to SuccessfulAccountIDEQ.
func SuccessfulAccountID(v int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldSuccessfulAccountID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldStatus, v))
}

// AttemptCount applies equality check predicate on the "attempt_count" field. It's identical to AttemptCountEQ.
func AttemptCount(v int) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldAttemptCount, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldErrorCode, v))
}

// ResetAt applies equality check predicate on the "reset_at" field. It's identical to ResetAtEQ.
func ResetAt(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldResetAt, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldFinishedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNotIn(FieldTaskID, vs...))
}

// TaskIDGT applies the GT predicate on the "task_id" field.
func TaskIDGT(v int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGT(FieldTaskID, v))
}

// TaskIDGTE applies the GTE predicate on the "task_id" field.
func TaskIDGTE(v int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGTE(FieldTaskID, v))
}

// TaskIDLT applies the LT predicate on the "task_id" field.
func TaskIDLT(v int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLT(FieldTaskID, v))
}

// TaskIDLTE applies the LTE predicate on the "task_id" field.
func TaskIDLTE(v int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLTE(FieldTaskID, v))
}

// IdentityHashEQ applies the EQ predicate on the "identity_hash" field.
func IdentityHashEQ(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldIdentityHash, v))
}

// IdentityHashNEQ applies the NEQ predicate on the "identity_hash" field.
func IdentityHashNEQ(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNEQ(FieldIdentityHash, v))
}

// IdentityHashIn applies the In predicate on the "identity_hash" field.
func IdentityHashIn(vs ...string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldIn(FieldIdentityHash, vs...))
}

// IdentityHashNotIn applies the NotIn predicate on the "identity_hash" field.
func IdentityHashNotIn(vs ...string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNotIn(FieldIdentityHash, vs...))
}

// IdentityHashGT applies the GT predicate on the "identity_hash" field.
func IdentityHashGT(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGT(FieldIdentityHash, v))
}

// IdentityHashGTE applies the GTE predicate on the "identity_hash" field.
func IdentityHashGTE(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGTE(FieldIdentityHash, v))
}

// IdentityHashLT applies the LT predicate on the "identity_hash" field.
func IdentityHashLT(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLT(FieldIdentityHash, v))
}

// IdentityHashLTE applies the LTE predicate on the "identity_hash" field.
func IdentityHashLTE(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLTE(FieldIdentityHash, v))
}

// IdentityHashContains applies the Contains predicate on the "identity_hash" field.
func IdentityHashContains(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldContains(FieldIdentityHash, v))
}

// IdentityHashHasPrefix applies the HasPrefix predicate on the "identity_hash" field.
func IdentityHashHasPrefix(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldHasPrefix(FieldIdentityHash, v))
}

// IdentityHashHasSuffix applies the HasSuffix predicate on the "identity_hash" field.
func IdentityHashHasSuffix(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldHasSuffix(FieldIdentityHash, v))
}

// IdentityHashEqualFold applies the EqualFold predicate on the "identity_hash" field.
func IdentityHashEqualFold(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEqualFold(FieldIdentityHash, v))
}

// IdentityHashContainsFold applies the ContainsFold predicate on the "identity_hash" field.
func IdentityHashContainsFold(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldContainsFold(FieldIdentityHash, v))
}

// SuccessfulAccountIDEQ applies the EQ predicate on the "successful_account_id" field.
func SuccessfulAccountIDEQ(v int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldSuccessfulAccountID, v))
}

// SuccessfulAccountIDNEQ applies the NEQ predicate on the "successful_account_id" field.
func SuccessfulAccountIDNEQ(v int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNEQ(FieldSuccessfulAccountID, v))
}

// SuccessfulAccountIDIn applies the In predicate on the "successful_account_id" field.
func SuccessfulAccountIDIn(vs ...int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldIn(FieldSuccessfulAccountID, vs...))
}

// SuccessfulAccountIDNotIn applies the NotIn predicate on the "successful_account_id" field.
func SuccessfulAccountIDNotIn(vs ...int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNotIn(FieldSuccessfulAccountID, vs...))
}

// SuccessfulAccountIDGT applies the GT predicate on the "successful_account_id" field.
func SuccessfulAccountIDGT(v int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGT(FieldSuccessfulAccountID, v))
}

// SuccessfulAccountIDGTE applies the GTE predicate on the "successful_account_id" field.
func SuccessfulAccountIDGTE(v int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGTE(FieldSuccessfulAccountID, v))
}

// SuccessfulAccountIDLT applies the LT predicate on the "successful_account_id" field.
func SuccessfulAccountIDLT(v int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLT(FieldSuccessfulAccountID, v))
}

// SuccessfulAccountIDLTE applies the LTE predicate on the "successful_account_id" field.
func SuccessfulAccountIDLTE(v int64) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLTE(FieldSuccessfulAccountID, v))
}

// SuccessfulAccountIDIsNil applies the IsNil predicate on the "successful_account_id" field.
func SuccessfulAccountIDIsNil() predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldIsNull(FieldSuccessfulAccountID))
}

// SuccessfulAccountIDNotNil applies the NotNil predicate on the "successful_account_id" field.
func SuccessfulAccountIDNotNil() predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNotNull(FieldSuccessfulAccountID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldContainsFold(FieldStatus, v))
}

// AttemptCountEQ applies the EQ predicate on the "attempt_count" field.
func AttemptCountEQ(v int) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldAttemptCount, v))
}

// AttemptCountNEQ applies the NEQ predicate on the "attempt_count" field.
func AttemptCountNEQ(v int) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNEQ(FieldAttemptCount, v))
}

// AttemptCountIn applies the In predicate on the "attempt_count" field.
func AttemptCountIn(vs ...int) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldIn(FieldAttemptCount, vs...))
}

// AttemptCountNotIn applies the NotIn predicate on the "attempt_count" field.
func AttemptCountNotIn(vs ...int) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNotIn(FieldAttemptCount, vs...))
}

// AttemptCountGT applies the GT predicate on the "attempt_count" field.
func AttemptCountGT(v int) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGT(FieldAttemptCount, v))
}

// AttemptCountGTE applies the GTE predicate on the "attempt_count" field.
func AttemptCountGTE(v int) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGTE(FieldAttemptCount, v))
}

// AttemptCountLT applies the LT predicate on the "attempt_count" field.
func AttemptCountLT(v int) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLT(FieldAttemptCount, v))
}

// AttemptCountLTE applies the LTE predicate on the "attempt_count" field.
func AttemptCountLTE(v int) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLTE(FieldAttemptCount, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldIsNull(FieldErrorCode))
}

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNotNull(FieldErrorCode))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldContainsFold(FieldErrorCode, v))
}

// ResetAtEQ applies the EQ predicate on the "reset_at" field.
func ResetAtEQ(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldResetAt, v))
}

// ResetAtNEQ applies the NEQ predicate on the "reset_at" field.
func ResetAtNEQ(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNEQ(FieldResetAt, v))
}

// ResetAtIn applies the In predicate on the "reset_at" field.
func ResetAtIn(vs ...time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldIn(FieldResetAt, vs...))
}

// ResetAtNotIn applies the NotIn predicate on the "reset_at" field.
func ResetAtNotIn(vs ...time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNotIn(FieldResetAt, vs...))
}

// ResetAtGT applies the GT predicate on the "reset_at" field.
func ResetAtGT(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGT(FieldResetAt, v))
}

// ResetAtGTE applies the GTE predicate on the "reset_at" field.
func ResetAtGTE(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGTE(FieldResetAt, v))
}

// ResetAtLT applies the LT predicate on the "reset_at" field.
func ResetAtLT(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLT(FieldResetAt, v))
}

// ResetAtLTE applies the LTE predicate on the "reset_at" field.
func ResetAtLTE(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLTE(FieldResetAt, v))
}

// ResetAtIsNil applies the IsNil predicate on the "reset_at" field.
func ResetAtIsNil() predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldIsNull(FieldResetAt))
}

// ResetAtNotNil applies the NotNil predicate on the "reset_at" field.
func ResetAtNotNil() predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNotNull(FieldResetAt))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNotNull(FieldStartedAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNotNull(FieldFinishedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OpenAI5hWakeTaskItem) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OpenAI5hWakeTaskItem) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OpenAI5hWakeTaskItem) predicate.OpenAI5hWakeTaskItem {
	return predicate.OpenAI5hWakeTaskItem(sql.NotPredicates(p))
}
