// Code generated by ent, DO NOT EDIT.

package openai5hwakepoollease

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the openai5hwakepoollease type in the database.
	Label = "open_ai5h_wake_pool_lease"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIdentityHash holds the string denoting the identity_hash field in the database.
	FieldIdentityHash = "identity_hash"
	// FieldTaskID holds the string denoting the task_id field in the database.
	FieldTaskID = "task_id"
	// FieldItemID holds the string denoting the item_id field in the database.
	FieldItemID = "item_id"
	// FieldLeaseOwner holds the string denoting the lease_owner field in the database.
	FieldLeaseOwner = "lease_owner"
	// FieldLeaseExpiresAt holds the string denoting the lease_expires_at field in the database.
	FieldLeaseExpiresAt = "lease_expires_at"
	// FieldHeartbeatAt holds the string denoting the heartbeat_at field in the database.
	FieldHeartbeatAt = "heartbeat_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the openai5hwakepoollease in the database.
	Table = "openai_5h_wake_pool_leases"
)

// Columns holds all SQL columns for openai5hwakepoollease fields.
var Columns = []string{
	FieldID,
	FieldIdentityHash,
	FieldTaskID,
	FieldItemID,
	FieldLeaseOwner,
	FieldLeaseExpiresAt,
	FieldHeartbeatAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IdentityHashValidator is a validator for the "identity_hash" field. It is called by the builders before save.
	IdentityHashValidator func(string) error
	// LeaseOwnerValidator is a validator for the "lease_owner" field. It is called by the builders before save.
	LeaseOwnerValidator func(string) error
	// DefaultHeartbeatAt holds the default value on creation for the "heartbeat_at" field.
	DefaultHeartbeatAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the OpenAI5hWakePoolLease queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIdentityHash orders the results by the identity_hash field.
func ByIdentityHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdentityHash, opts...).ToFunc()
}

// ByTaskID orders the results by the task_id field.
func ByTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskID, opts...).ToFunc()
}

// ByItemID orders the results by the item_id field.
func ByItemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldItemID, opts...).ToFunc()
}

// ByLeaseOwner orders the results by the lease_owner field.
func ByLeaseOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeaseOwner, opts...).ToFunc()
}

// ByLeaseExpiresAt orders the results by the lease_expires_at field.
func ByLeaseExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeaseExpiresAt, opts...).ToFunc()
}

// ByHeartbeatAt orders the results by the heartbeat_at field.
func ByHeartbeatAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeartbeatAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
