// Code generated by ent, DO NOT EDIT.

package openai5hwakepoollease

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldLTE(FieldID, id))
}

// IdentityHash applies equality check predicate on the "identity_hash" field. It's identical to IdentityHashEQ.
func IdentityHash(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldEQ(FieldIdentityHash, v))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldEQ(FieldTaskID, v))
}

// ItemID applies equality check predicate on the "item_id" field. It's identical to ItemIDEQ.
func ItemID(v int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldEQ(FieldItemID, v))
}

// LeaseOwner applies equality check predicate on the "lease_owner" field. It's identical to LeaseOwnerEQ.
func LeaseOwner(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldEQ(FieldLeaseOwner, v))
}

// LeaseExpiresAt applies equality check predicate on the "lease_expires_at" field. It's identical to LeaseExpiresAtEQ.
func LeaseExpiresAt(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldEQ(FieldLeaseExpiresAt, v))
}

// HeartbeatAt applies equality check predicate on the "heartbeat_at" field. It's identical to HeartbeatAtEQ.
func HeartbeatAt(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldEQ(FieldHeartbeatAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldEQ(FieldUpdatedAt, v))
}

// IdentityHashEQ applies the EQ predicate on the "identity_hash" field.
func IdentityHashEQ(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldEQ(FieldIdentityHash, v))
}

// IdentityHashNEQ applies the NEQ predicate on the "identity_hash" field.
func IdentityHashNEQ(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldNEQ(FieldIdentityHash, v))
}

// IdentityHashIn applies the In predicate on the "identity_hash" field.
func IdentityHashIn(vs ...string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldIn(FieldIdentityHash, vs...))
}

// IdentityHashNotIn applies the NotIn predicate on the "identity_hash" field.
func IdentityHashNotIn(vs ...string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldNotIn(FieldIdentityHash, vs...))
}

// IdentityHashGT applies the GT predicate on the "identity_hash" field.
func IdentityHashGT(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldGT(FieldIdentityHash, v))
}

// IdentityHashGTE applies the GTE predicate on the "identity_hash" field.
func IdentityHashGTE(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldGTE(FieldIdentityHash, v))
}

// IdentityHashLT applies the LT predicate on the "identity_hash" field.
func IdentityHashLT(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldLT(FieldIdentityHash, v))
}

// IdentityHashLTE applies the LTE predicate on the "identity_hash" field.
func IdentityHashLTE(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldLTE(FieldIdentityHash, v))
}

// IdentityHashContains applies the Contains predicate on the "identity_hash" field.
func IdentityHashContains(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldContains(FieldIdentityHash, v))
}

// IdentityHashHasPrefix applies the HasPrefix predicate on the "identity_hash" field.
func IdentityHashHasPrefix(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldHasPrefix(FieldIdentityHash, v))
}

// IdentityHashHasSuffix applies the HasSuffix predicate on the "identity_hash" field.
func IdentityHashHasSuffix(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldHasSuffix(FieldIdentityHash, v))
}

// IdentityHashEqualFold applies the EqualFold predicate on the "identity_hash" field.
func IdentityHashEqualFold(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldEqualFold(FieldIdentityHash, v))
}

// IdentityHashContainsFold applies the ContainsFold predicate on the "identity_hash" field.
func IdentityHashContainsFold(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldContainsFold(FieldIdentityHash, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldNotIn(FieldTaskID, vs...))
}

// TaskIDGT applies the GT predicate on the "task_id" field.
func TaskIDGT(v int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldGT(FieldTaskID, v))
}

// TaskIDGTE applies the GTE predicate on the "task_id" field.
func TaskIDGTE(v int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldGTE(FieldTaskID, v))
}

// TaskIDLT applies the LT predicate on the "task_id" field.
func TaskIDLT(v int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldLT(FieldTaskID, v))
}

// TaskIDLTE applies the LTE predicate on the "task_id" field.
func TaskIDLTE(v int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldLTE(FieldTaskID, v))
}

// ItemIDEQ applies the EQ predicate on the "item_id" field.
func ItemIDEQ(v int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldEQ(FieldItemID, v))
}

// ItemIDNEQ applies the NEQ predicate on the "item_id" field.
func ItemIDNEQ(v int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldNEQ(FieldItemID, v))
}

// ItemIDIn applies the In predicate on the "item_id" field.
func ItemIDIn(vs ...int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldIn(FieldItemID, vs...))
}

// ItemIDNotIn applies the NotIn predicate on the "item_id" field.
func ItemIDNotIn(vs ...int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldNotIn(FieldItemID, vs...))
}

// ItemIDGT applies the GT predicate on the "item_id" field.
func ItemIDGT(v int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldGT(FieldItemID, v))
}

// ItemIDGTE applies the GTE predicate on the "item_id" field.
func ItemIDGTE(v int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldGTE(FieldItemID, v))
}

// ItemIDLT applies the LT predicate on the "item_id" field.
func ItemIDLT(v int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldLT(FieldItemID, v))
}

// ItemIDLTE applies the LTE predicate on the "item_id" field.
func ItemIDLTE(v int64) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldLTE(FieldItemID, v))
}

// LeaseOwnerEQ applies the EQ predicate on the "lease_owner" field.
func LeaseOwnerEQ(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldEQ(FieldLeaseOwner, v))
}

// LeaseOwnerNEQ applies the NEQ predicate on the "lease_owner" field.
func LeaseOwnerNEQ(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldNEQ(FieldLeaseOwner, v))
}

// LeaseOwnerIn applies the In predicate on the "lease_owner" field.
func LeaseOwnerIn(vs ...string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldIn(FieldLeaseOwner, vs...))
}

// LeaseOwnerNotIn applies the NotIn predicate on the "lease_owner" field.
func LeaseOwnerNotIn(vs ...string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldNotIn(FieldLeaseOwner, vs...))
}

// LeaseOwnerGT applies the GT predicate on the "lease_owner" field.
func LeaseOwnerGT(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldGT(FieldLeaseOwner, v))
}

// LeaseOwnerGTE applies the GTE predicate on the "lease_owner" field.
func LeaseOwnerGTE(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldGTE(FieldLeaseOwner, v))
}

// LeaseOwnerLT applies the LT predicate on the "lease_owner" field.
func LeaseOwnerLT(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldLT(FieldLeaseOwner, v))
}

// LeaseOwnerLTE applies the LTE predicate on the "lease_owner" field.
func LeaseOwnerLTE(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldLTE(FieldLeaseOwner, v))
}

// LeaseOwnerContains applies the Contains predicate on the "lease_owner" field.
func LeaseOwnerContains(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldContains(FieldLeaseOwner, v))
}

// LeaseOwnerHasPrefix applies the HasPrefix predicate on the "lease_owner" field.
func LeaseOwnerHasPrefix(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldHasPrefix(FieldLeaseOwner, v))
}

// LeaseOwnerHasSuffix applies the HasSuffix predicate on the "lease_owner" field.
func LeaseOwnerHasSuffix(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldHasSuffix(FieldLeaseOwner, v))
}

// LeaseOwnerEqualFold applies the EqualFold predicate on the "lease_owner" field.
func LeaseOwnerEqualFold(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldEqualFold(FieldLeaseOwner, v))
}

// LeaseOwnerContainsFold applies the ContainsFold predicate on the "lease_owner" field.
func LeaseOwnerContainsFold(v string) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldContainsFold(FieldLeaseOwner, v))
}

// LeaseExpiresAtEQ applies the EQ predicate on the "lease_expires_at" field.
func LeaseExpiresAtEQ(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldEQ(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtNEQ applies the NEQ predicate on the "lease_expires_at" field.
func LeaseExpiresAtNEQ(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldNEQ(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtIn applies the In predicate on the "lease_expires_at" field.
func LeaseExpiresAtIn(vs ...time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldIn(FieldLeaseExpiresAt, vs...))
}

// LeaseExpiresAtNotIn applies the NotIn predicate on the "lease_expires_at" field.
func LeaseExpiresAtNotIn(vs ...time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldNotIn(FieldLeaseExpiresAt, vs...))
}

// LeaseExpiresAtGT applies the GT predicate on the "lease_expires_at" field.
func LeaseExpiresAtGT(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldGT(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtGTE applies the GTE predicate on the "lease_expires_at" field.
func LeaseExpiresAtGTE(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldGTE(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtLT applies the LT predicate on the "lease_expires_at" field.
func LeaseExpiresAtLT(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldLT(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtLTE applies the LTE predicate on the "lease_expires_at" field.
func LeaseExpiresAtLTE(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldLTE(FieldLeaseExpiresAt, v))
}

// HeartbeatAtEQ applies the EQ predicate on the "heartbeat_at" field.
func HeartbeatAtEQ(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldEQ(FieldHeartbeatAt, v))
}

// HeartbeatAtNEQ applies the NEQ predicate on the "heartbeat_at" field.
func HeartbeatAtNEQ(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldNEQ(FieldHeartbeatAt, v))
}

// HeartbeatAtIn applies the In predicate on the "heartbeat_at" field.
func HeartbeatAtIn(vs ...time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldIn(FieldHeartbeatAt, vs...))
}

// HeartbeatAtNotIn applies the NotIn predicate on the "heartbeat_at" field.
func HeartbeatAtNotIn(vs ...time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldNotIn(FieldHeartbeatAt, vs...))
}

// HeartbeatAtGT applies the GT predicate on the "heartbeat_at" field.
func HeartbeatAtGT(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldGT(FieldHeartbeatAt, v))
}

// HeartbeatAtGTE applies the GTE predicate on the "heartbeat_at" field.
func HeartbeatAtGTE(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldGTE(FieldHeartbeatAt, v))
}

// HeartbeatAtLT applies the LT predicate on the "heartbeat_at" field.
func HeartbeatAtLT(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldLT(FieldHeartbeatAt, v))
}

// HeartbeatAtLTE applies the LTE predicate on the "heartbeat_at" field.
func HeartbeatAtLTE(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldLTE(FieldHeartbeatAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OpenAI5hWakePoolLease) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OpenAI5hWakePoolLease) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OpenAI5hWakePoolLease) predicate.OpenAI5hWakePoolLease {
	return predicate.OpenAI5hWakePoolLease(sql.NotPredicates(p))
}
