// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/openai5hwakepoollease"
)

// OpenAI5hWakePoolLease is the model entity for the OpenAI5hWakePoolLease schema.
type OpenAI5hWakePoolLease struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// IdentityHash holds the value of the "identity_hash" field.
	IdentityHash string `json:"identity_hash,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID int64 `json:"task_id,omitempty"`
	// ItemID holds the value of the "item_id" field.
	ItemID int64 `json:"item_id,omitempty"`
	// LeaseOwner holds the value of the "lease_owner" field.
	LeaseOwner string `json:"lease_owner,omitempty"`
	// LeaseExpiresAt holds the value of the "lease_expires_at" field.
	LeaseExpiresAt time.Time `json:"lease_expires_at,omitempty"`
	// HeartbeatAt holds the value of the "heartbeat_at" field.
	HeartbeatAt time.Time `json:"heartbeat_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OpenAI5hWakePoolLease) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case openai5hwakepoollease.FieldID, openai5hwakepoollease.FieldTaskID, openai5hwakepoollease.FieldItemID:
			values[i] = new(sql.NullInt64)
		case openai5hwakepoollease.FieldIdentityHash, openai5hwakepoollease.FieldLeaseOwner:
			values[i] = new(sql.NullString)
		case openai5hwakepoollease.FieldLeaseExpiresAt, openai5hwakepoollease.FieldHeartbeatAt, openai5hwakepoollease.FieldCreatedAt, openai5hwakepoollease.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OpenAI5hWakePoolLease fields.
func (_m *OpenAI5hWakePoolLease) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case openai5hwakepoollease.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case openai5hwakepoollease.FieldIdentityHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field identity_hash", values[i])
			} else if value.Valid {
				_m.IdentityHash = value.String
			}
		case openai5hwakepoollease.FieldTaskID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				_m.TaskID = value.Int64
			}
		case openai5hwakepoollease.FieldItemID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field item_id", values[i])
			} else if value.Valid {
				_m.ItemID = value.Int64
			}
		case openai5hwakepoollease.FieldLeaseOwner:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lease_owner", values[i])
			} else if value.Valid {
				_m.LeaseOwner = value.String
			}
		case openai5hwakepoollease.FieldLeaseExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field lease_expires_at", values[i])
			} else if value.Valid {
				_m.LeaseExpiresAt = value.Time
			}
		case openai5hwakepoollease.FieldHeartbeatAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field heartbeat_at", values[i])
			} else if value.Valid {
				_m.HeartbeatAt = value.Time
			}
		case openai5hwakepoollease.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case openai5hwakepoollease.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OpenAI5hWakePoolLease.
// This includes values selected through modifiers, order, etc.
func (_m *OpenAI5hWakePoolLease) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OpenAI5hWakePoolLease.
// Note that you need to call OpenAI5hWakePoolLease.Unwrap() before calling this method if this OpenAI5hWakePoolLease
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OpenAI5hWakePoolLease) Update() *OpenAI5hWakePoolLeaseUpdateOne {
	return NewOpenAI5hWakePoolLeaseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OpenAI5hWakePoolLease entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OpenAI5hWakePoolLease) Unwrap() *OpenAI5hWakePoolLease {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OpenAI5hWakePoolLease is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OpenAI5hWakePoolLease) String() string {
	var builder strings.Builder
	builder.WriteString("OpenAI5hWakePoolLease(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("identity_hash=")
	builder.WriteString(_m.IdentityHash)
	builder.WriteString(", ")
	builder.WriteString("task_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaskID))
	builder.WriteString(", ")
	builder.WriteString("item_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ItemID))
	builder.WriteString(", ")
	builder.WriteString("lease_owner=")
	builder.WriteString(_m.LeaseOwner)
	builder.WriteString(", ")
	builder.WriteString("lease_expires_at=")
	builder.WriteString(_m.LeaseExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("heartbeat_at=")
	builder.WriteString(_m.HeartbeatAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OpenAI5hWakePoolLeases is a parsable slice of OpenAI5hWakePoolLease.
type OpenAI5hWakePoolLeases []*OpenAI5hWakePoolLease
