// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openai5hwaketask"
)

// OpenAI5hWakeTaskCreate is the builder for creating a OpenAI5hWakeTask entity.
type OpenAI5hWakeTaskCreate struct {
	config
	mutation *OpenAI5hWakeTaskMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetStatus sets the "status" field.
func (_c *OpenAI5hWakeTaskCreate) SetStatus(v string) *OpenAI5hWakeTaskCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskCreate) SetNillableStatus(v *string) *OpenAI5hWakeTaskCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetEligibleAccountCount sets the "eligible_account_count" field.
func (_c *OpenAI5hWakeTaskCreate) SetEligibleAccountCount(v int) *OpenAI5hWakeTaskCreate {
	_c.mutation.SetEligibleAccountCount(v)
	return _c
}

// SetNillableEligibleAccountCount sets the "eligible_account_count" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskCreate) SetNillableEligibleAccountCount(v *int) *OpenAI5hWakeTaskCreate {
	if v != nil {
		_c.SetEligibleAccountCount(*v)
	}
	return _c
}

// SetActiveWindowCount sets the "active_window_count" field.
func (_c *OpenAI5hWakeTaskCreate) SetActiveWindowCount(v int) *OpenAI5hWakeTaskCreate {
	_c.mutation.SetActiveWindowCount(v)
	return _c
}

// SetNillableActiveWindowCount sets the "active_window_count" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskCreate) SetNillableActiveWindowCount(v *int) *OpenAI5hWakeTaskCreate {
	if v != nil {
		_c.SetActiveWindowCount(*v)
	}
	return _c
}

// SetEstimatedRequestCount sets the "estimated_request_count" field.
func (_c *OpenAI5hWakeTaskCreate) SetEstimatedRequestCount(v int) *OpenAI5hWakeTaskCreate {
	_c.mutation.SetEstimatedRequestCount(v)
	return _c
}

// SetNillableEstimatedRequestCount sets the "estimated_request_count" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskCreate) SetNillableEstimatedRequestCount(v *int) *OpenAI5hWakeTaskCreate {
	if v != nil {
		_c.SetEstimatedRequestCount(*v)
	}
	return _c
}

// SetTotalItems sets the "total_items" field.
func (_c *OpenAI5hWakeTaskCreate) SetTotalItems(v int) *OpenAI5hWakeTaskCreate {
	_c.mutation.SetTotalItems(v)
	return _c
}

// SetNillableTotalItems sets the "total_items" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskCreate) SetNillableTotalItems(v *int) *OpenAI5hWakeTaskCreate {
	if v != nil {
		_c.SetTotalItems(*v)
	}
	return _c
}

// SetProcessedItems sets the "processed_items" field.
func (_c *OpenAI5hWakeTaskCreate) SetProcessedItems(v int) *OpenAI5hWakeTaskCreate {
	_c.mutation.SetProcessedItems(v)
	return _c
}

// SetNillableProcessedItems sets the "processed_items" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskCreate) SetNillableProcessedItems(v *int) *OpenAI5hWakeTaskCreate {
	if v != nil {
		_c.SetProcessedItems(*v)
	}
	return _c
}

// SetWokenCount sets the "woken_count" field.
func (_c *OpenAI5hWakeTaskCreate) SetWokenCount(v int) *OpenAI5hWakeTaskCreate {
	_c.mutation.SetWokenCount(v)
	return _c
}

// SetNillableWokenCount sets the "woken_count" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskCreate) SetNillableWokenCount(v *int) *OpenAI5hWakeTaskCreate {
	if v != nil {
		_c.SetWokenCount(*v)
	}
	return _c
}

// SetSkippedActiveCount sets the "skipped_active_count" field.
func (_c *OpenAI5hWakeTaskCreate) SetSkippedActiveCount(v int) *OpenAI5hWakeTaskCreate {
	_c.mutation.SetSkippedActiveCount(v)
	return _c
}

// SetNillableSkippedActiveCount sets the "skipped_active_count" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskCreate) SetNillableSkippedActiveCount(v *int) *OpenAI5hWakeTaskCreate {
	if v != nil {
		_c.SetSkippedActiveCount(*v)
	}
	return _c
}

// SetFailedCount sets the "failed_count" field.
func (_c *OpenAI5hWakeTaskCreate) SetFailedCount(v int) *OpenAI5hWakeTaskCreate {
	_c.mutation.SetFailedCount(v)
	return _c
}

// SetNillableFailedCount sets the "failed_count" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskCreate) SetNillableFailedCount(v *int) *OpenAI5hWakeTaskCreate {
	if v != nil {
		_c.SetFailedCount(*v)
	}
	return _c
}

// SetCancelledCount sets the "cancelled_count" field.
func (_c *OpenAI5hWakeTaskCreate) SetCancelledCount(v int) *OpenAI5hWakeTaskCreate {
	_c.mutation.SetCancelledCount(v)
	return _c
}

// SetNillableCancelledCount sets the "cancelled_count" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskCreate) SetNillableCancelledCount(v *int) *OpenAI5hWakeTaskCreate {
	if v != nil {
		_c.SetCancelledCount(*v)
	}
	return _c
}

// SetRequestedByUserID sets the "requested_by_user_id" field.
func (_c *OpenAI5hWakeTaskCreate) SetRequestedByUserID(v int64) *OpenAI5hWakeTaskCreate {
	_c.mutation.SetRequestedByUserID(v)
	return _c
}

// SetNillableRequestedByUserID sets the "requested_by_user_id" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskCreate) SetNillableRequestedByUserID(v *int64) *OpenAI5hWakeTaskCreate {
	if v != nil {
		_c.SetRequestedByUserID(*v)
	}
	return _c
}

// SetRequestedByEmail sets the "requested_by_email" field.
func (_c *OpenAI5hWakeTaskCreate) SetRequestedByEmail(v string) *OpenAI5hWakeTaskCreate {
	_c.mutation.SetRequestedByEmail(v)
	return _c
}

// SetNillableRequestedByEmail sets the "requested_by_email" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskCreate) SetNillableRequestedByEmail(v *string) *OpenAI5hWakeTaskCreate {
	if v != nil {
		_c.SetRequestedByEmail(*v)
	}
	return _c
}

// SetLeaseOwner sets the "lease_owner" field.
func (_c *OpenAI5hWakeTaskCreate) SetLeaseOwner(v string) *OpenAI5hWakeTaskCreate {
	_c.mutation.SetLeaseOwner(v)
	return _c
}

// SetNillableLeaseOwner sets the "lease_owner" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskCreate) SetNillableLeaseOwner(v *string) *OpenAI5hWakeTaskCreate {
	if v != nil {
		_c.SetLeaseOwner(*v)
	}
	return _c
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (_c *OpenAI5hWakeTaskCreate) SetLeaseExpiresAt(v time.Time) *OpenAI5hWakeTaskCreate {
	_c.mutation.SetLeaseExpiresAt(v)
	return _c
}

// SetNillableLeaseExpiresAt sets the "lease_expires_at" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskCreate) SetNillableLeaseExpiresAt(v *time.Time) *OpenAI5hWakeTaskCreate {
	if v != nil {
		_c.SetLeaseExpiresAt(*v)
	}
	return _c
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (_c *OpenAI5hWakeTaskCreate) SetHeartbeatAt(v time.Time) *OpenAI5hWakeTaskCreate {
	_c.mutation.SetHeartbeatAt(v)
	return _c
}

// SetNillableHeartbeatAt sets the "heartbeat_at" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskCreate) SetNillableHeartbeatAt(v *time.Time) *OpenAI5hWakeTaskCreate {
	if v != nil {
		_c.SetHeartbeatAt(*v)
	}
	return _c
}

// SetEarliestResetAt sets the "earliest_reset_at" field.
func (_c *OpenAI5hWakeTaskCreate) SetEarliestResetAt(v time.Time) *OpenAI5hWakeTaskCreate {
	_c.mutation.SetEarliestResetAt(v)
	return _c
}

// SetNillableEarliestResetAt sets the "earliest_reset_at" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskCreate) SetNillableEarliestResetAt(v *time.Time) *OpenAI5hWakeTaskCreate {
	if v != nil {
		_c.SetEarliestResetAt(*v)
	}
	return _c
}

// SetLatestResetAt sets the "latest_reset_at" field.
func (_c *OpenAI5hWakeTaskCreate) SetLatestResetAt(v time.Time) *OpenAI5hWakeTaskCreate {
	_c.mutation.SetLatestResetAt(v)
	return _c
}

// SetNillableLatestResetAt sets the "latest_reset_at" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskCreate) SetNillableLatestResetAt(v *time.Time) *OpenAI5hWakeTaskCreate {
	if v != nil {
		_c.SetLatestResetAt(*v)
	}
	return _c
}

// SetCancelRequestedAt sets the "cancel_requested_at" field.
func (_c *OpenAI5hWakeTaskCreate) SetCancelRequestedAt(v time.Time) *OpenAI5hWakeTaskCreate {
	_c.mutation.SetCancelRequestedAt(v)
	return _c
}

// SetNillableCancelRequestedAt sets the "cancel_requested_at" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskCreate) SetNillableCancelRequestedAt(v *time.Time) *OpenAI5hWakeTaskCreate {
	if v != nil {
		_c.SetCancelRequestedAt(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *OpenAI5hWakeTaskCreate) SetStartedAt(v time.Time) *OpenAI5hWakeTaskCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskCreate) SetNillableStartedAt(v *time.Time) *OpenAI5hWakeTaskCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *OpenAI5hWakeTaskCreate) SetFinishedAt(v time.Time) *OpenAI5hWakeTaskCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskCreate) SetNillableFinishedAt(v *time.Time) *OpenAI5hWakeTaskCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OpenAI5hWakeTaskCreate) SetCreatedAt(v time.Time) *OpenAI5hWakeTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskCreate) SetNillableCreatedAt(v *time.Time) *OpenAI5hWakeTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OpenAI5hWakeTaskCreate) SetUpdatedAt(v time.Time) *OpenAI5hWakeTaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskCreate) SetNillableUpdatedAt(v *time.Time) *OpenAI5hWakeTaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the OpenAI5hWakeTaskMutation object of the builder.
func (_c *OpenAI5hWakeTaskCreate) Mutation() *OpenAI5hWakeTaskMutation {
	return _c.mutation
}

// Save creates the OpenAI5hWakeTask in the database.
func (_c *OpenAI5hWakeTaskCreate) Save(ctx context.Context) (*OpenAI5hWakeTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OpenAI5hWakeTaskCreate) SaveX(ctx context.Context) *OpenAI5hWakeTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OpenAI5hWakeTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OpenAI5hWakeTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OpenAI5hWakeTaskCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := openai5hwaketask.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.EligibleAccountCount(); !ok {
		v := openai5hwaketask.DefaultEligibleAccountCount
		_c.mutation.SetEligibleAccountCount(v)
	}
	if _, ok := _c.mutation.ActiveWindowCount(); !ok {
		v := openai5hwaketask.DefaultActiveWindowCount
		_c.mutation.SetActiveWindowCount(v)
	}
	if _, ok := _c.mutation.EstimatedRequestCount(); !ok {
		v := openai5hwaketask.DefaultEstimatedRequestCount
		_c.mutation.SetEstimatedRequestCount(v)
	}
	if _, ok := _c.mutation.TotalItems(); !ok {
		v := openai5hwaketask.DefaultTotalItems
		_c.mutation.SetTotalItems(v)
	}
	if _, ok := _c.mutation.ProcessedItems(); !ok {
		v := openai5hwaketask.DefaultProcessedItems
		_c.mutation.SetProcessedItems(v)
	}
	if _, ok := _c.mutation.WokenCount(); !ok {
		v := openai5hwaketask.DefaultWokenCount
		_c.mutation.SetWokenCount(v)
	}
	if _, ok := _c.mutation.SkippedActiveCount(); !ok {
		v := openai5hwaketask.DefaultSkippedActiveCount
		_c.mutation.SetSkippedActiveCount(v)
	}
	if _, ok := _c.mutation.FailedCount(); !ok {
		v := openai5hwaketask.DefaultFailedCount
		_c.mutation.SetFailedCount(v)
	}
	if _, ok := _c.mutation.CancelledCount(); !ok {
		v := openai5hwaketask.DefaultCancelledCount
		_c.mutation.SetCancelledCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := openai5hwaketask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := openai5hwaketask.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OpenAI5hWakeTaskCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OpenAI5hWakeTask.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := openai5hwaketask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakeTask.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EligibleAccountCount(); !ok {
		return &ValidationError{Name: "eligible_account_count", err: errors.New(`ent: missing required field "OpenAI5hWakeTask.eligible_account_count"`)}
	}
	if _, ok := _c.mutation.ActiveWindowCount(); !ok {
		return &ValidationError{Name: "active_window_count", err: errors.New(`ent: missing required field "OpenAI5hWakeTask.active_window_count"`)}
	}
	if _, ok := _c.mutation.EstimatedRequestCount(); !ok {
		return &ValidationError{Name: "estimated_request_count", err: errors.New(`ent: missing required field "OpenAI5hWakeTask.estimated_request_count"`)}
	}
	if _, ok := _c.mutation.TotalItems(); !ok {
		return &ValidationError{Name: "total_items", err: errors.New(`ent: missing required field "OpenAI5hWakeTask.total_items"`)}
	}
	if _, ok := _c.mutation.ProcessedItems(); !ok {
		return &ValidationError{Name: "processed_items", err: errors.New(`ent: missing required field "OpenAI5hWakeTask.processed_items"`)}
	}
	if _, ok := _c.mutation.WokenCount(); !ok {
		return &ValidationError{Name: "woken_count", err: errors.New(`ent: missing required field "OpenAI5hWakeTask.woken_count"`)}
	}
	if _, ok := _c.mutation.SkippedActiveCount(); !ok {
		return &ValidationError{Name: "skipped_active_count", err: errors.New(`ent: missing required field "OpenAI5hWakeTask.skipped_active_count"`)}
	}
	if _, ok := _c.mutation.FailedCount(); !ok {
		return &ValidationError{Name: "failed_count", err: errors.New(`ent: missing required field "OpenAI5hWakeTask.failed_count"`)}
	}
	if _, ok := _c.mutation.CancelledCount(); !ok {
		return &ValidationError{Name: "cancelled_count", err: errors.New(`ent: missing required field "OpenAI5hWakeTask.cancelled_count"`)}
	}
	if v, ok := _c.mutation.RequestedByEmail(); ok {
		if err := openai5hwaketask.RequestedByEmailValidator(v); err != nil {
			return &ValidationError{Name: "requested_by_email", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakeTask.requested_by_email": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LeaseOwner(); ok {
		if err := openai5hwaketask.LeaseOwnerValidator(v); err != nil {
			return &ValidationError{Name: "lease_owner", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakeTask.lease_owner": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OpenAI5hWakeTask.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OpenAI5hWakeTask.updated_at"`)}
	}
	return nil
}

func (_c *OpenAI5hWakeTaskCreate) sqlSave(ctx context.Context) (*OpenAI5hWakeTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OpenAI5hWakeTaskCreate) createSpec() (*OpenAI5hWakeTask, *sqlgraph.CreateSpec) {
	var (
		_node = &OpenAI5hWakeTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(openai5hwaketask.Table, sqlgraph.NewFieldSpec(openai5hwaketask.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(openai5hwaketask.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.EligibleAccountCount(); ok {
		_spec.SetField(openai5hwaketask.FieldEligibleAccountCount, field.TypeInt, value)
		_node.EligibleAccountCount = value
	}
	if value, ok := _c.mutation.ActiveWindowCount(); ok {
		_spec.SetField(openai5hwaketask.FieldActiveWindowCount, field.TypeInt, value)
		_node.ActiveWindowCount = value
	}
	if value, ok := _c.mutation.EstimatedRequestCount(); ok {
		_spec.SetField(openai5hwaketask.FieldEstimatedRequestCount, field.TypeInt, value)
		_node.EstimatedRequestCount = value
	}
	if value, ok := _c.mutation.TotalItems(); ok {
		_spec.SetField(openai5hwaketask.FieldTotalItems, field.TypeInt, value)
		_node.TotalItems = value
	}
	if value, ok := _c.mutation.ProcessedItems(); ok {
		_spec.SetField(openai5hwaketask.FieldProcessedItems, field.TypeInt, value)
		_node.ProcessedItems = value
	}
	if value, ok := _c.mutation.WokenCount(); ok {
		_spec.SetField(openai5hwaketask.FieldWokenCount, field.TypeInt, value)
		_node.WokenCount = value
	}
	if value, ok := _c.mutation.SkippedActiveCount(); ok {
		_spec.SetField(openai5hwaketask.FieldSkippedActiveCount, field.TypeInt, value)
		_node.SkippedActiveCount = value
	}
	if value, ok := _c.mutation.FailedCount(); ok {
		_spec.SetField(openai5hwaketask.FieldFailedCount, field.TypeInt, value)
		_node.FailedCount = value
	}
	if value, ok := _c.mutation.CancelledCount(); ok {
		_spec.SetField(openai5hwaketask.FieldCancelledCount, field.TypeInt, value)
		_node.CancelledCount = value
	}
	if value, ok := _c.mutation.RequestedByUserID(); ok {
		_spec.SetField(openai5hwaketask.FieldRequestedByUserID, field.TypeInt64, value)
		_node.RequestedByUserID = &value
	}
	if value, ok := _c.mutation.RequestedByEmail(); ok {
		_spec.SetField(openai5hwaketask.FieldRequestedByEmail, field.TypeString, value)
		_node.RequestedByEmail = &value
	}
	if value, ok := _c.mutation.LeaseOwner(); ok {
		_spec.SetField(openai5hwaketask.FieldLeaseOwner, field.TypeString, value)
		_node.LeaseOwner = &value
	}
	if value, ok := _c.mutation.LeaseExpiresAt(); ok {
		_spec.SetField(openai5hwaketask.FieldLeaseExpiresAt, field.TypeTime, value)
		_node.LeaseExpiresAt = &value
	}
	if value, ok := _c.mutation.HeartbeatAt(); ok {
		_spec.SetField(openai5hwaketask.FieldHeartbeatAt, field.TypeTime, value)
		_node.HeartbeatAt = &value
	}
	if value, ok := _c.mutation.EarliestResetAt(); ok {
		_spec.SetField(openai5hwaketask.FieldEarliestResetAt, field.TypeTime, value)
		_node.EarliestResetAt = &value
	}
	if value, ok := _c.mutation.LatestResetAt(); ok {
		_spec.SetField(openai5hwaketask.FieldLatestResetAt, field.TypeTime, value)
		_node.LatestResetAt = &value
	}
	if value, ok := _c.mutation.CancelRequestedAt(); ok {
		_spec.SetField(openai5hwaketask.FieldCancelRequestedAt, field.TypeTime, value)
		_node.CancelRequestedAt = &value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(openai5hwaketask.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(openai5hwaketask.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(openai5hwaketask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(openai5hwaketask.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OpenAI5hWakeTask.Create().
//		SetStatus(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OpenAI5hWakeTaskUpsert) {
//			SetStatus(v+v).
//		}).
//		Exec(ctx)
func (_c *OpenAI5hWakeTaskCreate) OnConflict(opts ...sql.ConflictOption) *OpenAI5hWakeTaskUpsertOne {
	_c.conflict = opts
	return &OpenAI5hWakeTaskUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OpenAI5hWakeTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OpenAI5hWakeTaskCreate) OnConflictColumns(columns ...string) *OpenAI5hWakeTaskUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OpenAI5hWakeTaskUpsertOne{
		create: _c,
	}
}

type (
	// OpenAI5hWakeTaskUpsertOne is the builder for "upsert"-ing
	//  one OpenAI5hWakeTask node.
	OpenAI5hWakeTaskUpsertOne struct {
		create *OpenAI5hWakeTaskCreate
	}

	// OpenAI5hWakeTaskUpsert is the "OnConflict" setter.
	OpenAI5hWakeTaskUpsert struct {
		*sql.UpdateSet
	}
)

// SetStatus sets the "status" field.
func (u *OpenAI5hWakeTaskUpsert) SetStatus(v string) *OpenAI5hWakeTaskUpsert {
	u.Set(openai5hwaketask.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsert) UpdateStatus() *OpenAI5hWakeTaskUpsert {
	u.SetExcluded(openai5hwaketask.FieldStatus)
	return u
}

// SetEligibleAccountCount sets the "eligible_account_count" field.
func (u *OpenAI5hWakeTaskUpsert) SetEligibleAccountCount(v int) *OpenAI5hWakeTaskUpsert {
	u.Set(openai5hwaketask.FieldEligibleAccountCount, v)
	return u
}

// UpdateEligibleAccountCount sets the "eligible_account_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsert) UpdateEligibleAccountCount() *OpenAI5hWakeTaskUpsert {
	u.SetExcluded(openai5hwaketask.FieldEligibleAccountCount)
	return u
}

// AddEligibleAccountCount adds v to the "eligible_account_count" field.
func (u *OpenAI5hWakeTaskUpsert) AddEligibleAccountCount(v int) *OpenAI5hWakeTaskUpsert {
	u.Add(openai5hwaketask.FieldEligibleAccountCount, v)
	return u
}

// SetActiveWindowCount sets the "active_window_count" field.
func (u *OpenAI5hWakeTaskUpsert) SetActiveWindowCount(v int) *OpenAI5hWakeTaskUpsert {
	u.Set(openai5hwaketask.FieldActiveWindowCount, v)
	return u
}

// UpdateActiveWindowCount sets the "active_window_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsert) UpdateActiveWindowCount() *OpenAI5hWakeTaskUpsert {
	u.SetExcluded(openai5hwaketask.FieldActiveWindowCount)
	return u
}

// AddActiveWindowCount adds v to the "active_window_count" field.
func (u *OpenAI5hWakeTaskUpsert) AddActiveWindowCount(v int) *OpenAI5hWakeTaskUpsert {
	u.Add(openai5hwaketask.FieldActiveWindowCount, v)
	return u
}

// SetEstimatedRequestCount sets the "estimated_request_count" field.
func (u *OpenAI5hWakeTaskUpsert) SetEstimatedRequestCount(v int) *OpenAI5hWakeTaskUpsert {
	u.Set(openai5hwaketask.FieldEstimatedRequestCount, v)
	return u
}

// UpdateEstimatedRequestCount sets the "estimated_request_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsert) UpdateEstimatedRequestCount() *OpenAI5hWakeTaskUpsert {
	u.SetExcluded(openai5hwaketask.FieldEstimatedRequestCount)
	return u
}

// AddEstimatedRequestCount adds v to the "estimated_request_count" field.
func (u *OpenAI5hWakeTaskUpsert) AddEstimatedRequestCount(v int) *OpenAI5hWakeTaskUpsert {
	u.Add(openai5hwaketask.FieldEstimatedRequestCount, v)
	return u
}

// SetTotalItems sets the "total_items" field.
func (u *OpenAI5hWakeTaskUpsert) SetTotalItems(v int) *OpenAI5hWakeTaskUpsert {
	u.Set(openai5hwaketask.FieldTotalItems, v)
	return u
}

// UpdateTotalItems sets the "total_items" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsert) UpdateTotalItems() *OpenAI5hWakeTaskUpsert {
	u.SetExcluded(openai5hwaketask.FieldTotalItems)
	return u
}

// AddTotalItems adds v to the "total_items" field.
func (u *OpenAI5hWakeTaskUpsert) AddTotalItems(v int) *OpenAI5hWakeTaskUpsert {
	u.Add(openai5hwaketask.FieldTotalItems, v)
	return u
}

// SetProcessedItems sets the "processed_items" field.
func (u *OpenAI5hWakeTaskUpsert) SetProcessedItems(v int) *OpenAI5hWakeTaskUpsert {
	u.Set(openai5hwaketask.FieldProcessedItems, v)
	return u
}

// UpdateProcessedItems sets the "processed_items" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsert) UpdateProcessedItems() *OpenAI5hWakeTaskUpsert {
	u.SetExcluded(openai5hwaketask.FieldProcessedItems)
	return u
}

// AddProcessedItems adds v to the "processed_items" field.
func (u *OpenAI5hWakeTaskUpsert) AddProcessedItems(v int) *OpenAI5hWakeTaskUpsert {
	u.Add(openai5hwaketask.FieldProcessedItems, v)
	return u
}

// SetWokenCount sets the "woken_count" field.
func (u *OpenAI5hWakeTaskUpsert) SetWokenCount(v int) *OpenAI5hWakeTaskUpsert {
	u.Set(openai5hwaketask.FieldWokenCount, v)
	return u
}

// UpdateWokenCount sets the "woken_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsert) UpdateWokenCount() *OpenAI5hWakeTaskUpsert {
	u.SetExcluded(openai5hwaketask.FieldWokenCount)
	return u
}

// AddWokenCount adds v to the "woken_count" field.
func (u *OpenAI5hWakeTaskUpsert) AddWokenCount(v int) *OpenAI5hWakeTaskUpsert {
	u.Add(openai5hwaketask.FieldWokenCount, v)
	return u
}

// SetSkippedActiveCount sets the "skipped_active_count" field.
func (u *OpenAI5hWakeTaskUpsert) SetSkippedActiveCount(v int) *OpenAI5hWakeTaskUpsert {
	u.Set(openai5hwaketask.FieldSkippedActiveCount, v)
	return u
}

// UpdateSkippedActiveCount sets the "skipped_active_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsert) UpdateSkippedActiveCount() *OpenAI5hWakeTaskUpsert {
	u.SetExcluded(openai5hwaketask.FieldSkippedActiveCount)
	return u
}

// AddSkippedActiveCount adds v to the "skipped_active_count" field.
func (u *OpenAI5hWakeTaskUpsert) AddSkippedActiveCount(v int) *OpenAI5hWakeTaskUpsert {
	u.Add(openai5hwaketask.FieldSkippedActiveCount, v)
	return u
}

// SetFailedCount sets the "failed_count" field.
func (u *OpenAI5hWakeTaskUpsert) SetFailedCount(v int) *OpenAI5hWakeTaskUpsert {
	u.Set(openai5hwaketask.FieldFailedCount, v)
	return u
}

// UpdateFailedCount sets the "failed_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsert) UpdateFailedCount() *OpenAI5hWakeTaskUpsert {
	u.SetExcluded(openai5hwaketask.FieldFailedCount)
	return u
}

// AddFailedCount adds v to the "failed_count" field.
func (u *OpenAI5hWakeTaskUpsert) AddFailedCount(v int) *OpenAI5hWakeTaskUpsert {
	u.Add(openai5hwaketask.FieldFailedCount, v)
	return u
}

// SetCancelledCount sets the "cancelled_count" field.
func (u *OpenAI5hWakeTaskUpsert) SetCancelledCount(v int) *OpenAI5hWakeTaskUpsert {
	u.Set(openai5hwaketask.FieldCancelledCount, v)
	return u
}

// UpdateCancelledCount sets the "cancelled_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsert) UpdateCancelledCount() *OpenAI5hWakeTaskUpsert {
	u.SetExcluded(openai5hwaketask.FieldCancelledCount)
	return u
}

// AddCancelledCount adds v to the "cancelled_count" field.
func (u *OpenAI5hWakeTaskUpsert) AddCancelledCount(v int) *OpenAI5hWakeTaskUpsert {
	u.Add(openai5hwaketask.FieldCancelledCount, v)
	return u
}

// SetRequestedByUserID sets the "requested_by_user_id" field.
func (u *OpenAI5hWakeTaskUpsert) SetRequestedByUserID(v int64) *OpenAI5hWakeTaskUpsert {
	u.Set(openai5hwaketask.FieldRequestedByUserID, v)
	return u
}

// UpdateRequestedByUserID sets the "requested_by_user_id" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsert) UpdateRequestedByUserID() *OpenAI5hWakeTaskUpsert {
	u.SetExcluded(openai5hwaketask.FieldRequestedByUserID)
	return u
}

// AddRequestedByUserID adds v to the "requested_by_user_id" field.
func (u *OpenAI5hWakeTaskUpsert) AddRequestedByUserID(v int64) *OpenAI5hWakeTaskUpsert {
	u.Add(openai5hwaketask.FieldRequestedByUserID, v)
	return u
}

// ClearRequestedByUserID clears the value of the "requested_by_user_id" field.
func (u *OpenAI5hWakeTaskUpsert) ClearRequestedByUserID() *OpenAI5hWakeTaskUpsert {
	u.SetNull(openai5hwaketask.FieldRequestedByUserID)
	return u
}

// SetRequestedByEmail sets the "requested_by_email" field.
func (u *OpenAI5hWakeTaskUpsert) SetRequestedByEmail(v string) *OpenAI5hWakeTaskUpsert {
	u.Set(openai5hwaketask.FieldRequestedByEmail, v)
	return u
}

// UpdateRequestedByEmail sets the "requested_by_email" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsert) UpdateRequestedByEmail() *OpenAI5hWakeTaskUpsert {
	u.SetExcluded(openai5hwaketask.FieldRequestedByEmail)
	return u
}

// ClearRequestedByEmail clears the value of the "requested_by_email" field.
func (u *OpenAI5hWakeTaskUpsert) ClearRequestedByEmail() *OpenAI5hWakeTaskUpsert {
	u.SetNull(openai5hwaketask.FieldRequestedByEmail)
	return u
}

// SetLeaseOwner sets the "lease_owner" field.
func (u *OpenAI5hWakeTaskUpsert) SetLeaseOwner(v string) *OpenAI5hWakeTaskUpsert {
	u.Set(openai5hwaketask.FieldLeaseOwner, v)
	return u
}

// UpdateLeaseOwner sets the "lease_owner" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsert) UpdateLeaseOwner() *OpenAI5hWakeTaskUpsert {
	u.SetExcluded(openai5hwaketask.FieldLeaseOwner)
	return u
}

// ClearLeaseOwner clears the value of the "lease_owner" field.
func (u *OpenAI5hWakeTaskUpsert) ClearLeaseOwner() *OpenAI5hWakeTaskUpsert {
	u.SetNull(openai5hwaketask.FieldLeaseOwner)
	return u
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (u *OpenAI5hWakeTaskUpsert) SetLeaseExpiresAt(v time.Time) *OpenAI5hWakeTaskUpsert {
	u.Set(openai5hwaketask.FieldLeaseExpiresAt, v)
	return u
}

// UpdateLeaseExpiresAt sets the "lease_expires_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsert) UpdateLeaseExpiresAt() *OpenAI5hWakeTaskUpsert {
	u.SetExcluded(openai5hwaketask.FieldLeaseExpiresAt)
	return u
}

// ClearLeaseExpiresAt clears the value of the "lease_expires_at" field.
func (u *OpenAI5hWakeTaskUpsert) ClearLeaseExpiresAt() *OpenAI5hWakeTaskUpsert {
	u.SetNull(openai5hwaketask.FieldLeaseExpiresAt)
	return u
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (u *OpenAI5hWakeTaskUpsert) SetHeartbeatAt(v time.Time) *OpenAI5hWakeTaskUpsert {
	u.Set(openai5hwaketask.FieldHeartbeatAt, v)
	return u
}

// UpdateHeartbeatAt sets the "heartbeat_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsert) UpdateHeartbeatAt() *OpenAI5hWakeTaskUpsert {
	u.SetExcluded(openai5hwaketask.FieldHeartbeatAt)
	return u
}

// ClearHeartbeatAt clears the value of the "heartbeat_at" field.
func (u *OpenAI5hWakeTaskUpsert) ClearHeartbeatAt() *OpenAI5hWakeTaskUpsert {
	u.SetNull(openai5hwaketask.FieldHeartbeatAt)
	return u
}

// SetEarliestResetAt sets the "earliest_reset_at" field.
func (u *OpenAI5hWakeTaskUpsert) SetEarliestResetAt(v time.Time) *OpenAI5hWakeTaskUpsert {
	u.Set(openai5hwaketask.FieldEarliestResetAt, v)
	return u
}

// UpdateEarliestResetAt sets the "earliest_reset_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsert) UpdateEarliestResetAt() *OpenAI5hWakeTaskUpsert {
	u.SetExcluded(openai5hwaketask.FieldEarliestResetAt)
	return u
}

// ClearEarliestResetAt clears the value of the "earliest_reset_at" field.
func (u *OpenAI5hWakeTaskUpsert) ClearEarliestResetAt() *OpenAI5hWakeTaskUpsert {
	u.SetNull(openai5hwaketask.FieldEarliestResetAt)
	return u
}

// SetLatestResetAt sets the "latest_reset_at" field.
func (u *OpenAI5hWakeTaskUpsert) SetLatestResetAt(v time.Time) *OpenAI5hWakeTaskUpsert {
	u.Set(openai5hwaketask.FieldLatestResetAt, v)
	return u
}

// UpdateLatestResetAt sets the "latest_reset_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsert) UpdateLatestResetAt() *OpenAI5hWakeTaskUpsert {
	u.SetExcluded(openai5hwaketask.FieldLatestResetAt)
	return u
}

// ClearLatestResetAt clears the value of the "latest_reset_at" field.
func (u *OpenAI5hWakeTaskUpsert) ClearLatestResetAt() *OpenAI5hWakeTaskUpsert {
	u.SetNull(openai5hwaketask.FieldLatestResetAt)
	return u
}

// SetCancelRequestedAt sets the "cancel_requested_at" field.
func (u *OpenAI5hWakeTaskUpsert) SetCancelRequestedAt(v time.Time) *OpenAI5hWakeTaskUpsert {
	u.Set(openai5hwaketask.FieldCancelRequestedAt, v)
	return u
}

// UpdateCancelRequestedAt sets the "cancel_requested_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsert) UpdateCancelRequestedAt() *OpenAI5hWakeTaskUpsert {
	u.SetExcluded(openai5hwaketask.FieldCancelRequestedAt)
	return u
}

// ClearCancelRequestedAt clears the value of the "cancel_requested_at" field.
func (u *OpenAI5hWakeTaskUpsert) ClearCancelRequestedAt() *OpenAI5hWakeTaskUpsert {
	u.SetNull(openai5hwaketask.FieldCancelRequestedAt)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *OpenAI5hWakeTaskUpsert) SetStartedAt(v time.Time) *OpenAI5hWakeTaskUpsert {
	u.Set(openai5hwaketask.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsert) UpdateStartedAt() *OpenAI5hWakeTaskUpsert {
	u.SetExcluded(openai5hwaketask.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *OpenAI5hWakeTaskUpsert) ClearStartedAt() *OpenAI5hWakeTaskUpsert {
	u.SetNull(openai5hwaketask.FieldStartedAt)
	return u
}

// SetFinishedAt sets the "finished_at" field.
func (u *OpenAI5hWakeTaskUpsert) SetFinishedAt(v time.Time) *OpenAI5hWakeTaskUpsert {
	u.Set(openai5hwaketask.FieldFinishedAt, v)
	return u
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsert) UpdateFinishedAt() *OpenAI5hWakeTaskUpsert {
	u.SetExcluded(openai5hwaketask.FieldFinishedAt)
	return u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *OpenAI5hWakeTaskUpsert) ClearFinishedAt() *OpenAI5hWakeTaskUpsert {
	u.SetNull(openai5hwaketask.FieldFinishedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAI5hWakeTaskUpsert) SetUpdatedAt(v time.Time) *OpenAI5hWakeTaskUpsert {
	u.Set(openai5hwaketask.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsert) UpdateUpdatedAt() *OpenAI5hWakeTaskUpsert {
	u.SetExcluded(openai5hwaketask.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OpenAI5hWakeTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OpenAI5hWakeTaskUpsertOne) UpdateNewValues() *OpenAI5hWakeTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(openai5hwaketask.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OpenAI5hWakeTask.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OpenAI5hWakeTaskUpsertOne) Ignore() *OpenAI5hWakeTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OpenAI5hWakeTaskUpsertOne) DoNothing() *OpenAI5hWakeTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OpenAI5hWakeTaskCreate.OnConflict
// documentation for more info.
func (u *OpenAI5hWakeTaskUpsertOne) Update(set func(*OpenAI5hWakeTaskUpsert)) *OpenAI5hWakeTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OpenAI5hWakeTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetStatus sets the "status" field.
func (u *OpenAI5hWakeTaskUpsertOne) SetStatus(v string) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertOne) UpdateStatus() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetEligibleAccountCount sets the "eligible_account_count" field.
func (u *OpenAI5hWakeTaskUpsertOne) SetEligibleAccountCount(v int) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetEligibleAccountCount(v)
	})
}

// AddEligibleAccountCount adds v to the "eligible_account_count" field.
func (u *OpenAI5hWakeTaskUpsertOne) AddEligibleAccountCount(v int) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.AddEligibleAccountCount(v)
	})
}

// UpdateEligibleAccountCount sets the "eligible_account_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertOne) UpdateEligibleAccountCount() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateEligibleAccountCount()
	})
}

// SetActiveWindowCount sets the "active_window_count" field.
func (u *OpenAI5hWakeTaskUpsertOne) SetActiveWindowCount(v int) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetActiveWindowCount(v)
	})
}

// AddActiveWindowCount adds v to the "active_window_count" field.
func (u *OpenAI5hWakeTaskUpsertOne) AddActiveWindowCount(v int) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.AddActiveWindowCount(v)
	})
}

// UpdateActiveWindowCount sets the "active_window_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertOne) UpdateActiveWindowCount() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateActiveWindowCount()
	})
}

// SetEstimatedRequestCount sets the "estimated_request_count" field.
func (u *OpenAI5hWakeTaskUpsertOne) SetEstimatedRequestCount(v int) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetEstimatedRequestCount(v)
	})
}

// AddEstimatedRequestCount adds v to the "estimated_request_count" field.
func (u *OpenAI5hWakeTaskUpsertOne) AddEstimatedRequestCount(v int) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.AddEstimatedRequestCount(v)
	})
}

// UpdateEstimatedRequestCount sets the "estimated_request_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertOne) UpdateEstimatedRequestCount() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateEstimatedRequestCount()
	})
}

// SetTotalItems sets the "total_items" field.
func (u *OpenAI5hWakeTaskUpsertOne) SetTotalItems(v int) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetTotalItems(v)
	})
}

// AddTotalItems adds v to the "total_items" field.
func (u *OpenAI5hWakeTaskUpsertOne) AddTotalItems(v int) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.AddTotalItems(v)
	})
}

// UpdateTotalItems sets the "total_items" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertOne) UpdateTotalItems() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateTotalItems()
	})
}

// SetProcessedItems sets the "processed_items" field.
func (u *OpenAI5hWakeTaskUpsertOne) SetProcessedItems(v int) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetProcessedItems(v)
	})
}

// AddProcessedItems adds v to the "processed_items" field.
func (u *OpenAI5hWakeTaskUpsertOne) AddProcessedItems(v int) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.AddProcessedItems(v)
	})
}

// UpdateProcessedItems sets the "processed_items" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertOne) UpdateProcessedItems() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateProcessedItems()
	})
}

// SetWokenCount sets the "woken_count" field.
func (u *OpenAI5hWakeTaskUpsertOne) SetWokenCount(v int) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetWokenCount(v)
	})
}

// AddWokenCount adds v to the "woken_count" field.
func (u *OpenAI5hWakeTaskUpsertOne) AddWokenCount(v int) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.AddWokenCount(v)
	})
}

// UpdateWokenCount sets the "woken_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertOne) UpdateWokenCount() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateWokenCount()
	})
}

// SetSkippedActiveCount sets the "skipped_active_count" field.
func (u *OpenAI5hWakeTaskUpsertOne) SetSkippedActiveCount(v int) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetSkippedActiveCount(v)
	})
}

// AddSkippedActiveCount adds v to the "skipped_active_count" field.
func (u *OpenAI5hWakeTaskUpsertOne) AddSkippedActiveCount(v int) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.AddSkippedActiveCount(v)
	})
}

// UpdateSkippedActiveCount sets the "skipped_active_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertOne) UpdateSkippedActiveCount() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateSkippedActiveCount()
	})
}

// SetFailedCount sets the "failed_count" field.
func (u *OpenAI5hWakeTaskUpsertOne) SetFailedCount(v int) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetFailedCount(v)
	})
}

// AddFailedCount adds v to the "failed_count" field.
func (u *OpenAI5hWakeTaskUpsertOne) AddFailedCount(v int) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.AddFailedCount(v)
	})
}

// UpdateFailedCount sets the "failed_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertOne) UpdateFailedCount() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateFailedCount()
	})
}

// SetCancelledCount sets the "cancelled_count" field.
func (u *OpenAI5hWakeTaskUpsertOne) SetCancelledCount(v int) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetCancelledCount(v)
	})
}

// AddCancelledCount adds v to the "cancelled_count" field.
func (u *OpenAI5hWakeTaskUpsertOne) AddCancelledCount(v int) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.AddCancelledCount(v)
	})
}

// UpdateCancelledCount sets the "cancelled_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertOne) UpdateCancelledCount() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateCancelledCount()
	})
}

// SetRequestedByUserID sets the "requested_by_user_id" field.
func (u *OpenAI5hWakeTaskUpsertOne) SetRequestedByUserID(v int64) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetRequestedByUserID(v)
	})
}

// AddRequestedByUserID adds v to the "requested_by_user_id" field.
func (u *OpenAI5hWakeTaskUpsertOne) AddRequestedByUserID(v int64) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.AddRequestedByUserID(v)
	})
}

// UpdateRequestedByUserID sets the "requested_by_user_id" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertOne) UpdateRequestedByUserID() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateRequestedByUserID()
	})
}

// ClearRequestedByUserID clears the value of the "requested_by_user_id" field.
func (u *OpenAI5hWakeTaskUpsertOne) ClearRequestedByUserID() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.ClearRequestedByUserID()
	})
}

// SetRequestedByEmail sets the "requested_by_email" field.
func (u *OpenAI5hWakeTaskUpsertOne) SetRequestedByEmail(v string) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetRequestedByEmail(v)
	})
}

// UpdateRequestedByEmail sets the "requested_by_email" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertOne) UpdateRequestedByEmail() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateRequestedByEmail()
	})
}

// ClearRequestedByEmail clears the value of the "requested_by_email" field.
func (u *OpenAI5hWakeTaskUpsertOne) ClearRequestedByEmail() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.ClearRequestedByEmail()
	})
}

// SetLeaseOwner sets the "lease_owner" field.
func (u *OpenAI5hWakeTaskUpsertOne) SetLeaseOwner(v string) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetLeaseOwner(v)
	})
}

// UpdateLeaseOwner sets the "lease_owner" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertOne) UpdateLeaseOwner() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateLeaseOwner()
	})
}

// ClearLeaseOwner clears the value of the "lease_owner" field.
func (u *OpenAI5hWakeTaskUpsertOne) ClearLeaseOwner() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.ClearLeaseOwner()
	})
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (u *OpenAI5hWakeTaskUpsertOne) SetLeaseExpiresAt(v time.Time) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetLeaseExpiresAt(v)
	})
}

// UpdateLeaseExpiresAt sets the "lease_expires_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertOne) UpdateLeaseExpiresAt() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateLeaseExpiresAt()
	})
}

// ClearLeaseExpiresAt clears the value of the "lease_expires_at" field.
func (u *OpenAI5hWakeTaskUpsertOne) ClearLeaseExpiresAt() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.ClearLeaseExpiresAt()
	})
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (u *OpenAI5hWakeTaskUpsertOne) SetHeartbeatAt(v time.Time) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetHeartbeatAt(v)
	})
}

// UpdateHeartbeatAt sets the "heartbeat_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertOne) UpdateHeartbeatAt() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateHeartbeatAt()
	})
}

// ClearHeartbeatAt clears the value of the "heartbeat_at" field.
func (u *OpenAI5hWakeTaskUpsertOne) ClearHeartbeatAt() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.ClearHeartbeatAt()
	})
}

// SetEarliestResetAt sets the "earliest_reset_at" field.
func (u *OpenAI5hWakeTaskUpsertOne) SetEarliestResetAt(v time.Time) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetEarliestResetAt(v)
	})
}

// UpdateEarliestResetAt sets the "earliest_reset_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertOne) UpdateEarliestResetAt() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateEarliestResetAt()
	})
}

// ClearEarliestResetAt clears the value of the "earliest_reset_at" field.
func (u *OpenAI5hWakeTaskUpsertOne) ClearEarliestResetAt() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.ClearEarliestResetAt()
	})
}

// SetLatestResetAt sets the "latest_reset_at" field.
func (u *OpenAI5hWakeTaskUpsertOne) SetLatestResetAt(v time.Time) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetLatestResetAt(v)
	})
}

// UpdateLatestResetAt sets the "latest_reset_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertOne) UpdateLatestResetAt() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateLatestResetAt()
	})
}

// ClearLatestResetAt clears the value of the "latest_reset_at" field.
func (u *OpenAI5hWakeTaskUpsertOne) ClearLatestResetAt() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.ClearLatestResetAt()
	})
}

// SetCancelRequestedAt sets the "cancel_requested_at" field.
func (u *OpenAI5hWakeTaskUpsertOne) SetCancelRequestedAt(v time.Time) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetCancelRequestedAt(v)
	})
}

// UpdateCancelRequestedAt sets the "cancel_requested_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertOne) UpdateCancelRequestedAt() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateCancelRequestedAt()
	})
}

// ClearCancelRequestedAt clears the value of the "cancel_requested_at" field.
func (u *OpenAI5hWakeTaskUpsertOne) ClearCancelRequestedAt() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.ClearCancelRequestedAt()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *OpenAI5hWakeTaskUpsertOne) SetStartedAt(v time.Time) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertOne) UpdateStartedAt() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *OpenAI5hWakeTaskUpsertOne) ClearStartedAt() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.ClearStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *OpenAI5hWakeTaskUpsertOne) SetFinishedAt(v time.Time) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertOne) UpdateFinishedAt() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *OpenAI5hWakeTaskUpsertOne) ClearFinishedAt() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.ClearFinishedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAI5hWakeTaskUpsertOne) SetUpdatedAt(v time.Time) *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertOne) UpdateUpdatedAt() *OpenAI5hWakeTaskUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *OpenAI5hWakeTaskUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OpenAI5hWakeTaskCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OpenAI5hWakeTaskUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OpenAI5hWakeTaskUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OpenAI5hWakeTaskUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OpenAI5hWakeTaskCreateBulk is the builder for creating many OpenAI5hWakeTask entities in bulk.
type OpenAI5hWakeTaskCreateBulk struct {
	config
	err      error
	builders []*OpenAI5hWakeTaskCreate
	conflict []sql.ConflictOption
}

// Save creates the OpenAI5hWakeTask entities in the database.
func (_c *OpenAI5hWakeTaskCreateBulk) Save(ctx context.Context) ([]*OpenAI5hWakeTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OpenAI5hWakeTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OpenAI5hWakeTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OpenAI5hWakeTaskCreateBulk) SaveX(ctx context.Context) []*OpenAI5hWakeTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OpenAI5hWakeTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OpenAI5hWakeTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OpenAI5hWakeTask.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OpenAI5hWakeTaskUpsert) {
//			SetStatus(v+v).
//		}).
//		Exec(ctx)
func (_c *OpenAI5hWakeTaskCreateBulk) OnConflict(opts ...sql.ConflictOption) *OpenAI5hWakeTaskUpsertBulk {
	_c.conflict = opts
	return &OpenAI5hWakeTaskUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OpenAI5hWakeTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OpenAI5hWakeTaskCreateBulk) OnConflictColumns(columns ...string) *OpenAI5hWakeTaskUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OpenAI5hWakeTaskUpsertBulk{
		create: _c,
	}
}

// OpenAI5hWakeTaskUpsertBulk is the builder for "upsert"-ing
// a bulk of OpenAI5hWakeTask nodes.
type OpenAI5hWakeTaskUpsertBulk struct {
	create *OpenAI5hWakeTaskCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OpenAI5hWakeTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OpenAI5hWakeTaskUpsertBulk) UpdateNewValues() *OpenAI5hWakeTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(openai5hwaketask.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OpenAI5hWakeTask.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OpenAI5hWakeTaskUpsertBulk) Ignore() *OpenAI5hWakeTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OpenAI5hWakeTaskUpsertBulk) DoNothing() *OpenAI5hWakeTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OpenAI5hWakeTaskCreateBulk.OnConflict
// documentation for more info.
func (u *OpenAI5hWakeTaskUpsertBulk) Update(set func(*OpenAI5hWakeTaskUpsert)) *OpenAI5hWakeTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OpenAI5hWakeTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetStatus sets the "status" field.
func (u *OpenAI5hWakeTaskUpsertBulk) SetStatus(v string) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertBulk) UpdateStatus() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetEligibleAccountCount sets the "eligible_account_count" field.
func (u *OpenAI5hWakeTaskUpsertBulk) SetEligibleAccountCount(v int) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetEligibleAccountCount(v)
	})
}

// AddEligibleAccountCount adds v to the "eligible_account_count" field.
func (u *OpenAI5hWakeTaskUpsertBulk) AddEligibleAccountCount(v int) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.AddEligibleAccountCount(v)
	})
}

// UpdateEligibleAccountCount sets the "eligible_account_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertBulk) UpdateEligibleAccountCount() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateEligibleAccountCount()
	})
}

// SetActiveWindowCount sets the "active_window_count" field.
func (u *OpenAI5hWakeTaskUpsertBulk) SetActiveWindowCount(v int) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetActiveWindowCount(v)
	})
}

// AddActiveWindowCount adds v to the "active_window_count" field.
func (u *OpenAI5hWakeTaskUpsertBulk) AddActiveWindowCount(v int) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.AddActiveWindowCount(v)
	})
}

// UpdateActiveWindowCount sets the "active_window_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertBulk) UpdateActiveWindowCount() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateActiveWindowCount()
	})
}

// SetEstimatedRequestCount sets the "estimated_request_count" field.
func (u *OpenAI5hWakeTaskUpsertBulk) SetEstimatedRequestCount(v int) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetEstimatedRequestCount(v)
	})
}

// AddEstimatedRequestCount adds v to the "estimated_request_count" field.
func (u *OpenAI5hWakeTaskUpsertBulk) AddEstimatedRequestCount(v int) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.AddEstimatedRequestCount(v)
	})
}

// UpdateEstimatedRequestCount sets the "estimated_request_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertBulk) UpdateEstimatedRequestCount() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateEstimatedRequestCount()
	})
}

// SetTotalItems sets the "total_items" field.
func (u *OpenAI5hWakeTaskUpsertBulk) SetTotalItems(v int) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetTotalItems(v)
	})
}

// AddTotalItems adds v to the "total_items" field.
func (u *OpenAI5hWakeTaskUpsertBulk) AddTotalItems(v int) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.AddTotalItems(v)
	})
}

// UpdateTotalItems sets the "total_items" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertBulk) UpdateTotalItems() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateTotalItems()
	})
}

// SetProcessedItems sets the "processed_items" field.
func (u *OpenAI5hWakeTaskUpsertBulk) SetProcessedItems(v int) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetProcessedItems(v)
	})
}

// AddProcessedItems adds v to the "processed_items" field.
func (u *OpenAI5hWakeTaskUpsertBulk) AddProcessedItems(v int) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.AddProcessedItems(v)
	})
}

// UpdateProcessedItems sets the "processed_items" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertBulk) UpdateProcessedItems() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateProcessedItems()
	})
}

// SetWokenCount sets the "woken_count" field.
func (u *OpenAI5hWakeTaskUpsertBulk) SetWokenCount(v int) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetWokenCount(v)
	})
}

// AddWokenCount adds v to the "woken_count" field.
func (u *OpenAI5hWakeTaskUpsertBulk) AddWokenCount(v int) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.AddWokenCount(v)
	})
}

// UpdateWokenCount sets the "woken_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertBulk) UpdateWokenCount() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateWokenCount()
	})
}

// SetSkippedActiveCount sets the "skipped_active_count" field.
func (u *OpenAI5hWakeTaskUpsertBulk) SetSkippedActiveCount(v int) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetSkippedActiveCount(v)
	})
}

// AddSkippedActiveCount adds v to the "skipped_active_count" field.
func (u *OpenAI5hWakeTaskUpsertBulk) AddSkippedActiveCount(v int) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.AddSkippedActiveCount(v)
	})
}

// UpdateSkippedActiveCount sets the "skipped_active_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertBulk) UpdateSkippedActiveCount() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateSkippedActiveCount()
	})
}

// SetFailedCount sets the "failed_count" field.
func (u *OpenAI5hWakeTaskUpsertBulk) SetFailedCount(v int) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetFailedCount(v)
	})
}

// AddFailedCount adds v to the "failed_count" field.
func (u *OpenAI5hWakeTaskUpsertBulk) AddFailedCount(v int) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.AddFailedCount(v)
	})
}

// UpdateFailedCount sets the "failed_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertBulk) UpdateFailedCount() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateFailedCount()
	})
}

// SetCancelledCount sets the "cancelled_count" field.
func (u *OpenAI5hWakeTaskUpsertBulk) SetCancelledCount(v int) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetCancelledCount(v)
	})
}

// AddCancelledCount adds v to the "cancelled_count" field.
func (u *OpenAI5hWakeTaskUpsertBulk) AddCancelledCount(v int) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.AddCancelledCount(v)
	})
}

// UpdateCancelledCount sets the "cancelled_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertBulk) UpdateCancelledCount() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateCancelledCount()
	})
}

// SetRequestedByUserID sets the "requested_by_user_id" field.
func (u *OpenAI5hWakeTaskUpsertBulk) SetRequestedByUserID(v int64) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetRequestedByUserID(v)
	})
}

// AddRequestedByUserID adds v to the "requested_by_user_id" field.
func (u *OpenAI5hWakeTaskUpsertBulk) AddRequestedByUserID(v int64) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.AddRequestedByUserID(v)
	})
}

// UpdateRequestedByUserID sets the "requested_by_user_id" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertBulk) UpdateRequestedByUserID() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateRequestedByUserID()
	})
}

// ClearRequestedByUserID clears the value of the "requested_by_user_id" field.
func (u *OpenAI5hWakeTaskUpsertBulk) ClearRequestedByUserID() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.ClearRequestedByUserID()
	})
}

// SetRequestedByEmail sets the "requested_by_email" field.
func (u *OpenAI5hWakeTaskUpsertBulk) SetRequestedByEmail(v string) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetRequestedByEmail(v)
	})
}

// UpdateRequestedByEmail sets the "requested_by_email" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertBulk) UpdateRequestedByEmail() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateRequestedByEmail()
	})
}

// ClearRequestedByEmail clears the value of the "requested_by_email" field.
func (u *OpenAI5hWakeTaskUpsertBulk) ClearRequestedByEmail() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.ClearRequestedByEmail()
	})
}

// SetLeaseOwner sets the "lease_owner" field.
func (u *OpenAI5hWakeTaskUpsertBulk) SetLeaseOwner(v string) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetLeaseOwner(v)
	})
}

// UpdateLeaseOwner sets the "lease_owner" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertBulk) UpdateLeaseOwner() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateLeaseOwner()
	})
}

// ClearLeaseOwner clears the value of the "lease_owner" field.
func (u *OpenAI5hWakeTaskUpsertBulk) ClearLeaseOwner() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.ClearLeaseOwner()
	})
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (u *OpenAI5hWakeTaskUpsertBulk) SetLeaseExpiresAt(v time.Time) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetLeaseExpiresAt(v)
	})
}

// UpdateLeaseExpiresAt sets the "lease_expires_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertBulk) UpdateLeaseExpiresAt() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateLeaseExpiresAt()
	})
}

// ClearLeaseExpiresAt clears the value of the "lease_expires_at" field.
func (u *OpenAI5hWakeTaskUpsertBulk) ClearLeaseExpiresAt() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.ClearLeaseExpiresAt()
	})
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (u *OpenAI5hWakeTaskUpsertBulk) SetHeartbeatAt(v time.Time) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetHeartbeatAt(v)
	})
}

// UpdateHeartbeatAt sets the "heartbeat_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertBulk) UpdateHeartbeatAt() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateHeartbeatAt()
	})
}

// ClearHeartbeatAt clears the value of the "heartbeat_at" field.
func (u *OpenAI5hWakeTaskUpsertBulk) ClearHeartbeatAt() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.ClearHeartbeatAt()
	})
}

// SetEarliestResetAt sets the "earliest_reset_at" field.
func (u *OpenAI5hWakeTaskUpsertBulk) SetEarliestResetAt(v time.Time) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetEarliestResetAt(v)
	})
}

// UpdateEarliestResetAt sets the "earliest_reset_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertBulk) UpdateEarliestResetAt() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateEarliestResetAt()
	})
}

// ClearEarliestResetAt clears the value of the "earliest_reset_at" field.
func (u *OpenAI5hWakeTaskUpsertBulk) ClearEarliestResetAt() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.ClearEarliestResetAt()
	})
}

// SetLatestResetAt sets the "latest_reset_at" field.
func (u *OpenAI5hWakeTaskUpsertBulk) SetLatestResetAt(v time.Time) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetLatestResetAt(v)
	})
}

// UpdateLatestResetAt sets the "latest_reset_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertBulk) UpdateLatestResetAt() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateLatestResetAt()
	})
}

// ClearLatestResetAt clears the value of the "latest_reset_at" field.
func (u *OpenAI5hWakeTaskUpsertBulk) ClearLatestResetAt() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.ClearLatestResetAt()
	})
}

// SetCancelRequestedAt sets the "cancel_requested_at" field.
func (u *OpenAI5hWakeTaskUpsertBulk) SetCancelRequestedAt(v time.Time) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetCancelRequestedAt(v)
	})
}

// UpdateCancelRequestedAt sets the "cancel_requested_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertBulk) UpdateCancelRequestedAt() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateCancelRequestedAt()
	})
}

// ClearCancelRequestedAt clears the value of the "cancel_requested_at" field.
func (u *OpenAI5hWakeTaskUpsertBulk) ClearCancelRequestedAt() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.ClearCancelRequestedAt()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *OpenAI5hWakeTaskUpsertBulk) SetStartedAt(v time.Time) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertBulk) UpdateStartedAt() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *OpenAI5hWakeTaskUpsertBulk) ClearStartedAt() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.ClearStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *OpenAI5hWakeTaskUpsertBulk) SetFinishedAt(v time.Time) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertBulk) UpdateFinishedAt() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *OpenAI5hWakeTaskUpsertBulk) ClearFinishedAt() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.ClearFinishedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAI5hWakeTaskUpsertBulk) SetUpdatedAt(v time.Time) *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskUpsertBulk) UpdateUpdatedAt() *OpenAI5hWakeTaskUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *OpenAI5hWakeTaskUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OpenAI5hWakeTaskCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OpenAI5hWakeTaskCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OpenAI5hWakeTaskUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
