// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openai5hwaketaskitem"
)

// OpenAI5hWakeTaskItemCreate is the builder for creating a OpenAI5hWakeTaskItem entity.
type OpenAI5hWakeTaskItemCreate struct {
	config
	mutation *OpenAI5hWakeTaskItemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTaskID sets the "task_id" field.
func (_c *OpenAI5hWakeTaskItemCreate) SetTaskID(v int64) *OpenAI5hWakeTaskItemCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetIdentityHash sets the "identity_hash" field.
func (_c *OpenAI5hWakeTaskItemCreate) SetIdentityHash(v string) *OpenAI5hWakeTaskItemCreate {
	_c.mutation.SetIdentityHash(v)
	return _c
}

// SetMemberAccountIds sets the "member_account_ids" field.
func (_c *OpenAI5hWakeTaskItemCreate) SetMemberAccountIds(v []int64) *OpenAI5hWakeTaskItemCreate {
	_c.mutation.SetMemberAccountIds(v)
	return _c
}

// SetAttemptedAccountIds sets the "attempted_account_ids" field.
func (_c *OpenAI5hWakeTaskItemCreate) SetAttemptedAccountIds(v []int64) *OpenAI5hWakeTaskItemCreate {
	_c.mutation.SetAttemptedAccountIds(v)
	return _c
}

// SetSuccessfulAccountID sets the "successful_account_id" field.
func (_c *OpenAI5hWakeTaskItemCreate) SetSuccessfulAccountID(v int64) *OpenAI5hWakeTaskItemCreate {
	_c.mutation.SetSuccessfulAccountID(v)
	return _c
}

// SetNillableSuccessfulAccountID sets the "successful_account_id" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskItemCreate) SetNillableSuccessfulAccountID(v *int64) *OpenAI5hWakeTaskItemCreate {
	if v != nil {
		_c.SetSuccessfulAccountID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OpenAI5hWakeTaskItemCreate) SetStatus(v string) *OpenAI5hWakeTaskItemCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskItemCreate) SetNillableStatus(v *string) *OpenAI5hWakeTaskItemCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAttemptCount sets the "attempt_count" field.
func (_c *OpenAI5hWakeTaskItemCreate) SetAttemptCount(v int) *OpenAI5hWakeTaskItemCreate {
	_c.mutation.SetAttemptCount(v)
	return _c
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskItemCreate) SetNillableAttemptCount(v *int) *OpenAI5hWakeTaskItemCreate {
	if v != nil {
		_c.SetAttemptCount(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *OpenAI5hWakeTaskItemCreate) SetErrorCode(v string) *OpenAI5hWakeTaskItemCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskItemCreate) SetNillableErrorCode(v *string) *OpenAI5hWakeTaskItemCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetResetAt sets the "reset_at" field.
func (_c *OpenAI5hWakeTaskItemCreate) SetResetAt(v time.Time) *OpenAI5hWakeTaskItemCreate {
	_c.mutation.SetResetAt(v)
	return _c
}

// SetNillableResetAt sets the "reset_at" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskItemCreate) SetNillableResetAt(v *time.Time) *OpenAI5hWakeTaskItemCreate {
	if v != nil {
		_c.SetResetAt(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *OpenAI5hWakeTaskItemCreate) SetStartedAt(v time.Time) *OpenAI5hWakeTaskItemCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskItemCreate) SetNillableStartedAt(v *time.Time) *OpenAI5hWakeTaskItemCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *OpenAI5hWakeTaskItemCreate) SetFinishedAt(v time.Time) *OpenAI5hWakeTaskItemCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskItemCreate) SetNillableFinishedAt(v *time.Time) *OpenAI5hWakeTaskItemCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OpenAI5hWakeTaskItemCreate) SetCreatedAt(v time.Time) *OpenAI5hWakeTaskItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskItemCreate) SetNillableCreatedAt(v *time.Time) *OpenAI5hWakeTaskItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OpenAI5hWakeTaskItemCreate) SetUpdatedAt(v time.Time) *OpenAI5hWakeTaskItemCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OpenAI5hWakeTaskItemCreate) SetNillableUpdatedAt(v *time.Time) *OpenAI5hWakeTaskItemCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the OpenAI5hWakeTaskItemMutation object of the builder.
func (_c *OpenAI5hWakeTaskItemCreate) Mutation() *OpenAI5hWakeTaskItemMutation {
	return _c.mutation
}

// Save creates the OpenAI5hWakeTaskItem in the database.
func (_c *OpenAI5hWakeTaskItemCreate) Save(ctx context.Context) (*OpenAI5hWakeTaskItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OpenAI5hWakeTaskItemCreate) SaveX(ctx context.Context) *OpenAI5hWakeTaskItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OpenAI5hWakeTaskItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OpenAI5hWakeTaskItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OpenAI5hWakeTaskItemCreate) defaults() {
	if _, ok := _c.mutation.AttemptedAccountIds(); !ok {
		v := openai5hwaketaskitem.DefaultAttemptedAccountIds()
		_c.mutation.SetAttemptedAccountIds(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := openai5hwaketaskitem.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.AttemptCount(); !ok {
		v := openai5hwaketaskitem.DefaultAttemptCount
		_c.mutation.SetAttemptCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := openai5hwaketaskitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := openai5hwaketaskitem.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OpenAI5hWakeTaskItemCreate) check() error {
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "OpenAI5hWakeTaskItem.task_id"`)}
	}
	if _, ok := _c.mutation.IdentityHash(); !ok {
		return &ValidationError{Name: "identity_hash", err: errors.New(`ent: missing required field "OpenAI5hWakeTaskItem.identity_hash"`)}
	}
	if v, ok := _c.mutation.IdentityHash(); ok {
		if err := openai5hwaketaskitem.IdentityHashValidator(v); err != nil {
			return &ValidationError{Name: "identity_hash", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakeTaskItem.identity_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MemberAccountIds(); !ok {
		return &ValidationError{Name: "member_account_ids", err: errors.New(`ent: missing required field "OpenAI5hWakeTaskItem.member_account_ids"`)}
	}
	if _, ok := _c.mutation.AttemptedAccountIds(); !ok {
		return &ValidationError{Name: "attempted_account_ids", err: errors.New(`ent: missing required field "OpenAI5hWakeTaskItem.attempted_account_ids"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OpenAI5hWakeTaskItem.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := openai5hwaketaskitem.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakeTaskItem.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AttemptCount(); !ok {
		return &ValidationError{Name: "attempt_count", err: errors.New(`ent: missing required field "OpenAI5hWakeTaskItem.attempt_count"`)}
	}
	if v, ok := _c.mutation.ErrorCode(); ok {
		if err := openai5hwaketaskitem.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakeTaskItem.error_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OpenAI5hWakeTaskItem.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OpenAI5hWakeTaskItem.updated_at"`)}
	}
	return nil
}

func (_c *OpenAI5hWakeTaskItemCreate) sqlSave(ctx context.Context) (*OpenAI5hWakeTaskItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OpenAI5hWakeTaskItemCreate) createSpec() (*OpenAI5hWakeTaskItem, *sqlgraph.CreateSpec) {
	var (
		_node = &OpenAI5hWakeTaskItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(openai5hwaketaskitem.Table, sqlgraph.NewFieldSpec(openai5hwaketaskitem.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.TaskID(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldTaskID, field.TypeInt64, value)
		_node.TaskID = value
	}
	if value, ok := _c.mutation.IdentityHash(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldIdentityHash, field.TypeString, value)
		_node.IdentityHash = value
	}
	if value, ok := _c.mutation.MemberAccountIds(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldMemberAccountIds, field.TypeJSON, value)
		_node.MemberAccountIds = value
	}
	if value, ok := _c.mutation.AttemptedAccountIds(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldAttemptedAccountIds, field.TypeJSON, value)
		_node.AttemptedAccountIds = value
	}
	if value, ok := _c.mutation.SuccessfulAccountID(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldSuccessfulAccountID, field.TypeInt64, value)
		_node.SuccessfulAccountID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AttemptCount(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldAttemptCount, field.TypeInt, value)
		_node.AttemptCount = value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = &value
	}
	if value, ok := _c.mutation.ResetAt(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldResetAt, field.TypeTime, value)
		_node.ResetAt = &value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OpenAI5hWakeTaskItem.Create().
//		SetTaskID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OpenAI5hWakeTaskItemUpsert) {
//			SetTaskID(v+v).
//		}).
//		Exec(ctx)
func (_c *OpenAI5hWakeTaskItemCreate) OnConflict(opts ...sql.ConflictOption) *OpenAI5hWakeTaskItemUpsertOne {
	_c.conflict = opts
	return &OpenAI5hWakeTaskItemUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OpenAI5hWakeTaskItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OpenAI5hWakeTaskItemCreate) OnConflictColumns(columns ...string) *OpenAI5hWakeTaskItemUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OpenAI5hWakeTaskItemUpsertOne{
		create: _c,
	}
}

type (
	// OpenAI5hWakeTaskItemUpsertOne is the builder for "upsert"-ing
	//  one OpenAI5hWakeTaskItem node.
	OpenAI5hWakeTaskItemUpsertOne struct {
		create *OpenAI5hWakeTaskItemCreate
	}

	// OpenAI5hWakeTaskItemUpsert is the "OnConflict" setter.
	OpenAI5hWakeTaskItemUpsert struct {
		*sql.UpdateSet
	}
)

// SetTaskID sets the "task_id" field.
func (u *OpenAI5hWakeTaskItemUpsert) SetTaskID(v int64) *OpenAI5hWakeTaskItemUpsert {
	u.Set(openai5hwaketaskitem.FieldTaskID, v)
	return u
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsert) UpdateTaskID() *OpenAI5hWakeTaskItemUpsert {
	u.SetExcluded(openai5hwaketaskitem.FieldTaskID)
	return u
}

// AddTaskID adds v to the "task_id" field.
func (u *OpenAI5hWakeTaskItemUpsert) AddTaskID(v int64) *OpenAI5hWakeTaskItemUpsert {
	u.Add(openai5hwaketaskitem.FieldTaskID, v)
	return u
}

// SetIdentityHash sets the "identity_hash" field.
func (u *OpenAI5hWakeTaskItemUpsert) SetIdentityHash(v string) *OpenAI5hWakeTaskItemUpsert {
	u.Set(openai5hwaketaskitem.FieldIdentityHash, v)
	return u
}

// UpdateIdentityHash sets the "identity_hash" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsert) UpdateIdentityHash() *OpenAI5hWakeTaskItemUpsert {
	u.SetExcluded(openai5hwaketaskitem.FieldIdentityHash)
	return u
}

// SetMemberAccountIds sets the "member_account_ids" field.
func (u *OpenAI5hWakeTaskItemUpsert) SetMemberAccountIds(v []int64) *OpenAI5hWakeTaskItemUpsert {
	u.Set(openai5hwaketaskitem.FieldMemberAccountIds, v)
	return u
}

// UpdateMemberAccountIds sets the "member_account_ids" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsert) UpdateMemberAccountIds() *OpenAI5hWakeTaskItemUpsert {
	u.SetExcluded(openai5hwaketaskitem.FieldMemberAccountIds)
	return u
}

// SetAttemptedAccountIds sets the "attempted_account_ids" field.
func (u *OpenAI5hWakeTaskItemUpsert) SetAttemptedAccountIds(v []int64) *OpenAI5hWakeTaskItemUpsert {
	u.Set(openai5hwaketaskitem.FieldAttemptedAccountIds, v)
	return u
}

// UpdateAttemptedAccountIds sets the "attempted_account_ids" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsert) UpdateAttemptedAccountIds() *OpenAI5hWakeTaskItemUpsert {
	u.SetExcluded(openai5hwaketaskitem.FieldAttemptedAccountIds)
	return u
}

// SetSuccessfulAccountID sets the "successful_account_id" field.
func (u *OpenAI5hWakeTaskItemUpsert) SetSuccessfulAccountID(v int64) *OpenAI5hWakeTaskItemUpsert {
	u.Set(openai5hwaketaskitem.FieldSuccessfulAccountID, v)
	return u
}

// UpdateSuccessfulAccountID sets the "successful_account_id" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsert) UpdateSuccessfulAccountID() *OpenAI5hWakeTaskItemUpsert {
	u.SetExcluded(openai5hwaketaskitem.FieldSuccessfulAccountID)
	return u
}

// AddSuccessfulAccountID adds v to the "successful_account_id" field.
func (u *OpenAI5hWakeTaskItemUpsert) AddSuccessfulAccountID(v int64) *OpenAI5hWakeTaskItemUpsert {
	u.Add(openai5hwaketaskitem.FieldSuccessfulAccountID, v)
	return u
}

// ClearSuccessfulAccountID clears the value of the "successful_account_id" field.
func (u *OpenAI5hWakeTaskItemUpsert) ClearSuccessfulAccountID() *OpenAI5hWakeTaskItemUpsert {
	u.SetNull(openai5hwaketaskitem.FieldSuccessfulAccountID)
	return u
}

// SetStatus sets the "status" field.
func (u *OpenAI5hWakeTaskItemUpsert) SetStatus(v string) *OpenAI5hWakeTaskItemUpsert {
	u.Set(openai5hwaketaskitem.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsert) UpdateStatus() *OpenAI5hWakeTaskItemUpsert {
	u.SetExcluded(openai5hwaketaskitem.FieldStatus)
	return u
}

// SetAttemptCount sets the "attempt_count" field.
func (u *OpenAI5hWakeTaskItemUpsert) SetAttemptCount(v int) *OpenAI5hWakeTaskItemUpsert {
	u.Set(openai5hwaketaskitem.FieldAttemptCount, v)
	return u
}

// UpdateAttemptCount sets the "attempt_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsert) UpdateAttemptCount() *OpenAI5hWakeTaskItemUpsert {
	u.SetExcluded(openai5hwaketaskitem.FieldAttemptCount)
	return u
}

// AddAttemptCount adds v to the "attempt_count" field.
func (u *OpenAI5hWakeTaskItemUpsert) AddAttemptCount(v int) *OpenAI5hWakeTaskItemUpsert {
	u.Add(openai5hwaketaskitem.FieldAttemptCount, v)
	return u
}

// SetErrorCode sets the "error_code" field.
func (u *OpenAI5hWakeTaskItemUpsert) SetErrorCode(v string) *OpenAI5hWakeTaskItemUpsert {
	u.Set(openai5hwaketaskitem.FieldErrorCode, v)
	return u
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsert) UpdateErrorCode() *OpenAI5hWakeTaskItemUpsert {
	u.SetExcluded(openai5hwaketaskitem.FieldErrorCode)
	return u
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *OpenAI5hWakeTaskItemUpsert) ClearErrorCode() *OpenAI5hWakeTaskItemUpsert {
	u.SetNull(openai5hwaketaskitem.FieldErrorCode)
	return u
}

// SetResetAt sets the "reset_at" field.
func (u *OpenAI5hWakeTaskItemUpsert) SetResetAt(v time.Time) *OpenAI5hWakeTaskItemUpsert {
	u.Set(openai5hwaketaskitem.FieldResetAt, v)
	return u
}

// UpdateResetAt sets the "reset_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsert) UpdateResetAt() *OpenAI5hWakeTaskItemUpsert {
	u.SetExcluded(openai5hwaketaskitem.FieldResetAt)
	return u
}

// ClearResetAt clears the value of the "reset_at" field.
func (u *OpenAI5hWakeTaskItemUpsert) ClearResetAt() *OpenAI5hWakeTaskItemUpsert {
	u.SetNull(openai5hwaketaskitem.FieldResetAt)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *OpenAI5hWakeTaskItemUpsert) SetStartedAt(v time.Time) *OpenAI5hWakeTaskItemUpsert {
	u.Set(openai5hwaketaskitem.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsert) UpdateStartedAt() *OpenAI5hWakeTaskItemUpsert {
	u.SetExcluded(openai5hwaketaskitem.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *OpenAI5hWakeTaskItemUpsert) ClearStartedAt() *OpenAI5hWakeTaskItemUpsert {
	u.SetNull(openai5hwaketaskitem.FieldStartedAt)
	return u
}

// SetFinishedAt sets the "finished_at" field.
func (u *OpenAI5hWakeTaskItemUpsert) SetFinishedAt(v time.Time) *OpenAI5hWakeTaskItemUpsert {
	u.Set(openai5hwaketaskitem.FieldFinishedAt, v)
	return u
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsert) UpdateFinishedAt() *OpenAI5hWakeTaskItemUpsert {
	u.SetExcluded(openai5hwaketaskitem.FieldFinishedAt)
	return u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *OpenAI5hWakeTaskItemUpsert) ClearFinishedAt() *OpenAI5hWakeTaskItemUpsert {
	u.SetNull(openai5hwaketaskitem.FieldFinishedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAI5hWakeTaskItemUpsert) SetUpdatedAt(v time.Time) *OpenAI5hWakeTaskItemUpsert {
	u.Set(openai5hwaketaskitem.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsert) UpdateUpdatedAt() *OpenAI5hWakeTaskItemUpsert {
	u.SetExcluded(openai5hwaketaskitem.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OpenAI5hWakeTaskItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OpenAI5hWakeTaskItemUpsertOne) UpdateNewValues() *OpenAI5hWakeTaskItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(openai5hwaketaskitem.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OpenAI5hWakeTaskItem.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OpenAI5hWakeTaskItemUpsertOne) Ignore() *OpenAI5hWakeTaskItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OpenAI5hWakeTaskItemUpsertOne) DoNothing() *OpenAI5hWakeTaskItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OpenAI5hWakeTaskItemCreate.OnConflict
// documentation for more info.
func (u *OpenAI5hWakeTaskItemUpsertOne) Update(set func(*OpenAI5hWakeTaskItemUpsert)) *OpenAI5hWakeTaskItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OpenAI5hWakeTaskItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetTaskID sets the "task_id" field.
func (u *OpenAI5hWakeTaskItemUpsertOne) SetTaskID(v int64) *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetTaskID(v)
	})
}

// AddTaskID adds v to the "task_id" field.
func (u *OpenAI5hWakeTaskItemUpsertOne) AddTaskID(v int64) *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.AddTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertOne) UpdateTaskID() *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateTaskID()
	})
}

// SetIdentityHash sets the "identity_hash" field.
func (u *OpenAI5hWakeTaskItemUpsertOne) SetIdentityHash(v string) *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetIdentityHash(v)
	})
}

// UpdateIdentityHash sets the "identity_hash" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertOne) UpdateIdentityHash() *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateIdentityHash()
	})
}

// SetMemberAccountIds sets the "member_account_ids" field.
func (u *OpenAI5hWakeTaskItemUpsertOne) SetMemberAccountIds(v []int64) *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetMemberAccountIds(v)
	})
}

// UpdateMemberAccountIds sets the "member_account_ids" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertOne) UpdateMemberAccountIds() *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateMemberAccountIds()
	})
}

// SetAttemptedAccountIds sets the "attempted_account_ids" field.
func (u *OpenAI5hWakeTaskItemUpsertOne) SetAttemptedAccountIds(v []int64) *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetAttemptedAccountIds(v)
	})
}

// UpdateAttemptedAccountIds sets the "attempted_account_ids" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertOne) UpdateAttemptedAccountIds() *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateAttemptedAccountIds()
	})
}

// SetSuccessfulAccountID sets the "successful_account_id" field.
func (u *OpenAI5hWakeTaskItemUpsertOne) SetSuccessfulAccountID(v int64) *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetSuccessfulAccountID(v)
	})
}

// AddSuccessfulAccountID adds v to the "successful_account_id" field.
func (u *OpenAI5hWakeTaskItemUpsertOne) AddSuccessfulAccountID(v int64) *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.AddSuccessfulAccountID(v)
	})
}

// UpdateSuccessfulAccountID sets the "successful_account_id" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertOne) UpdateSuccessfulAccountID() *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateSuccessfulAccountID()
	})
}

// ClearSuccessfulAccountID clears the value of the "successful_account_id" field.
func (u *OpenAI5hWakeTaskItemUpsertOne) ClearSuccessfulAccountID() *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.ClearSuccessfulAccountID()
	})
}

// SetStatus sets the "status" field.
func (u *OpenAI5hWakeTaskItemUpsertOne) SetStatus(v string) *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertOne) UpdateStatus() *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateStatus()
	})
}

// SetAttemptCount sets the "attempt_count" field.
func (u *OpenAI5hWakeTaskItemUpsertOne) SetAttemptCount(v int) *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetAttemptCount(v)
	})
}

// AddAttemptCount adds v to the "attempt_count" field.
func (u *OpenAI5hWakeTaskItemUpsertOne) AddAttemptCount(v int) *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.AddAttemptCount(v)
	})
}

// UpdateAttemptCount sets the "attempt_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertOne) UpdateAttemptCount() *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateAttemptCount()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *OpenAI5hWakeTaskItemUpsertOne) SetErrorCode(v string) *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertOne) UpdateErrorCode() *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *OpenAI5hWakeTaskItemUpsertOne) ClearErrorCode() *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.ClearErrorCode()
	})
}

// SetResetAt sets the "reset_at" field.
func (u *OpenAI5hWakeTaskItemUpsertOne) SetResetAt(v time.Time) *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetResetAt(v)
	})
}

// UpdateResetAt sets the "reset_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertOne) UpdateResetAt() *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateResetAt()
	})
}

// ClearResetAt clears the value of the "reset_at" field.
func (u *OpenAI5hWakeTaskItemUpsertOne) ClearResetAt() *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.ClearResetAt()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *OpenAI5hWakeTaskItemUpsertOne) SetStartedAt(v time.Time) *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertOne) UpdateStartedAt() *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *OpenAI5hWakeTaskItemUpsertOne) ClearStartedAt() *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.ClearStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *OpenAI5hWakeTaskItemUpsertOne) SetFinishedAt(v time.Time) *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertOne) UpdateFinishedAt() *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *OpenAI5hWakeTaskItemUpsertOne) ClearFinishedAt() *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.ClearFinishedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAI5hWakeTaskItemUpsertOne) SetUpdatedAt(v time.Time) *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertOne) UpdateUpdatedAt() *OpenAI5hWakeTaskItemUpsertOne {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *OpenAI5hWakeTaskItemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OpenAI5hWakeTaskItemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OpenAI5hWakeTaskItemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OpenAI5hWakeTaskItemUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OpenAI5hWakeTaskItemUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OpenAI5hWakeTaskItemCreateBulk is the builder for creating many OpenAI5hWakeTaskItem entities in bulk.
type OpenAI5hWakeTaskItemCreateBulk struct {
	config
	err      error
	builders []*OpenAI5hWakeTaskItemCreate
	conflict []sql.ConflictOption
}

// Save creates the OpenAI5hWakeTaskItem entities in the database.
func (_c *OpenAI5hWakeTaskItemCreateBulk) Save(ctx context.Context) ([]*OpenAI5hWakeTaskItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OpenAI5hWakeTaskItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OpenAI5hWakeTaskItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OpenAI5hWakeTaskItemCreateBulk) SaveX(ctx context.Context) []*OpenAI5hWakeTaskItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OpenAI5hWakeTaskItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OpenAI5hWakeTaskItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OpenAI5hWakeTaskItem.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OpenAI5hWakeTaskItemUpsert) {
//			SetTaskID(v+v).
//		}).
//		Exec(ctx)
func (_c *OpenAI5hWakeTaskItemCreateBulk) OnConflict(opts ...sql.ConflictOption) *OpenAI5hWakeTaskItemUpsertBulk {
	_c.conflict = opts
	return &OpenAI5hWakeTaskItemUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OpenAI5hWakeTaskItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OpenAI5hWakeTaskItemCreateBulk) OnConflictColumns(columns ...string) *OpenAI5hWakeTaskItemUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OpenAI5hWakeTaskItemUpsertBulk{
		create: _c,
	}
}

// OpenAI5hWakeTaskItemUpsertBulk is the builder for "upsert"-ing
// a bulk of OpenAI5hWakeTaskItem nodes.
type OpenAI5hWakeTaskItemUpsertBulk struct {
	create *OpenAI5hWakeTaskItemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OpenAI5hWakeTaskItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OpenAI5hWakeTaskItemUpsertBulk) UpdateNewValues() *OpenAI5hWakeTaskItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(openai5hwaketaskitem.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OpenAI5hWakeTaskItem.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OpenAI5hWakeTaskItemUpsertBulk) Ignore() *OpenAI5hWakeTaskItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OpenAI5hWakeTaskItemUpsertBulk) DoNothing() *OpenAI5hWakeTaskItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OpenAI5hWakeTaskItemCreateBulk.OnConflict
// documentation for more info.
func (u *OpenAI5hWakeTaskItemUpsertBulk) Update(set func(*OpenAI5hWakeTaskItemUpsert)) *OpenAI5hWakeTaskItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OpenAI5hWakeTaskItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetTaskID sets the "task_id" field.
func (u *OpenAI5hWakeTaskItemUpsertBulk) SetTaskID(v int64) *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetTaskID(v)
	})
}

// AddTaskID adds v to the "task_id" field.
func (u *OpenAI5hWakeTaskItemUpsertBulk) AddTaskID(v int64) *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.AddTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertBulk) UpdateTaskID() *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateTaskID()
	})
}

// SetIdentityHash sets the "identity_hash" field.
func (u *OpenAI5hWakeTaskItemUpsertBulk) SetIdentityHash(v string) *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetIdentityHash(v)
	})
}

// UpdateIdentityHash sets the "identity_hash" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertBulk) UpdateIdentityHash() *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateIdentityHash()
	})
}

// SetMemberAccountIds sets the "member_account_ids" field.
func (u *OpenAI5hWakeTaskItemUpsertBulk) SetMemberAccountIds(v []int64) *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetMemberAccountIds(v)
	})
}

// UpdateMemberAccountIds sets the "member_account_ids" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertBulk) UpdateMemberAccountIds() *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateMemberAccountIds()
	})
}

// SetAttemptedAccountIds sets the "attempted_account_ids" field.
func (u *OpenAI5hWakeTaskItemUpsertBulk) SetAttemptedAccountIds(v []int64) *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetAttemptedAccountIds(v)
	})
}

// UpdateAttemptedAccountIds sets the "attempted_account_ids" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertBulk) UpdateAttemptedAccountIds() *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateAttemptedAccountIds()
	})
}

// SetSuccessfulAccountID sets the "successful_account_id" field.
func (u *OpenAI5hWakeTaskItemUpsertBulk) SetSuccessfulAccountID(v int64) *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetSuccessfulAccountID(v)
	})
}

// AddSuccessfulAccountID adds v to the "successful_account_id" field.
func (u *OpenAI5hWakeTaskItemUpsertBulk) AddSuccessfulAccountID(v int64) *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.AddSuccessfulAccountID(v)
	})
}

// UpdateSuccessfulAccountID sets the "successful_account_id" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertBulk) UpdateSuccessfulAccountID() *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateSuccessfulAccountID()
	})
}

// ClearSuccessfulAccountID clears the value of the "successful_account_id" field.
func (u *OpenAI5hWakeTaskItemUpsertBulk) ClearSuccessfulAccountID() *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.ClearSuccessfulAccountID()
	})
}

// SetStatus sets the "status" field.
func (u *OpenAI5hWakeTaskItemUpsertBulk) SetStatus(v string) *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertBulk) UpdateStatus() *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateStatus()
	})
}

// SetAttemptCount sets the "attempt_count" field.
func (u *OpenAI5hWakeTaskItemUpsertBulk) SetAttemptCount(v int) *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetAttemptCount(v)
	})
}

// AddAttemptCount adds v to the "attempt_count" field.
func (u *OpenAI5hWakeTaskItemUpsertBulk) AddAttemptCount(v int) *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.AddAttemptCount(v)
	})
}

// UpdateAttemptCount sets the "attempt_count" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertBulk) UpdateAttemptCount() *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateAttemptCount()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *OpenAI5hWakeTaskItemUpsertBulk) SetErrorCode(v string) *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertBulk) UpdateErrorCode() *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *OpenAI5hWakeTaskItemUpsertBulk) ClearErrorCode() *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.ClearErrorCode()
	})
}

// SetResetAt sets the "reset_at" field.
func (u *OpenAI5hWakeTaskItemUpsertBulk) SetResetAt(v time.Time) *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetResetAt(v)
	})
}

// UpdateResetAt sets the "reset_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertBulk) UpdateResetAt() *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateResetAt()
	})
}

// ClearResetAt clears the value of the "reset_at" field.
func (u *OpenAI5hWakeTaskItemUpsertBulk) ClearResetAt() *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.ClearResetAt()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *OpenAI5hWakeTaskItemUpsertBulk) SetStartedAt(v time.Time) *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertBulk) UpdateStartedAt() *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *OpenAI5hWakeTaskItemUpsertBulk) ClearStartedAt() *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.ClearStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *OpenAI5hWakeTaskItemUpsertBulk) SetFinishedAt(v time.Time) *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertBulk) UpdateFinishedAt() *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *OpenAI5hWakeTaskItemUpsertBulk) ClearFinishedAt() *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.ClearFinishedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAI5hWakeTaskItemUpsertBulk) SetUpdatedAt(v time.Time) *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAI5hWakeTaskItemUpsertBulk) UpdateUpdatedAt() *OpenAI5hWakeTaskItemUpsertBulk {
	return u.Update(func(s *OpenAI5hWakeTaskItemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *OpenAI5hWakeTaskItemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OpenAI5hWakeTaskItemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OpenAI5hWakeTaskItemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OpenAI5hWakeTaskItemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
