// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/openai5hwaketask"
)

// OpenAI5hWakeTask is the model entity for the OpenAI5hWakeTask schema.
type OpenAI5hWakeTask struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// EligibleAccountCount holds the value of the "eligible_account_count" field.
	EligibleAccountCount int `json:"eligible_account_count,omitempty"`
	// ActiveWindowCount holds the value of the "active_window_count" field.
	ActiveWindowCount int `json:"active_window_count,omitempty"`
	// EstimatedRequestCount holds the value of the "estimated_request_count" field.
	EstimatedRequestCount int `json:"estimated_request_count,omitempty"`
	// TotalItems holds the value of the "total_items" field.
	TotalItems int `json:"total_items,omitempty"`
	// ProcessedItems holds the value of the "processed_items" field.
	ProcessedItems int `json:"processed_items,omitempty"`
	// WokenCount holds the value of the "woken_count" field.
	WokenCount int `json:"woken_count,omitempty"`
	// SkippedActiveCount holds the value of the "skipped_active_count" field.
	SkippedActiveCount int `json:"skipped_active_count,omitempty"`
	// FailedCount holds the value of the "failed_count" field.
	FailedCount int `json:"failed_count,omitempty"`
	// CancelledCount holds the value of the "cancelled_count" field.
	CancelledCount int `json:"cancelled_count,omitempty"`
	// RequestedByUserID holds the value of the "requested_by_user_id" field.
	RequestedByUserID *int64 `json:"requested_by_user_id,omitempty"`
	// RequestedByEmail holds the value of the "requested_by_email" field.
	RequestedByEmail *string `json:"requested_by_email,omitempty"`
	// LeaseOwner holds the value of the "lease_owner" field.
	LeaseOwner *string `json:"lease_owner,omitempty"`
	// LeaseExpiresAt holds the value of the "lease_expires_at" field.
	LeaseExpiresAt *time.Time `json:"lease_expires_at,omitempty"`
	// HeartbeatAt holds the value of the "heartbeat_at" field.
	HeartbeatAt *time.Time `json:"heartbeat_at,omitempty"`
	// EarliestResetAt holds the value of the "earliest_reset_at" field.
	EarliestResetAt *time.Time `json:"earliest_reset_at,omitempty"`
	// LatestResetAt holds the value of the "latest_reset_at" field.
	LatestResetAt *time.Time `json:"latest_reset_at,omitempty"`
	// CancelRequestedAt holds the value of the "cancel_requested_at" field.
	CancelRequestedAt *time.Time `json:"cancel_requested_at,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OpenAI5hWakeTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case openai5hwaketask.FieldID, openai5hwaketask.FieldEligibleAccountCount, openai5hwaketask.FieldActiveWindowCount, openai5hwaketask.FieldEstimatedRequestCount, openai5hwaketask.FieldTotalItems, openai5hwaketask.FieldProcessedItems, openai5hwaketask.FieldWokenCount, openai5hwaketask.FieldSkippedActiveCount, openai5hwaketask.FieldFailedCount, openai5hwaketask.FieldCancelledCount, openai5hwaketask.FieldRequestedByUserID:
			values[i] = new(sql.NullInt64)
		case openai5hwaketask.FieldStatus, openai5hwaketask.FieldRequestedByEmail, openai5hwaketask.FieldLeaseOwner:
			values[i] = new(sql.NullString)
		case openai5hwaketask.FieldLeaseExpiresAt, openai5hwaketask.FieldHeartbeatAt, openai5hwaketask.FieldEarliestResetAt, openai5hwaketask.FieldLatestResetAt, openai5hwaketask.FieldCancelRequestedAt, openai5hwaketask.FieldStartedAt, openai5hwaketask.FieldFinishedAt, openai5hwaketask.FieldCreatedAt, openai5hwaketask.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OpenAI5hWakeTask fields.
func (_m *OpenAI5hWakeTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case openai5hwaketask.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case openai5hwaketask.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case openai5hwaketask.FieldEligibleAccountCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field eligible_account_count", values[i])
			} else if value.Valid {
				_m.EligibleAccountCount = int(value.Int64)
			}
		case openai5hwaketask.FieldActiveWindowCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field active_window_count", values[i])
			} else if value.Valid {
				_m.ActiveWindowCount = int(value.Int64)
			}
		case openai5hwaketask.FieldEstimatedRequestCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field estimated_request_count", values[i])
			} else if value.Valid {
				_m.EstimatedRequestCount = int(value.Int64)
			}
		case openai5hwaketask.FieldTotalItems:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_items", values[i])
			} else if value.Valid {
				_m.TotalItems = int(value.Int64)
			}
		case openai5hwaketask.FieldProcessedItems:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field processed_items", values[i])
			} else if value.Valid {
				_m.ProcessedItems = int(value.Int64)
			}
		case openai5hwaketask.FieldWokenCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field woken_count", values[i])
			} else if value.Valid {
				_m.WokenCount = int(value.Int64)
			}
		case openai5hwaketask.FieldSkippedActiveCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field skipped_active_count", values[i])
			} else if value.Valid {
				_m.SkippedActiveCount = int(value.Int64)
			}
		case openai5hwaketask.FieldFailedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field failed_count", values[i])
			} else if value.Valid {
				_m.FailedCount = int(value.Int64)
			}
		case openai5hwaketask.FieldCancelledCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cancelled_count", values[i])
			} else if value.Valid {
				_m.CancelledCount = int(value.Int64)
			}
		case openai5hwaketask.FieldRequestedByUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field requested_by_user_id", values[i])
			} else if value.Valid {
				_m.RequestedByUserID = new(int64)
				*_m.RequestedByUserID = value.Int64
			}
		case openai5hwaketask.FieldRequestedByEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requested_by_email", values[i])
			} else if value.Valid {
				_m.RequestedByEmail = new(string)
				*_m.RequestedByEmail = value.String
			}
		case openai5hwaketask.FieldLeaseOwner:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lease_owner", values[i])
			} else if value.Valid {
				_m.LeaseOwner = new(string)
				*_m.LeaseOwner = value.String
			}
		case openai5hwaketask.FieldLeaseExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field lease_expires_at", values[i])
			} else if value.Valid {
				_m.LeaseExpiresAt = new(time.Time)
				*_m.LeaseExpiresAt = value.Time
			}
		case openai5hwaketask.FieldHeartbeatAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field heartbeat_at", values[i])
			} else if value.Valid {
				_m.HeartbeatAt = new(time.Time)
				*_m.HeartbeatAt = value.Time
			}
		case openai5hwaketask.FieldEarliestResetAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field earliest_reset_at", values[i])
			} else if value.Valid {
				_m.EarliestResetAt = new(time.Time)
				*_m.EarliestResetAt = value.Time
			}
		case openai5hwaketask.FieldLatestResetAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field latest_reset_at", values[i])
			} else if value.Valid {
				_m.LatestResetAt = new(time.Time)
				*_m.LatestResetAt = value.Time
			}
		case openai5hwaketask.FieldCancelRequestedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cancel_requested_at", values[i])
			} else if value.Valid {
				_m.CancelRequestedAt = new(time.Time)
				*_m.CancelRequestedAt = value.Time
			}
		case openai5hwaketask.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case openai5hwaketask.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case openai5hwaketask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case openai5hwaketask.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OpenAI5hWakeTask.
// This includes values selected through modifiers, order, etc.
func (_m *OpenAI5hWakeTask) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OpenAI5hWakeTask.
// Note that you need to call OpenAI5hWakeTask.Unwrap() before calling this method if this OpenAI5hWakeTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OpenAI5hWakeTask) Update() *OpenAI5hWakeTaskUpdateOne {
	return NewOpenAI5hWakeTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OpenAI5hWakeTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OpenAI5hWakeTask) Unwrap() *OpenAI5hWakeTask {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OpenAI5hWakeTask is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OpenAI5hWakeTask) String() string {
	var builder strings.Builder
	builder.WriteString("OpenAI5hWakeTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("eligible_account_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.EligibleAccountCount))
	builder.WriteString(", ")
	builder.WriteString("active_window_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActiveWindowCount))
	builder.WriteString(", ")
	builder.WriteString("estimated_request_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.EstimatedRequestCount))
	builder.WriteString(", ")
	builder.WriteString("total_items=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalItems))
	builder.WriteString(", ")
	builder.WriteString("processed_items=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProcessedItems))
	builder.WriteString(", ")
	builder.WriteString("woken_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.WokenCount))
	builder.WriteString(", ")
	builder.WriteString("skipped_active_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SkippedActiveCount))
	builder.WriteString(", ")
	builder.WriteString("failed_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.FailedCount))
	builder.WriteString(", ")
	builder.WriteString("cancelled_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.CancelledCount))
	builder.WriteString(", ")
	if v := _m.RequestedByUserID; v != nil {
		builder.WriteString("requested_by_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RequestedByEmail; v != nil {
		builder.WriteString("requested_by_email=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LeaseOwner; v != nil {
		builder.WriteString("lease_owner=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LeaseExpiresAt; v != nil {
		builder.WriteString("lease_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.HeartbeatAt; v != nil {
		builder.WriteString("heartbeat_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.EarliestResetAt; v != nil {
		builder.WriteString("earliest_reset_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LatestResetAt; v != nil {
		builder.WriteString("latest_reset_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CancelRequestedAt; v != nil {
		builder.WriteString("cancel_requested_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OpenAI5hWakeTasks is a parsable slice of OpenAI5hWakeTask.
type OpenAI5hWakeTasks []*OpenAI5hWakeTask
