// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openai5hwaketaskitem"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OpenAI5hWakeTaskItemUpdate is the builder for updating OpenAI5hWakeTaskItem entities.
type OpenAI5hWakeTaskItemUpdate struct {
	config
	hooks    []Hook
	mutation *OpenAI5hWakeTaskItemMutation
}

// Where appends a list predicates to the OpenAI5hWakeTaskItemUpdate builder.
func (_u *OpenAI5hWakeTaskItemUpdate) Where(ps ...predicate.OpenAI5hWakeTaskItem) *OpenAI5hWakeTaskItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *OpenAI5hWakeTaskItemUpdate) SetTaskID(v int64) *OpenAI5hWakeTaskItemUpdate {
	_u.mutation.ResetTaskID()
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskItemUpdate) SetNillableTaskID(v *int64) *OpenAI5hWakeTaskItemUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// AddTaskID adds value to the "task_id" field.
func (_u *OpenAI5hWakeTaskItemUpdate) AddTaskID(v int64) *OpenAI5hWakeTaskItemUpdate {
	_u.mutation.AddTaskID(v)
	return _u
}

// SetIdentityHash sets the "identity_hash" field.
func (_u *OpenAI5hWakeTaskItemUpdate) SetIdentityHash(v string) *OpenAI5hWakeTaskItemUpdate {
	_u.mutation.SetIdentityHash(v)
	return _u
}

// SetNillableIdentityHash sets the "identity_hash" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskItemUpdate) SetNillableIdentityHash(v *string) *OpenAI5hWakeTaskItemUpdate {
	if v != nil {
		_u.SetIdentityHash(*v)
	}
	return _u
}

// SetMemberAccountIds sets the "member_account_ids" field.
func (_u *OpenAI5hWakeTaskItemUpdate) SetMemberAccountIds(v []int64) *OpenAI5hWakeTaskItemUpdate {
	_u.mutation.SetMemberAccountIds(v)
	return _u
}

// AppendMemberAccountIds appends value to the "member_account_ids" field.
func (_u *OpenAI5hWakeTaskItemUpdate) AppendMemberAccountIds(v []int64) *OpenAI5hWakeTaskItemUpdate {
	_u.mutation.AppendMemberAccountIds(v)
	return _u
}

// SetAttemptedAccountIds sets the "attempted_account_ids" field.
func (_u *OpenAI5hWakeTaskItemUpdate) SetAttemptedAccountIds(v []int64) *OpenAI5hWakeTaskItemUpdate {
	_u.mutation.SetAttemptedAccountIds(v)
	return _u
}

// AppendAttemptedAccountIds appends value to the "attempted_account_ids" field.
func (_u *OpenAI5hWakeTaskItemUpdate) AppendAttemptedAccountIds(v []int64) *OpenAI5hWakeTaskItemUpdate {
	_u.mutation.AppendAttemptedAccountIds(v)
	return _u
}

// SetSuccessfulAccountID sets the "successful_account_id" field.
func (_u *OpenAI5hWakeTaskItemUpdate) SetSuccessfulAccountID(v int64) *OpenAI5hWakeTaskItemUpdate {
	_u.mutation.ResetSuccessfulAccountID()
	_u.mutation.SetSuccessfulAccountID(v)
	return _u
}

// SetNillableSuccessfulAccountID sets the "successful_account_id" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskItemUpdate) SetNillableSuccessfulAccountID(v *int64) *OpenAI5hWakeTaskItemUpdate {
	if v != nil {
		_u.SetSuccessfulAccountID(*v)
	}
	return _u
}

// AddSuccessfulAccountID adds value to the "successful_account_id" field.
func (_u *OpenAI5hWakeTaskItemUpdate) AddSuccessfulAccountID(v int64) *OpenAI5hWakeTaskItemUpdate {
	_u.mutation.AddSuccessfulAccountID(v)
	return _u
}

// ClearSuccessfulAccountID clears the value of the "successful_account_id" field.
func (_u *OpenAI5hWakeTaskItemUpdate) ClearSuccessfulAccountID() *OpenAI5hWakeTaskItemUpdate {
	_u.mutation.ClearSuccessfulAccountID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OpenAI5hWakeTaskItemUpdate) SetStatus(v string) *OpenAI5hWakeTaskItemUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskItemUpdate) SetNillableStatus(v *string) *OpenAI5hWakeTaskItemUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *OpenAI5hWakeTaskItemUpdate) SetAttemptCount(v int) *OpenAI5hWakeTaskItemUpdate {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskItemUpdate) SetNillableAttemptCount(v *int) *OpenAI5hWakeTaskItemUpdate {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *OpenAI5hWakeTaskItemUpdate) AddAttemptCount(v int) *OpenAI5hWakeTaskItemUpdate {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *OpenAI5hWakeTaskItemUpdate) SetErrorCode(v string) *OpenAI5hWakeTaskItemUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskItemUpdate) SetNillableErrorCode(v *string) *OpenAI5hWakeTaskItemUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *OpenAI5hWakeTaskItemUpdate) ClearErrorCode() *OpenAI5hWakeTaskItemUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetResetAt sets the "reset_at" field.
func (_u *OpenAI5hWakeTaskItemUpdate) SetResetAt(v time.Time) *OpenAI5hWakeTaskItemUpdate {
	_u.mutation.SetResetAt(v)
	return _u
}

// SetNillableResetAt sets the "reset_at" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskItemUpdate) SetNillableResetAt(v *time.Time) *OpenAI5hWakeTaskItemUpdate {
	if v != nil {
		_u.SetResetAt(*v)
	}
	return _u
}

// ClearResetAt clears the value of the "reset_at" field.
func (_u *OpenAI5hWakeTaskItemUpdate) ClearResetAt() *OpenAI5hWakeTaskItemUpdate {
	_u.mutation.ClearResetAt()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *OpenAI5hWakeTaskItemUpdate) SetStartedAt(v time.Time) *OpenAI5hWakeTaskItemUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskItemUpdate) SetNillableStartedAt(v *time.Time) *OpenAI5hWakeTaskItemUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *OpenAI5hWakeTaskItemUpdate) ClearStartedAt() *OpenAI5hWakeTaskItemUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *OpenAI5hWakeTaskItemUpdate) SetFinishedAt(v time.Time) *OpenAI5hWakeTaskItemUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskItemUpdate) SetNillableFinishedAt(v *time.Time) *OpenAI5hWakeTaskItemUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *OpenAI5hWakeTaskItemUpdate) ClearFinishedAt() *OpenAI5hWakeTaskItemUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OpenAI5hWakeTaskItemUpdate) SetUpdatedAt(v time.Time) *OpenAI5hWakeTaskItemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OpenAI5hWakeTaskItemMutation object of the builder.
func (_u *OpenAI5hWakeTaskItemUpdate) Mutation() *OpenAI5hWakeTaskItemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OpenAI5hWakeTaskItemUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAI5hWakeTaskItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OpenAI5hWakeTaskItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAI5hWakeTaskItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OpenAI5hWakeTaskItemUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := openai5hwaketaskitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAI5hWakeTaskItemUpdate) check() error {
	if v, ok := _u.mutation.IdentityHash(); ok {
		if err := openai5hwaketaskitem.IdentityHashValidator(v); err != nil {
			return &ValidationError{Name: "identity_hash", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakeTaskItem.identity_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := openai5hwaketaskitem.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakeTaskItem.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := openai5hwaketaskitem.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakeTaskItem.error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *OpenAI5hWakeTaskItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openai5hwaketaskitem.Table, openai5hwaketaskitem.Columns, sqlgraph.NewFieldSpec(openai5hwaketaskitem.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTaskID(); ok {
		_spec.AddField(openai5hwaketaskitem.FieldTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.IdentityHash(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldIdentityHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.MemberAccountIds(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldMemberAccountIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMemberAccountIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, openai5hwaketaskitem.FieldMemberAccountIds, value)
		})
	}
	if value, ok := _u.mutation.AttemptedAccountIds(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldAttemptedAccountIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAttemptedAccountIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, openai5hwaketaskitem.FieldAttemptedAccountIds, value)
		})
	}
	if value, ok := _u.mutation.SuccessfulAccountID(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldSuccessfulAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSuccessfulAccountID(); ok {
		_spec.AddField(openai5hwaketaskitem.FieldSuccessfulAccountID, field.TypeInt64, value)
	}
	if _u.mutation.SuccessfulAccountIDCleared() {
		_spec.ClearField(openai5hwaketaskitem.FieldSuccessfulAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(openai5hwaketaskitem.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(openai5hwaketaskitem.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ResetAt(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldResetAt, field.TypeTime, value)
	}
	if _u.mutation.ResetAtCleared() {
		_spec.ClearField(openai5hwaketaskitem.FieldResetAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(openai5hwaketaskitem.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(openai5hwaketaskitem.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openai5hwaketaskitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OpenAI5hWakeTaskItemUpdateOne is the builder for updating a single OpenAI5hWakeTaskItem entity.
type OpenAI5hWakeTaskItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OpenAI5hWakeTaskItemMutation
}

// SetTaskID sets the "task_id" field.
func (_u *OpenAI5hWakeTaskItemUpdateOne) SetTaskID(v int64) *OpenAI5hWakeTaskItemUpdateOne {
	_u.mutation.ResetTaskID()
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskItemUpdateOne) SetNillableTaskID(v *int64) *OpenAI5hWakeTaskItemUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// AddTaskID adds value to the "task_id" field.
func (_u *OpenAI5hWakeTaskItemUpdateOne) AddTaskID(v int64) *OpenAI5hWakeTaskItemUpdateOne {
	_u.mutation.AddTaskID(v)
	return _u
}

// SetIdentityHash sets the "identity_hash" field.
func (_u *OpenAI5hWakeTaskItemUpdateOne) SetIdentityHash(v string) *OpenAI5hWakeTaskItemUpdateOne {
	_u.mutation.SetIdentityHash(v)
	return _u
}

// SetNillableIdentityHash sets the "identity_hash" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskItemUpdateOne) SetNillableIdentityHash(v *string) *OpenAI5hWakeTaskItemUpdateOne {
	if v != nil {
		_u.SetIdentityHash(*v)
	}
	return _u
}

// SetMemberAccountIds sets the "member_account_ids" field.
func (_u *OpenAI5hWakeTaskItemUpdateOne) SetMemberAccountIds(v []int64) *OpenAI5hWakeTaskItemUpdateOne {
	_u.mutation.SetMemberAccountIds(v)
	return _u
}

// AppendMemberAccountIds appends value to the "member_account_ids" field.
func (_u *OpenAI5hWakeTaskItemUpdateOne) AppendMemberAccountIds(v []int64) *OpenAI5hWakeTaskItemUpdateOne {
	_u.mutation.AppendMemberAccountIds(v)
	return _u
}

// SetAttemptedAccountIds sets the "attempted_account_ids" field.
func (_u *OpenAI5hWakeTaskItemUpdateOne) SetAttemptedAccountIds(v []int64) *OpenAI5hWakeTaskItemUpdateOne {
	_u.mutation.SetAttemptedAccountIds(v)
	return _u
}

// AppendAttemptedAccountIds appends value to the "attempted_account_ids" field.
func (_u *OpenAI5hWakeTaskItemUpdateOne) AppendAttemptedAccountIds(v []int64) *OpenAI5hWakeTaskItemUpdateOne {
	_u.mutation.AppendAttemptedAccountIds(v)
	return _u
}

// SetSuccessfulAccountID sets the "successful_account_id" field.
func (_u *OpenAI5hWakeTaskItemUpdateOne) SetSuccessfulAccountID(v int64) *OpenAI5hWakeTaskItemUpdateOne {
	_u.mutation.ResetSuccessfulAccountID()
	_u.mutation.SetSuccessfulAccountID(v)
	return _u
}

// SetNillableSuccessfulAccountID sets the "successful_account_id" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskItemUpdateOne) SetNillableSuccessfulAccountID(v *int64) *OpenAI5hWakeTaskItemUpdateOne {
	if v != nil {
		_u.SetSuccessfulAccountID(*v)
	}
	return _u
}

// AddSuccessfulAccountID adds value to the "successful_account_id" field.
func (_u *OpenAI5hWakeTaskItemUpdateOne) AddSuccessfulAccountID(v int64) *OpenAI5hWakeTaskItemUpdateOne {
	_u.mutation.AddSuccessfulAccountID(v)
	return _u
}

// ClearSuccessfulAccountID clears the value of the "successful_account_id" field.
func (_u *OpenAI5hWakeTaskItemUpdateOne) ClearSuccessfulAccountID() *OpenAI5hWakeTaskItemUpdateOne {
	_u.mutation.ClearSuccessfulAccountID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OpenAI5hWakeTaskItemUpdateOne) SetStatus(v string) *OpenAI5hWakeTaskItemUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskItemUpdateOne) SetNillableStatus(v *string) *OpenAI5hWakeTaskItemUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *OpenAI5hWakeTaskItemUpdateOne) SetAttemptCount(v int) *OpenAI5hWakeTaskItemUpdateOne {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskItemUpdateOne) SetNillableAttemptCount(v *int) *OpenAI5hWakeTaskItemUpdateOne {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *OpenAI5hWakeTaskItemUpdateOne) AddAttemptCount(v int) *OpenAI5hWakeTaskItemUpdateOne {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *OpenAI5hWakeTaskItemUpdateOne) SetErrorCode(v string) *OpenAI5hWakeTaskItemUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskItemUpdateOne) SetNillableErrorCode(v *string) *OpenAI5hWakeTaskItemUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *OpenAI5hWakeTaskItemUpdateOne) ClearErrorCode() *OpenAI5hWakeTaskItemUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetResetAt sets the "reset_at" field.
func (_u *OpenAI5hWakeTaskItemUpdateOne) SetResetAt(v time.Time) *OpenAI5hWakeTaskItemUpdateOne {
	_u.mutation.SetResetAt(v)
	return _u
}

// SetNillableResetAt sets the "reset_at" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskItemUpdateOne) SetNillableResetAt(v *time.Time) *OpenAI5hWakeTaskItemUpdateOne {
	if v != nil {
		_u.SetResetAt(*v)
	}
	return _u
}

// ClearResetAt clears the value of the "reset_at" field.
func (_u *OpenAI5hWakeTaskItemUpdateOne) ClearResetAt() *OpenAI5hWakeTaskItemUpdateOne {
	_u.mutation.ClearResetAt()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *OpenAI5hWakeTaskItemUpdateOne) SetStartedAt(v time.Time) *OpenAI5hWakeTaskItemUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskItemUpdateOne) SetNillableStartedAt(v *time.Time) *OpenAI5hWakeTaskItemUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *OpenAI5hWakeTaskItemUpdateOne) ClearStartedAt() *OpenAI5hWakeTaskItemUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *OpenAI5hWakeTaskItemUpdateOne) SetFinishedAt(v time.Time) *OpenAI5hWakeTaskItemUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskItemUpdateOne) SetNillableFinishedAt(v *time.Time) *OpenAI5hWakeTaskItemUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *OpenAI5hWakeTaskItemUpdateOne) ClearFinishedAt() *OpenAI5hWakeTaskItemUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OpenAI5hWakeTaskItemUpdateOne) SetUpdatedAt(v time.Time) *OpenAI5hWakeTaskItemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OpenAI5hWakeTaskItemMutation object of the builder.
func (_u *OpenAI5hWakeTaskItemUpdateOne) Mutation() *OpenAI5hWakeTaskItemMutation {
	return _u.mutation
}

// Where appends a list predicates to the OpenAI5hWakeTaskItemUpdate builder.
func (_u *OpenAI5hWakeTaskItemUpdateOne) Where(ps ...predicate.OpenAI5hWakeTaskItem) *OpenAI5hWakeTaskItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OpenAI5hWakeTaskItemUpdateOne) Select(field string, fields ...string) *OpenAI5hWakeTaskItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OpenAI5hWakeTaskItem entity.
func (_u *OpenAI5hWakeTaskItemUpdateOne) Save(ctx context.Context) (*OpenAI5hWakeTaskItem, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAI5hWakeTaskItemUpdateOne) SaveX(ctx context.Context) *OpenAI5hWakeTaskItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OpenAI5hWakeTaskItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAI5hWakeTaskItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OpenAI5hWakeTaskItemUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := openai5hwaketaskitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAI5hWakeTaskItemUpdateOne) check() error {
	if v, ok := _u.mutation.IdentityHash(); ok {
		if err := openai5hwaketaskitem.IdentityHashValidator(v); err != nil {
			return &ValidationError{Name: "identity_hash", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakeTaskItem.identity_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := openai5hwaketaskitem.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakeTaskItem.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := openai5hwaketaskitem.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakeTaskItem.error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *OpenAI5hWakeTaskItemUpdateOne) sqlSave(ctx context.Context) (_node *OpenAI5hWakeTaskItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openai5hwaketaskitem.Table, openai5hwaketaskitem.Columns, sqlgraph.NewFieldSpec(openai5hwaketaskitem.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OpenAI5hWakeTaskItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, openai5hwaketaskitem.FieldID)
		for _, f := range fields {
			if !openai5hwaketaskitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != openai5hwaketaskitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTaskID(); ok {
		_spec.AddField(openai5hwaketaskitem.FieldTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.IdentityHash(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldIdentityHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.MemberAccountIds(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldMemberAccountIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMemberAccountIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, openai5hwaketaskitem.FieldMemberAccountIds, value)
		})
	}
	if value, ok := _u.mutation.AttemptedAccountIds(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldAttemptedAccountIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAttemptedAccountIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, openai5hwaketaskitem.FieldAttemptedAccountIds, value)
		})
	}
	if value, ok := _u.mutation.SuccessfulAccountID(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldSuccessfulAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSuccessfulAccountID(); ok {
		_spec.AddField(openai5hwaketaskitem.FieldSuccessfulAccountID, field.TypeInt64, value)
	}
	if _u.mutation.SuccessfulAccountIDCleared() {
		_spec.ClearField(openai5hwaketaskitem.FieldSuccessfulAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(openai5hwaketaskitem.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(openai5hwaketaskitem.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ResetAt(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldResetAt, field.TypeTime, value)
	}
	if _u.mutation.ResetAtCleared() {
		_spec.ClearField(openai5hwaketaskitem.FieldResetAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(openai5hwaketaskitem.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(openai5hwaketaskitem.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(openai5hwaketaskitem.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &OpenAI5hWakeTaskItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openai5hwaketaskitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
