// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/openai5hwaketaskitem"
)

// OpenAI5hWakeTaskItem is the model entity for the OpenAI5hWakeTaskItem schema.
type OpenAI5hWakeTaskItem struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID int64 `json:"task_id,omitempty"`
	// IdentityHash holds the value of the "identity_hash" field.
	IdentityHash string `json:"identity_hash,omitempty"`
	// MemberAccountIds holds the value of the "member_account_ids" field.
	MemberAccountIds []int64 `json:"member_account_ids,omitempty"`
	// AttemptedAccountIds holds the value of the "attempted_account_ids" field.
	AttemptedAccountIds []int64 `json:"attempted_account_ids,omitempty"`
	// SuccessfulAccountID holds the value of the "successful_account_id" field.
	SuccessfulAccountID *int64 `json:"successful_account_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// AttemptCount holds the value of the "attempt_count" field.
	AttemptCount int `json:"attempt_count,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode *string `json:"error_code,omitempty"`
	// ResetAt holds the value of the "reset_at" field.
	ResetAt *time.Time `json:"reset_at,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OpenAI5hWakeTaskItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case openai5hwaketaskitem.FieldMemberAccountIds, openai5hwaketaskitem.FieldAttemptedAccountIds:
			values[i] = new([]byte)
		case openai5hwaketaskitem.FieldID, openai5hwaketaskitem.FieldTaskID, openai5hwaketaskitem.FieldSuccessfulAccountID, openai5hwaketaskitem.FieldAttemptCount:
			values[i] = new(sql.NullInt64)
		case openai5hwaketaskitem.FieldIdentityHash, openai5hwaketaskitem.FieldStatus, openai5hwaketaskitem.FieldErrorCode:
			values[i] = new(sql.NullString)
		case openai5hwaketaskitem.FieldResetAt, openai5hwaketaskitem.FieldStartedAt, openai5hwaketaskitem.FieldFinishedAt, openai5hwaketaskitem.FieldCreatedAt, openai5hwaketaskitem.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OpenAI5hWakeTaskItem fields.
func (_m *OpenAI5hWakeTaskItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case openai5hwaketaskitem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case openai5hwaketaskitem.FieldTaskID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				_m.TaskID = value.Int64
			}
		case openai5hwaketaskitem.FieldIdentityHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field identity_hash", values[i])
			} else if value.Valid {
				_m.IdentityHash = value.String
			}
		case openai5hwaketaskitem.FieldMemberAccountIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field member_account_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.MemberAccountIds); err != nil {
					return fmt.Errorf("unmarshal field member_account_ids: %w", err)
				}
			}
		case openai5hwaketaskitem.FieldAttemptedAccountIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field attempted_account_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AttemptedAccountIds); err != nil {
					return fmt.Errorf("unmarshal field attempted_account_ids: %w", err)
				}
			}
		case openai5hwaketaskitem.FieldSuccessfulAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field successful_account_id", values[i])
			} else if value.Valid {
				_m.SuccessfulAccountID = new(int64)
				*_m.SuccessfulAccountID = value.Int64
			}
		case openai5hwaketaskitem.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case openai5hwaketaskitem.FieldAttemptCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_count", values[i])
			} else if value.Valid {
				_m.AttemptCount = int(value.Int64)
			}
		case openai5hwaketaskitem.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = new(string)
				*_m.ErrorCode = value.String
			}
		case openai5hwaketaskitem.FieldResetAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reset_at", values[i])
			} else if value.Valid {
				_m.ResetAt = new(time.Time)
				*_m.ResetAt = value.Time
			}
		case openai5hwaketaskitem.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case openai5hwaketaskitem.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case openai5hwaketaskitem.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case openai5hwaketaskitem.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OpenAI5hWakeTaskItem.
// This includes values selected through modifiers, order, etc.
func (_m *OpenAI5hWakeTaskItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OpenAI5hWakeTaskItem.
// Note that you need to call OpenAI5hWakeTaskItem.Unwrap() before calling this method if this OpenAI5hWakeTaskItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OpenAI5hWakeTaskItem) Update() *OpenAI5hWakeTaskItemUpdateOne {
	return NewOpenAI5hWakeTaskItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OpenAI5hWakeTaskItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OpenAI5hWakeTaskItem) Unwrap() *OpenAI5hWakeTaskItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OpenAI5hWakeTaskItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OpenAI5hWakeTaskItem) String() string {
	var builder strings.Builder
	builder.WriteString("OpenAI5hWakeTaskItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("task_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaskID))
	builder.WriteString(", ")
	builder.WriteString("identity_hash=")
	builder.WriteString(_m.IdentityHash)
	builder.WriteString(", ")
	builder.WriteString("member_account_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.MemberAccountIds))
	builder.WriteString(", ")
	builder.WriteString("attempted_account_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptedAccountIds))
	builder.WriteString(", ")
	if v := _m.SuccessfulAccountID; v != nil {
		builder.WriteString("successful_account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("attempt_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptCount))
	builder.WriteString(", ")
	if v := _m.ErrorCode; v != nil {
		builder.WriteString("error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ResetAt; v != nil {
		builder.WriteString("reset_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OpenAI5hWakeTaskItems is a parsable slice of OpenAI5hWakeTaskItem.
type OpenAI5hWakeTaskItems []*OpenAI5hWakeTaskItem
