// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openai5hwakepoollease"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OpenAI5hWakePoolLeaseUpdate is the builder for updating OpenAI5hWakePoolLease entities.
type OpenAI5hWakePoolLeaseUpdate struct {
	config
	hooks    []Hook
	mutation *OpenAI5hWakePoolLeaseMutation
}

// Where appends a list predicates to the OpenAI5hWakePoolLeaseUpdate builder.
func (_u *OpenAI5hWakePoolLeaseUpdate) Where(ps ...predicate.OpenAI5hWakePoolLease) *OpenAI5hWakePoolLeaseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetIdentityHash sets the "identity_hash" field.
func (_u *OpenAI5hWakePoolLeaseUpdate) SetIdentityHash(v string) *OpenAI5hWakePoolLeaseUpdate {
	_u.mutation.SetIdentityHash(v)
	return _u
}

// SetNillableIdentityHash sets the "identity_hash" field if the given value is not nil.
func (_u *OpenAI5hWakePoolLeaseUpdate) SetNillableIdentityHash(v *string) *OpenAI5hWakePoolLeaseUpdate {
	if v != nil {
		_u.SetIdentityHash(*v)
	}
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *OpenAI5hWakePoolLeaseUpdate) SetTaskID(v int64) *OpenAI5hWakePoolLeaseUpdate {
	_u.mutation.ResetTaskID()
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *OpenAI5hWakePoolLeaseUpdate) SetNillableTaskID(v *int64) *OpenAI5hWakePoolLeaseUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// AddTaskID adds value to the "task_id" field.
func (_u *OpenAI5hWakePoolLeaseUpdate) AddTaskID(v int64) *OpenAI5hWakePoolLeaseUpdate {
	_u.mutation.AddTaskID(v)
	return _u
}

// SetItemID sets the "item_id" field.
func (_u *OpenAI5hWakePoolLeaseUpdate) SetItemID(v int64) *OpenAI5hWakePoolLeaseUpdate {
	_u.mutation.ResetItemID()
	_u.mutation.SetItemID(v)
	return _u
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_u *OpenAI5hWakePoolLeaseUpdate) SetNillableItemID(v *int64) *OpenAI5hWakePoolLeaseUpdate {
	if v != nil {
		_u.SetItemID(*v)
	}
	return _u
}

// AddItemID adds value to the "item_id" field.
func (_u *OpenAI5hWakePoolLeaseUpdate) AddItemID(v int64) *OpenAI5hWakePoolLeaseUpdate {
	_u.mutation.AddItemID(v)
	return _u
}

// SetLeaseOwner sets the "lease_owner" field.
func (_u *OpenAI5hWakePoolLeaseUpdate) SetLeaseOwner(v string) *OpenAI5hWakePoolLeaseUpdate {
	_u.mutation.SetLeaseOwner(v)
	return _u
}

// SetNillableLeaseOwner sets the "lease_owner" field if the given value is not nil.
func (_u *OpenAI5hWakePoolLeaseUpdate) SetNillableLeaseOwner(v *string) *OpenAI5hWakePoolLeaseUpdate {
	if v != nil {
		_u.SetLeaseOwner(*v)
	}
	return _u
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (_u *OpenAI5hWakePoolLeaseUpdate) SetLeaseExpiresAt(v time.Time) *OpenAI5hWakePoolLeaseUpdate {
	_u.mutation.SetLeaseExpiresAt(v)
	return _u
}

// SetNillableLeaseExpiresAt sets the "lease_expires_at" field if the given value is not nil.
func (_u *OpenAI5hWakePoolLeaseUpdate) SetNillableLeaseExpiresAt(v *time.Time) *OpenAI5hWakePoolLeaseUpdate {
	if v != nil {
		_u.SetLeaseExpiresAt(*v)
	}
	return _u
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (_u *OpenAI5hWakePoolLeaseUpdate) SetHeartbeatAt(v time.Time) *OpenAI5hWakePoolLeaseUpdate {
	_u.mutation.SetHeartbeatAt(v)
	return _u
}

// SetNillableHeartbeatAt sets the "heartbeat_at" field if the given value is not nil.
func (_u *OpenAI5hWakePoolLeaseUpdate) SetNillableHeartbeatAt(v *time.Time) *OpenAI5hWakePoolLeaseUpdate {
	if v != nil {
		_u.SetHeartbeatAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OpenAI5hWakePoolLeaseUpdate) SetUpdatedAt(v time.Time) *OpenAI5hWakePoolLeaseUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OpenAI5hWakePoolLeaseMutation object of the builder.
func (_u *OpenAI5hWakePoolLeaseUpdate) Mutation() *OpenAI5hWakePoolLeaseMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OpenAI5hWakePoolLeaseUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAI5hWakePoolLeaseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OpenAI5hWakePoolLeaseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAI5hWakePoolLeaseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OpenAI5hWakePoolLeaseUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := openai5hwakepoollease.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAI5hWakePoolLeaseUpdate) check() error {
	if v, ok := _u.mutation.IdentityHash(); ok {
		if err := openai5hwakepoollease.IdentityHashValidator(v); err != nil {
			return &ValidationError{Name: "identity_hash", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakePoolLease.identity_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeaseOwner(); ok {
		if err := openai5hwakepoollease.LeaseOwnerValidator(v); err != nil {
			return &ValidationError{Name: "lease_owner", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakePoolLease.lease_owner": %w`, err)}
		}
	}
	return nil
}

func (_u *OpenAI5hWakePoolLeaseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openai5hwakepoollease.Table, openai5hwakepoollease.Columns, sqlgraph.NewFieldSpec(openai5hwakepoollease.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IdentityHash(); ok {
		_spec.SetField(openai5hwakepoollease.FieldIdentityHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(openai5hwakepoollease.FieldTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTaskID(); ok {
		_spec.AddField(openai5hwakepoollease.FieldTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ItemID(); ok {
		_spec.SetField(openai5hwakepoollease.FieldItemID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedItemID(); ok {
		_spec.AddField(openai5hwakepoollease.FieldItemID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LeaseOwner(); ok {
		_spec.SetField(openai5hwakepoollease.FieldLeaseOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.LeaseExpiresAt(); ok {
		_spec.SetField(openai5hwakepoollease.FieldLeaseExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.HeartbeatAt(); ok {
		_spec.SetField(openai5hwakepoollease.FieldHeartbeatAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(openai5hwakepoollease.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openai5hwakepoollease.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OpenAI5hWakePoolLeaseUpdateOne is the builder for updating a single OpenAI5hWakePoolLease entity.
type OpenAI5hWakePoolLeaseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OpenAI5hWakePoolLeaseMutation
}

// SetIdentityHash sets the "identity_hash" field.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) SetIdentityHash(v string) *OpenAI5hWakePoolLeaseUpdateOne {
	_u.mutation.SetIdentityHash(v)
	return _u
}

// SetNillableIdentityHash sets the "identity_hash" field if the given value is not nil.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) SetNillableIdentityHash(v *string) *OpenAI5hWakePoolLeaseUpdateOne {
	if v != nil {
		_u.SetIdentityHash(*v)
	}
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) SetTaskID(v int64) *OpenAI5hWakePoolLeaseUpdateOne {
	_u.mutation.ResetTaskID()
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) SetNillableTaskID(v *int64) *OpenAI5hWakePoolLeaseUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// AddTaskID adds value to the "task_id" field.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) AddTaskID(v int64) *OpenAI5hWakePoolLeaseUpdateOne {
	_u.mutation.AddTaskID(v)
	return _u
}

// SetItemID sets the "item_id" field.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) SetItemID(v int64) *OpenAI5hWakePoolLeaseUpdateOne {
	_u.mutation.ResetItemID()
	_u.mutation.SetItemID(v)
	return _u
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) SetNillableItemID(v *int64) *OpenAI5hWakePoolLeaseUpdateOne {
	if v != nil {
		_u.SetItemID(*v)
	}
	return _u
}

// AddItemID adds value to the "item_id" field.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) AddItemID(v int64) *OpenAI5hWakePoolLeaseUpdateOne {
	_u.mutation.AddItemID(v)
	return _u
}

// SetLeaseOwner sets the "lease_owner" field.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) SetLeaseOwner(v string) *OpenAI5hWakePoolLeaseUpdateOne {
	_u.mutation.SetLeaseOwner(v)
	return _u
}

// SetNillableLeaseOwner sets the "lease_owner" field if the given value is not nil.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) SetNillableLeaseOwner(v *string) *OpenAI5hWakePoolLeaseUpdateOne {
	if v != nil {
		_u.SetLeaseOwner(*v)
	}
	return _u
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) SetLeaseExpiresAt(v time.Time) *OpenAI5hWakePoolLeaseUpdateOne {
	_u.mutation.SetLeaseExpiresAt(v)
	return _u
}

// SetNillableLeaseExpiresAt sets the "lease_expires_at" field if the given value is not nil.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) SetNillableLeaseExpiresAt(v *time.Time) *OpenAI5hWakePoolLeaseUpdateOne {
	if v != nil {
		_u.SetLeaseExpiresAt(*v)
	}
	return _u
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) SetHeartbeatAt(v time.Time) *OpenAI5hWakePoolLeaseUpdateOne {
	_u.mutation.SetHeartbeatAt(v)
	return _u
}

// SetNillableHeartbeatAt sets the "heartbeat_at" field if the given value is not nil.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) SetNillableHeartbeatAt(v *time.Time) *OpenAI5hWakePoolLeaseUpdateOne {
	if v != nil {
		_u.SetHeartbeatAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) SetUpdatedAt(v time.Time) *OpenAI5hWakePoolLeaseUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OpenAI5hWakePoolLeaseMutation object of the builder.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) Mutation() *OpenAI5hWakePoolLeaseMutation {
	return _u.mutation
}

// Where appends a list predicates to the OpenAI5hWakePoolLeaseUpdate builder.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) Where(ps ...predicate.OpenAI5hWakePoolLease) *OpenAI5hWakePoolLeaseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) Select(field string, fields ...string) *OpenAI5hWakePoolLeaseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OpenAI5hWakePoolLease entity.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) Save(ctx context.Context) (*OpenAI5hWakePoolLease, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) SaveX(ctx context.Context) *OpenAI5hWakePoolLease {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := openai5hwakepoollease.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAI5hWakePoolLeaseUpdateOne) check() error {
	if v, ok := _u.mutation.IdentityHash(); ok {
		if err := openai5hwakepoollease.IdentityHashValidator(v); err != nil {
			return &ValidationError{Name: "identity_hash", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakePoolLease.identity_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeaseOwner(); ok {
		if err := openai5hwakepoollease.LeaseOwnerValidator(v); err != nil {
			return &ValidationError{Name: "lease_owner", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakePoolLease.lease_owner": %w`, err)}
		}
	}
	return nil
}

func (_u *OpenAI5hWakePoolLeaseUpdateOne) sqlSave(ctx context.Context) (_node *OpenAI5hWakePoolLease, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openai5hwakepoollease.Table, openai5hwakepoollease.Columns, sqlgraph.NewFieldSpec(openai5hwakepoollease.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OpenAI5hWakePoolLease.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, openai5hwakepoollease.FieldID)
		for _, f := range fields {
			if !openai5hwakepoollease.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != openai5hwakepoollease.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IdentityHash(); ok {
		_spec.SetField(openai5hwakepoollease.FieldIdentityHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(openai5hwakepoollease.FieldTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTaskID(); ok {
		_spec.AddField(openai5hwakepoollease.FieldTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ItemID(); ok {
		_spec.SetField(openai5hwakepoollease.FieldItemID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedItemID(); ok {
		_spec.AddField(openai5hwakepoollease.FieldItemID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LeaseOwner(); ok {
		_spec.SetField(openai5hwakepoollease.FieldLeaseOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.LeaseExpiresAt(); ok {
		_spec.SetField(openai5hwakepoollease.FieldLeaseExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.HeartbeatAt(); ok {
		_spec.SetField(openai5hwakepoollease.FieldHeartbeatAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(openai5hwakepoollease.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &OpenAI5hWakePoolLease{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openai5hwakepoollease.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
