// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openai5hwaketask"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OpenAI5hWakeTaskUpdate is the builder for updating OpenAI5hWakeTask entities.
type OpenAI5hWakeTaskUpdate struct {
	config
	hooks    []Hook
	mutation *OpenAI5hWakeTaskMutation
}

// Where appends a list predicates to the OpenAI5hWakeTaskUpdate builder.
func (_u *OpenAI5hWakeTaskUpdate) Where(ps ...predicate.OpenAI5hWakeTask) *OpenAI5hWakeTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *OpenAI5hWakeTaskUpdate) SetStatus(v string) *OpenAI5hWakeTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdate) SetNillableStatus(v *string) *OpenAI5hWakeTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEligibleAccountCount sets the "eligible_account_count" field.
func (_u *OpenAI5hWakeTaskUpdate) SetEligibleAccountCount(v int) *OpenAI5hWakeTaskUpdate {
	_u.mutation.ResetEligibleAccountCount()
	_u.mutation.SetEligibleAccountCount(v)
	return _u
}

// SetNillableEligibleAccountCount sets the "eligible_account_count" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdate) SetNillableEligibleAccountCount(v *int) *OpenAI5hWakeTaskUpdate {
	if v != nil {
		_u.SetEligibleAccountCount(*v)
	}
	return _u
}

// AddEligibleAccountCount adds value to the "eligible_account_count" field.
func (_u *OpenAI5hWakeTaskUpdate) AddEligibleAccountCount(v int) *OpenAI5hWakeTaskUpdate {
	_u.mutation.AddEligibleAccountCount(v)
	return _u
}

// SetActiveWindowCount sets the "active_window_count" field.
func (_u *OpenAI5hWakeTaskUpdate) SetActiveWindowCount(v int) *OpenAI5hWakeTaskUpdate {
	_u.mutation.ResetActiveWindowCount()
	_u.mutation.SetActiveWindowCount(v)
	return _u
}

// SetNillableActiveWindowCount sets the "active_window_count" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdate) SetNillableActiveWindowCount(v *int) *OpenAI5hWakeTaskUpdate {
	if v != nil {
		_u.SetActiveWindowCount(*v)
	}
	return _u
}

// AddActiveWindowCount adds value to the "active_window_count" field.
func (_u *OpenAI5hWakeTaskUpdate) AddActiveWindowCount(v int) *OpenAI5hWakeTaskUpdate {
	_u.mutation.AddActiveWindowCount(v)
	return _u
}

// SetEstimatedRequestCount sets the "estimated_request_count" field.
func (_u *OpenAI5hWakeTaskUpdate) SetEstimatedRequestCount(v int) *OpenAI5hWakeTaskUpdate {
	_u.mutation.ResetEstimatedRequestCount()
	_u.mutation.SetEstimatedRequestCount(v)
	return _u
}

// SetNillableEstimatedRequestCount sets the "estimated_request_count" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdate) SetNillableEstimatedRequestCount(v *int) *OpenAI5hWakeTaskUpdate {
	if v != nil {
		_u.SetEstimatedRequestCount(*v)
	}
	return _u
}

// AddEstimatedRequestCount adds value to the "estimated_request_count" field.
func (_u *OpenAI5hWakeTaskUpdate) AddEstimatedRequestCount(v int) *OpenAI5hWakeTaskUpdate {
	_u.mutation.AddEstimatedRequestCount(v)
	return _u
}

// SetTotalItems sets the "total_items" field.
func (_u *OpenAI5hWakeTaskUpdate) SetTotalItems(v int) *OpenAI5hWakeTaskUpdate {
	_u.mutation.ResetTotalItems()
	_u.mutation.SetTotalItems(v)
	return _u
}

// SetNillableTotalItems sets the "total_items" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdate) SetNillableTotalItems(v *int) *OpenAI5hWakeTaskUpdate {
	if v != nil {
		_u.SetTotalItems(*v)
	}
	return _u
}

// AddTotalItems adds value to the "total_items" field.
func (_u *OpenAI5hWakeTaskUpdate) AddTotalItems(v int) *OpenAI5hWakeTaskUpdate {
	_u.mutation.AddTotalItems(v)
	return _u
}

// SetProcessedItems sets the "processed_items" field.
func (_u *OpenAI5hWakeTaskUpdate) SetProcessedItems(v int) *OpenAI5hWakeTaskUpdate {
	_u.mutation.ResetProcessedItems()
	_u.mutation.SetProcessedItems(v)
	return _u
}

// SetNillableProcessedItems sets the "processed_items" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdate) SetNillableProcessedItems(v *int) *OpenAI5hWakeTaskUpdate {
	if v != nil {
		_u.SetProcessedItems(*v)
	}
	return _u
}

// AddProcessedItems adds value to the "processed_items" field.
func (_u *OpenAI5hWakeTaskUpdate) AddProcessedItems(v int) *OpenAI5hWakeTaskUpdate {
	_u.mutation.AddProcessedItems(v)
	return _u
}

// SetWokenCount sets the "woken_count" field.
func (_u *OpenAI5hWakeTaskUpdate) SetWokenCount(v int) *OpenAI5hWakeTaskUpdate {
	_u.mutation.ResetWokenCount()
	_u.mutation.SetWokenCount(v)
	return _u
}

// SetNillableWokenCount sets the "woken_count" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdate) SetNillableWokenCount(v *int) *OpenAI5hWakeTaskUpdate {
	if v != nil {
		_u.SetWokenCount(*v)
	}
	return _u
}

// AddWokenCount adds value to the "woken_count" field.
func (_u *OpenAI5hWakeTaskUpdate) AddWokenCount(v int) *OpenAI5hWakeTaskUpdate {
	_u.mutation.AddWokenCount(v)
	return _u
}

// SetSkippedActiveCount sets the "skipped_active_count" field.
func (_u *OpenAI5hWakeTaskUpdate) SetSkippedActiveCount(v int) *OpenAI5hWakeTaskUpdate {
	_u.mutation.ResetSkippedActiveCount()
	_u.mutation.SetSkippedActiveCount(v)
	return _u
}

// SetNillableSkippedActiveCount sets the "skipped_active_count" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdate) SetNillableSkippedActiveCount(v *int) *OpenAI5hWakeTaskUpdate {
	if v != nil {
		_u.SetSkippedActiveCount(*v)
	}
	return _u
}

// AddSkippedActiveCount adds value to the "skipped_active_count" field.
func (_u *OpenAI5hWakeTaskUpdate) AddSkippedActiveCount(v int) *OpenAI5hWakeTaskUpdate {
	_u.mutation.AddSkippedActiveCount(v)
	return _u
}

// SetFailedCount sets the "failed_count" field.
func (_u *OpenAI5hWakeTaskUpdate) SetFailedCount(v int) *OpenAI5hWakeTaskUpdate {
	_u.mutation.ResetFailedCount()
	_u.mutation.SetFailedCount(v)
	return _u
}

// SetNillableFailedCount sets the "failed_count" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdate) SetNillableFailedCount(v *int) *OpenAI5hWakeTaskUpdate {
	if v != nil {
		_u.SetFailedCount(*v)
	}
	return _u
}

// AddFailedCount adds value to the "failed_count" field.
func (_u *OpenAI5hWakeTaskUpdate) AddFailedCount(v int) *OpenAI5hWakeTaskUpdate {
	_u.mutation.AddFailedCount(v)
	return _u
}

// SetCancelledCount sets the "cancelled_count" field.
func (_u *OpenAI5hWakeTaskUpdate) SetCancelledCount(v int) *OpenAI5hWakeTaskUpdate {
	_u.mutation.ResetCancelledCount()
	_u.mutation.SetCancelledCount(v)
	return _u
}

// SetNillableCancelledCount sets the "cancelled_count" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdate) SetNillableCancelledCount(v *int) *OpenAI5hWakeTaskUpdate {
	if v != nil {
		_u.SetCancelledCount(*v)
	}
	return _u
}

// AddCancelledCount adds value to the "cancelled_count" field.
func (_u *OpenAI5hWakeTaskUpdate) AddCancelledCount(v int) *OpenAI5hWakeTaskUpdate {
	_u.mutation.AddCancelledCount(v)
	return _u
}

// SetRequestedByUserID sets the "requested_by_user_id" field.
func (_u *OpenAI5hWakeTaskUpdate) SetRequestedByUserID(v int64) *OpenAI5hWakeTaskUpdate {
	_u.mutation.ResetRequestedByUserID()
	_u.mutation.SetRequestedByUserID(v)
	return _u
}

// SetNillableRequestedByUserID sets the "requested_by_user_id" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdate) SetNillableRequestedByUserID(v *int64) *OpenAI5hWakeTaskUpdate {
	if v != nil {
		_u.SetRequestedByUserID(*v)
	}
	return _u
}

// AddRequestedByUserID adds value to the "requested_by_user_id" field.
func (_u *OpenAI5hWakeTaskUpdate) AddRequestedByUserID(v int64) *OpenAI5hWakeTaskUpdate {
	_u.mutation.AddRequestedByUserID(v)
	return _u
}

// ClearRequestedByUserID clears the value of the "requested_by_user_id" field.
func (_u *OpenAI5hWakeTaskUpdate) ClearRequestedByUserID() *OpenAI5hWakeTaskUpdate {
	_u.mutation.ClearRequestedByUserID()
	return _u
}

// SetRequestedByEmail sets the "requested_by_email" field.
func (_u *OpenAI5hWakeTaskUpdate) SetRequestedByEmail(v string) *OpenAI5hWakeTaskUpdate {
	_u.mutation.SetRequestedByEmail(v)
	return _u
}

// SetNillableRequestedByEmail sets the "requested_by_email" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdate) SetNillableRequestedByEmail(v *string) *OpenAI5hWakeTaskUpdate {
	if v != nil {
		_u.SetRequestedByEmail(*v)
	}
	return _u
}

// ClearRequestedByEmail clears the value of the "requested_by_email" field.
func (_u *OpenAI5hWakeTaskUpdate) ClearRequestedByEmail() *OpenAI5hWakeTaskUpdate {
	_u.mutation.ClearRequestedByEmail()
	return _u
}

// SetLeaseOwner sets the "lease_owner" field.
func (_u *OpenAI5hWakeTaskUpdate) SetLeaseOwner(v string) *OpenAI5hWakeTaskUpdate {
	_u.mutation.SetLeaseOwner(v)
	return _u
}

// SetNillableLeaseOwner sets the "lease_owner" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdate) SetNillableLeaseOwner(v *string) *OpenAI5hWakeTaskUpdate {
	if v != nil {
		_u.SetLeaseOwner(*v)
	}
	return _u
}

// ClearLeaseOwner clears the value of the "lease_owner" field.
func (_u *OpenAI5hWakeTaskUpdate) ClearLeaseOwner() *OpenAI5hWakeTaskUpdate {
	_u.mutation.ClearLeaseOwner()
	return _u
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (_u *OpenAI5hWakeTaskUpdate) SetLeaseExpiresAt(v time.Time) *OpenAI5hWakeTaskUpdate {
	_u.mutation.SetLeaseExpiresAt(v)
	return _u
}

// SetNillableLeaseExpiresAt sets the "lease_expires_at" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdate) SetNillableLeaseExpiresAt(v *time.Time) *OpenAI5hWakeTaskUpdate {
	if v != nil {
		_u.SetLeaseExpiresAt(*v)
	}
	return _u
}

// ClearLeaseExpiresAt clears the value of the "lease_expires_at" field.
func (_u *OpenAI5hWakeTaskUpdate) ClearLeaseExpiresAt() *OpenAI5hWakeTaskUpdate {
	_u.mutation.ClearLeaseExpiresAt()
	return _u
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (_u *OpenAI5hWakeTaskUpdate) SetHeartbeatAt(v time.Time) *OpenAI5hWakeTaskUpdate {
	_u.mutation.SetHeartbeatAt(v)
	return _u
}

// SetNillableHeartbeatAt sets the "heartbeat_at" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdate) SetNillableHeartbeatAt(v *time.Time) *OpenAI5hWakeTaskUpdate {
	if v != nil {
		_u.SetHeartbeatAt(*v)
	}
	return _u
}

// ClearHeartbeatAt clears the value of the "heartbeat_at" field.
func (_u *OpenAI5hWakeTaskUpdate) ClearHeartbeatAt() *OpenAI5hWakeTaskUpdate {
	_u.mutation.ClearHeartbeatAt()
	return _u
}

// SetEarliestResetAt sets the "earliest_reset_at" field.
func (_u *OpenAI5hWakeTaskUpdate) SetEarliestResetAt(v time.Time) *OpenAI5hWakeTaskUpdate {
	_u.mutation.SetEarliestResetAt(v)
	return _u
}

// SetNillableEarliestResetAt sets the "earliest_reset_at" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdate) SetNillableEarliestResetAt(v *time.Time) *OpenAI5hWakeTaskUpdate {
	if v != nil {
		_u.SetEarliestResetAt(*v)
	}
	return _u
}

// ClearEarliestResetAt clears the value of the "earliest_reset_at" field.
func (_u *OpenAI5hWakeTaskUpdate) ClearEarliestResetAt() *OpenAI5hWakeTaskUpdate {
	_u.mutation.ClearEarliestResetAt()
	return _u
}

// SetLatestResetAt sets the "latest_reset_at" field.
func (_u *OpenAI5hWakeTaskUpdate) SetLatestResetAt(v time.Time) *OpenAI5hWakeTaskUpdate {
	_u.mutation.SetLatestResetAt(v)
	return _u
}

// SetNillableLatestResetAt sets the "latest_reset_at" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdate) SetNillableLatestResetAt(v *time.Time) *OpenAI5hWakeTaskUpdate {
	if v != nil {
		_u.SetLatestResetAt(*v)
	}
	return _u
}

// ClearLatestResetAt clears the value of the "latest_reset_at" field.
func (_u *OpenAI5hWakeTaskUpdate) ClearLatestResetAt() *OpenAI5hWakeTaskUpdate {
	_u.mutation.ClearLatestResetAt()
	return _u
}

// SetCancelRequestedAt sets the "cancel_requested_at" field.
func (_u *OpenAI5hWakeTaskUpdate) SetCancelRequestedAt(v time.Time) *OpenAI5hWakeTaskUpdate {
	_u.mutation.SetCancelRequestedAt(v)
	return _u
}

// SetNillableCancelRequestedAt sets the "cancel_requested_at" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdate) SetNillableCancelRequestedAt(v *time.Time) *OpenAI5hWakeTaskUpdate {
	if v != nil {
		_u.SetCancelRequestedAt(*v)
	}
	return _u
}

// ClearCancelRequestedAt clears the value of the "cancel_requested_at" field.
func (_u *OpenAI5hWakeTaskUpdate) ClearCancelRequestedAt() *OpenAI5hWakeTaskUpdate {
	_u.mutation.ClearCancelRequestedAt()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *OpenAI5hWakeTaskUpdate) SetStartedAt(v time.Time) *OpenAI5hWakeTaskUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdate) SetNillableStartedAt(v *time.Time) *OpenAI5hWakeTaskUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *OpenAI5hWakeTaskUpdate) ClearStartedAt() *OpenAI5hWakeTaskUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *OpenAI5hWakeTaskUpdate) SetFinishedAt(v time.Time) *OpenAI5hWakeTaskUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdate) SetNillableFinishedAt(v *time.Time) *OpenAI5hWakeTaskUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *OpenAI5hWakeTaskUpdate) ClearFinishedAt() *OpenAI5hWakeTaskUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OpenAI5hWakeTaskUpdate) SetUpdatedAt(v time.Time) *OpenAI5hWakeTaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OpenAI5hWakeTaskMutation object of the builder.
func (_u *OpenAI5hWakeTaskUpdate) Mutation() *OpenAI5hWakeTaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OpenAI5hWakeTaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAI5hWakeTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OpenAI5hWakeTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAI5hWakeTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OpenAI5hWakeTaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := openai5hwaketask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAI5hWakeTaskUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := openai5hwaketask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakeTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestedByEmail(); ok {
		if err := openai5hwaketask.RequestedByEmailValidator(v); err != nil {
			return &ValidationError{Name: "requested_by_email", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakeTask.requested_by_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeaseOwner(); ok {
		if err := openai5hwaketask.LeaseOwnerValidator(v); err != nil {
			return &ValidationError{Name: "lease_owner", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakeTask.lease_owner": %w`, err)}
		}
	}
	return nil
}

func (_u *OpenAI5hWakeTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openai5hwaketask.Table, openai5hwaketask.Columns, sqlgraph.NewFieldSpec(openai5hwaketask.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(openai5hwaketask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.EligibleAccountCount(); ok {
		_spec.SetField(openai5hwaketask.FieldEligibleAccountCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEligibleAccountCount(); ok {
		_spec.AddField(openai5hwaketask.FieldEligibleAccountCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActiveWindowCount(); ok {
		_spec.SetField(openai5hwaketask.FieldActiveWindowCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActiveWindowCount(); ok {
		_spec.AddField(openai5hwaketask.FieldActiveWindowCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EstimatedRequestCount(); ok {
		_spec.SetField(openai5hwaketask.FieldEstimatedRequestCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEstimatedRequestCount(); ok {
		_spec.AddField(openai5hwaketask.FieldEstimatedRequestCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalItems(); ok {
		_spec.SetField(openai5hwaketask.FieldTotalItems, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalItems(); ok {
		_spec.AddField(openai5hwaketask.FieldTotalItems, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProcessedItems(); ok {
		_spec.SetField(openai5hwaketask.FieldProcessedItems, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProcessedItems(); ok {
		_spec.AddField(openai5hwaketask.FieldProcessedItems, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WokenCount(); ok {
		_spec.SetField(openai5hwaketask.FieldWokenCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWokenCount(); ok {
		_spec.AddField(openai5hwaketask.FieldWokenCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SkippedActiveCount(); ok {
		_spec.SetField(openai5hwaketask.FieldSkippedActiveCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSkippedActiveCount(); ok {
		_spec.AddField(openai5hwaketask.FieldSkippedActiveCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailedCount(); ok {
		_spec.SetField(openai5hwaketask.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailedCount(); ok {
		_spec.AddField(openai5hwaketask.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CancelledCount(); ok {
		_spec.SetField(openai5hwaketask.FieldCancelledCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCancelledCount(); ok {
		_spec.AddField(openai5hwaketask.FieldCancelledCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RequestedByUserID(); ok {
		_spec.SetField(openai5hwaketask.FieldRequestedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestedByUserID(); ok {
		_spec.AddField(openai5hwaketask.FieldRequestedByUserID, field.TypeInt64, value)
	}
	if _u.mutation.RequestedByUserIDCleared() {
		_spec.ClearField(openai5hwaketask.FieldRequestedByUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RequestedByEmail(); ok {
		_spec.SetField(openai5hwaketask.FieldRequestedByEmail, field.TypeString, value)
	}
	if _u.mutation.RequestedByEmailCleared() {
		_spec.ClearField(openai5hwaketask.FieldRequestedByEmail, field.TypeString)
	}
	if value, ok := _u.mutation.LeaseOwner(); ok {
		_spec.SetField(openai5hwaketask.FieldLeaseOwner, field.TypeString, value)
	}
	if _u.mutation.LeaseOwnerCleared() {
		_spec.ClearField(openai5hwaketask.FieldLeaseOwner, field.TypeString)
	}
	if value, ok := _u.mutation.LeaseExpiresAt(); ok {
		_spec.SetField(openai5hwaketask.FieldLeaseExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.LeaseExpiresAtCleared() {
		_spec.ClearField(openai5hwaketask.FieldLeaseExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HeartbeatAt(); ok {
		_spec.SetField(openai5hwaketask.FieldHeartbeatAt, field.TypeTime, value)
	}
	if _u.mutation.HeartbeatAtCleared() {
		_spec.ClearField(openai5hwaketask.FieldHeartbeatAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EarliestResetAt(); ok {
		_spec.SetField(openai5hwaketask.FieldEarliestResetAt, field.TypeTime, value)
	}
	if _u.mutation.EarliestResetAtCleared() {
		_spec.ClearField(openai5hwaketask.FieldEarliestResetAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LatestResetAt(); ok {
		_spec.SetField(openai5hwaketask.FieldLatestResetAt, field.TypeTime, value)
	}
	if _u.mutation.LatestResetAtCleared() {
		_spec.ClearField(openai5hwaketask.FieldLatestResetAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CancelRequestedAt(); ok {
		_spec.SetField(openai5hwaketask.FieldCancelRequestedAt, field.TypeTime, value)
	}
	if _u.mutation.CancelRequestedAtCleared() {
		_spec.ClearField(openai5hwaketask.FieldCancelRequestedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(openai5hwaketask.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(openai5hwaketask.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(openai5hwaketask.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(openai5hwaketask.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(openai5hwaketask.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openai5hwaketask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OpenAI5hWakeTaskUpdateOne is the builder for updating a single OpenAI5hWakeTask entity.
type OpenAI5hWakeTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OpenAI5hWakeTaskMutation
}

// SetStatus sets the "status" field.
func (_u *OpenAI5hWakeTaskUpdateOne) SetStatus(v string) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdateOne) SetNillableStatus(v *string) *OpenAI5hWakeTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEligibleAccountCount sets the "eligible_account_count" field.
func (_u *OpenAI5hWakeTaskUpdateOne) SetEligibleAccountCount(v int) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.ResetEligibleAccountCount()
	_u.mutation.SetEligibleAccountCount(v)
	return _u
}

// SetNillableEligibleAccountCount sets the "eligible_account_count" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdateOne) SetNillableEligibleAccountCount(v *int) *OpenAI5hWakeTaskUpdateOne {
	if v != nil {
		_u.SetEligibleAccountCount(*v)
	}
	return _u
}

// AddEligibleAccountCount adds value to the "eligible_account_count" field.
func (_u *OpenAI5hWakeTaskUpdateOne) AddEligibleAccountCount(v int) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.AddEligibleAccountCount(v)
	return _u
}

// SetActiveWindowCount sets the "active_window_count" field.
func (_u *OpenAI5hWakeTaskUpdateOne) SetActiveWindowCount(v int) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.ResetActiveWindowCount()
	_u.mutation.SetActiveWindowCount(v)
	return _u
}

// SetNillableActiveWindowCount sets the "active_window_count" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdateOne) SetNillableActiveWindowCount(v *int) *OpenAI5hWakeTaskUpdateOne {
	if v != nil {
		_u.SetActiveWindowCount(*v)
	}
	return _u
}

// AddActiveWindowCount adds value to the "active_window_count" field.
func (_u *OpenAI5hWakeTaskUpdateOne) AddActiveWindowCount(v int) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.AddActiveWindowCount(v)
	return _u
}

// SetEstimatedRequestCount sets the "estimated_request_count" field.
func (_u *OpenAI5hWakeTaskUpdateOne) SetEstimatedRequestCount(v int) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.ResetEstimatedRequestCount()
	_u.mutation.SetEstimatedRequestCount(v)
	return _u
}

// SetNillableEstimatedRequestCount sets the "estimated_request_count" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdateOne) SetNillableEstimatedRequestCount(v *int) *OpenAI5hWakeTaskUpdateOne {
	if v != nil {
		_u.SetEstimatedRequestCount(*v)
	}
	return _u
}

// AddEstimatedRequestCount adds value to the "estimated_request_count" field.
func (_u *OpenAI5hWakeTaskUpdateOne) AddEstimatedRequestCount(v int) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.AddEstimatedRequestCount(v)
	return _u
}

// SetTotalItems sets the "total_items" field.
func (_u *OpenAI5hWakeTaskUpdateOne) SetTotalItems(v int) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.ResetTotalItems()
	_u.mutation.SetTotalItems(v)
	return _u
}

// SetNillableTotalItems sets the "total_items" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdateOne) SetNillableTotalItems(v *int) *OpenAI5hWakeTaskUpdateOne {
	if v != nil {
		_u.SetTotalItems(*v)
	}
	return _u
}

// AddTotalItems adds value to the "total_items" field.
func (_u *OpenAI5hWakeTaskUpdateOne) AddTotalItems(v int) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.AddTotalItems(v)
	return _u
}

// SetProcessedItems sets the "processed_items" field.
func (_u *OpenAI5hWakeTaskUpdateOne) SetProcessedItems(v int) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.ResetProcessedItems()
	_u.mutation.SetProcessedItems(v)
	return _u
}

// SetNillableProcessedItems sets the "processed_items" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdateOne) SetNillableProcessedItems(v *int) *OpenAI5hWakeTaskUpdateOne {
	if v != nil {
		_u.SetProcessedItems(*v)
	}
	return _u
}

// AddProcessedItems adds value to the "processed_items" field.
func (_u *OpenAI5hWakeTaskUpdateOne) AddProcessedItems(v int) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.AddProcessedItems(v)
	return _u
}

// SetWokenCount sets the "woken_count" field.
func (_u *OpenAI5hWakeTaskUpdateOne) SetWokenCount(v int) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.ResetWokenCount()
	_u.mutation.SetWokenCount(v)
	return _u
}

// SetNillableWokenCount sets the "woken_count" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdateOne) SetNillableWokenCount(v *int) *OpenAI5hWakeTaskUpdateOne {
	if v != nil {
		_u.SetWokenCount(*v)
	}
	return _u
}

// AddWokenCount adds value to the "woken_count" field.
func (_u *OpenAI5hWakeTaskUpdateOne) AddWokenCount(v int) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.AddWokenCount(v)
	return _u
}

// SetSkippedActiveCount sets the "skipped_active_count" field.
func (_u *OpenAI5hWakeTaskUpdateOne) SetSkippedActiveCount(v int) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.ResetSkippedActiveCount()
	_u.mutation.SetSkippedActiveCount(v)
	return _u
}

// SetNillableSkippedActiveCount sets the "skipped_active_count" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdateOne) SetNillableSkippedActiveCount(v *int) *OpenAI5hWakeTaskUpdateOne {
	if v != nil {
		_u.SetSkippedActiveCount(*v)
	}
	return _u
}

// AddSkippedActiveCount adds value to the "skipped_active_count" field.
func (_u *OpenAI5hWakeTaskUpdateOne) AddSkippedActiveCount(v int) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.AddSkippedActiveCount(v)
	return _u
}

// SetFailedCount sets the "failed_count" field.
func (_u *OpenAI5hWakeTaskUpdateOne) SetFailedCount(v int) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.ResetFailedCount()
	_u.mutation.SetFailedCount(v)
	return _u
}

// SetNillableFailedCount sets the "failed_count" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdateOne) SetNillableFailedCount(v *int) *OpenAI5hWakeTaskUpdateOne {
	if v != nil {
		_u.SetFailedCount(*v)
	}
	return _u
}

// AddFailedCount adds value to the "failed_count" field.
func (_u *OpenAI5hWakeTaskUpdateOne) AddFailedCount(v int) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.AddFailedCount(v)
	return _u
}

// SetCancelledCount sets the "cancelled_count" field.
func (_u *OpenAI5hWakeTaskUpdateOne) SetCancelledCount(v int) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.ResetCancelledCount()
	_u.mutation.SetCancelledCount(v)
	return _u
}

// SetNillableCancelledCount sets the "cancelled_count" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdateOne) SetNillableCancelledCount(v *int) *OpenAI5hWakeTaskUpdateOne {
	if v != nil {
		_u.SetCancelledCount(*v)
	}
	return _u
}

// AddCancelledCount adds value to the "cancelled_count" field.
func (_u *OpenAI5hWakeTaskUpdateOne) AddCancelledCount(v int) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.AddCancelledCount(v)
	return _u
}

// SetRequestedByUserID sets the "requested_by_user_id" field.
func (_u *OpenAI5hWakeTaskUpdateOne) SetRequestedByUserID(v int64) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.ResetRequestedByUserID()
	_u.mutation.SetRequestedByUserID(v)
	return _u
}

// SetNillableRequestedByUserID sets the "requested_by_user_id" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdateOne) SetNillableRequestedByUserID(v *int64) *OpenAI5hWakeTaskUpdateOne {
	if v != nil {
		_u.SetRequestedByUserID(*v)
	}
	return _u
}

// AddRequestedByUserID adds value to the "requested_by_user_id" field.
func (_u *OpenAI5hWakeTaskUpdateOne) AddRequestedByUserID(v int64) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.AddRequestedByUserID(v)
	return _u
}

// ClearRequestedByUserID clears the value of the "requested_by_user_id" field.
func (_u *OpenAI5hWakeTaskUpdateOne) ClearRequestedByUserID() *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.ClearRequestedByUserID()
	return _u
}

// SetRequestedByEmail sets the "requested_by_email" field.
func (_u *OpenAI5hWakeTaskUpdateOne) SetRequestedByEmail(v string) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.SetRequestedByEmail(v)
	return _u
}

// SetNillableRequestedByEmail sets the "requested_by_email" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdateOne) SetNillableRequestedByEmail(v *string) *OpenAI5hWakeTaskUpdateOne {
	if v != nil {
		_u.SetRequestedByEmail(*v)
	}
	return _u
}

// ClearRequestedByEmail clears the value of the "requested_by_email" field.
func (_u *OpenAI5hWakeTaskUpdateOne) ClearRequestedByEmail() *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.ClearRequestedByEmail()
	return _u
}

// SetLeaseOwner sets the "lease_owner" field.
func (_u *OpenAI5hWakeTaskUpdateOne) SetLeaseOwner(v string) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.SetLeaseOwner(v)
	return _u
}

// SetNillableLeaseOwner sets the "lease_owner" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdateOne) SetNillableLeaseOwner(v *string) *OpenAI5hWakeTaskUpdateOne {
	if v != nil {
		_u.SetLeaseOwner(*v)
	}
	return _u
}

// ClearLeaseOwner clears the value of the "lease_owner" field.
func (_u *OpenAI5hWakeTaskUpdateOne) ClearLeaseOwner() *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.ClearLeaseOwner()
	return _u
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (_u *OpenAI5hWakeTaskUpdateOne) SetLeaseExpiresAt(v time.Time) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.SetLeaseExpiresAt(v)
	return _u
}

// SetNillableLeaseExpiresAt sets the "lease_expires_at" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdateOne) SetNillableLeaseExpiresAt(v *time.Time) *OpenAI5hWakeTaskUpdateOne {
	if v != nil {
		_u.SetLeaseExpiresAt(*v)
	}
	return _u
}

// ClearLeaseExpiresAt clears the value of the "lease_expires_at" field.
func (_u *OpenAI5hWakeTaskUpdateOne) ClearLeaseExpiresAt() *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.ClearLeaseExpiresAt()
	return _u
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (_u *OpenAI5hWakeTaskUpdateOne) SetHeartbeatAt(v time.Time) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.SetHeartbeatAt(v)
	return _u
}

// SetNillableHeartbeatAt sets the "heartbeat_at" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdateOne) SetNillableHeartbeatAt(v *time.Time) *OpenAI5hWakeTaskUpdateOne {
	if v != nil {
		_u.SetHeartbeatAt(*v)
	}
	return _u
}

// ClearHeartbeatAt clears the value of the "heartbeat_at" field.
func (_u *OpenAI5hWakeTaskUpdateOne) ClearHeartbeatAt() *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.ClearHeartbeatAt()
	return _u
}

// SetEarliestResetAt sets the "earliest_reset_at" field.
func (_u *OpenAI5hWakeTaskUpdateOne) SetEarliestResetAt(v time.Time) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.SetEarliestResetAt(v)
	return _u
}

// SetNillableEarliestResetAt sets the "earliest_reset_at" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdateOne) SetNillableEarliestResetAt(v *time.Time) *OpenAI5hWakeTaskUpdateOne {
	if v != nil {
		_u.SetEarliestResetAt(*v)
	}
	return _u
}

// ClearEarliestResetAt clears the value of the "earliest_reset_at" field.
func (_u *OpenAI5hWakeTaskUpdateOne) ClearEarliestResetAt() *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.ClearEarliestResetAt()
	return _u
}

// SetLatestResetAt sets the "latest_reset_at" field.
func (_u *OpenAI5hWakeTaskUpdateOne) SetLatestResetAt(v time.Time) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.SetLatestResetAt(v)
	return _u
}

// SetNillableLatestResetAt sets the "latest_reset_at" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdateOne) SetNillableLatestResetAt(v *time.Time) *OpenAI5hWakeTaskUpdateOne {
	if v != nil {
		_u.SetLatestResetAt(*v)
	}
	return _u
}

// ClearLatestResetAt clears the value of the "latest_reset_at" field.
func (_u *OpenAI5hWakeTaskUpdateOne) ClearLatestResetAt() *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.ClearLatestResetAt()
	return _u
}

// SetCancelRequestedAt sets the "cancel_requested_at" field.
func (_u *OpenAI5hWakeTaskUpdateOne) SetCancelRequestedAt(v time.Time) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.SetCancelRequestedAt(v)
	return _u
}

// SetNillableCancelRequestedAt sets the "cancel_requested_at" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdateOne) SetNillableCancelRequestedAt(v *time.Time) *OpenAI5hWakeTaskUpdateOne {
	if v != nil {
		_u.SetCancelRequestedAt(*v)
	}
	return _u
}

// ClearCancelRequestedAt clears the value of the "cancel_requested_at" field.
func (_u *OpenAI5hWakeTaskUpdateOne) ClearCancelRequestedAt() *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.ClearCancelRequestedAt()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *OpenAI5hWakeTaskUpdateOne) SetStartedAt(v time.Time) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdateOne) SetNillableStartedAt(v *time.Time) *OpenAI5hWakeTaskUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *OpenAI5hWakeTaskUpdateOne) ClearStartedAt() *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *OpenAI5hWakeTaskUpdateOne) SetFinishedAt(v time.Time) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *OpenAI5hWakeTaskUpdateOne) SetNillableFinishedAt(v *time.Time) *OpenAI5hWakeTaskUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *OpenAI5hWakeTaskUpdateOne) ClearFinishedAt() *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OpenAI5hWakeTaskUpdateOne) SetUpdatedAt(v time.Time) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OpenAI5hWakeTaskMutation object of the builder.
func (_u *OpenAI5hWakeTaskUpdateOne) Mutation() *OpenAI5hWakeTaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the OpenAI5hWakeTaskUpdate builder.
func (_u *OpenAI5hWakeTaskUpdateOne) Where(ps ...predicate.OpenAI5hWakeTask) *OpenAI5hWakeTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OpenAI5hWakeTaskUpdateOne) Select(field string, fields ...string) *OpenAI5hWakeTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OpenAI5hWakeTask entity.
func (_u *OpenAI5hWakeTaskUpdateOne) Save(ctx context.Context) (*OpenAI5hWakeTask, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAI5hWakeTaskUpdateOne) SaveX(ctx context.Context) *OpenAI5hWakeTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OpenAI5hWakeTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAI5hWakeTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OpenAI5hWakeTaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := openai5hwaketask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAI5hWakeTaskUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := openai5hwaketask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakeTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestedByEmail(); ok {
		if err := openai5hwaketask.RequestedByEmailValidator(v); err != nil {
			return &ValidationError{Name: "requested_by_email", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakeTask.requested_by_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeaseOwner(); ok {
		if err := openai5hwaketask.LeaseOwnerValidator(v); err != nil {
			return &ValidationError{Name: "lease_owner", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakeTask.lease_owner": %w`, err)}
		}
	}
	return nil
}

func (_u *OpenAI5hWakeTaskUpdateOne) sqlSave(ctx context.Context) (_node *OpenAI5hWakeTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openai5hwaketask.Table, openai5hwaketask.Columns, sqlgraph.NewFieldSpec(openai5hwaketask.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OpenAI5hWakeTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, openai5hwaketask.FieldID)
		for _, f := range fields {
			if !openai5hwaketask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != openai5hwaketask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(openai5hwaketask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.EligibleAccountCount(); ok {
		_spec.SetField(openai5hwaketask.FieldEligibleAccountCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEligibleAccountCount(); ok {
		_spec.AddField(openai5hwaketask.FieldEligibleAccountCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActiveWindowCount(); ok {
		_spec.SetField(openai5hwaketask.FieldActiveWindowCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActiveWindowCount(); ok {
		_spec.AddField(openai5hwaketask.FieldActiveWindowCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EstimatedRequestCount(); ok {
		_spec.SetField(openai5hwaketask.FieldEstimatedRequestCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEstimatedRequestCount(); ok {
		_spec.AddField(openai5hwaketask.FieldEstimatedRequestCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalItems(); ok {
		_spec.SetField(openai5hwaketask.FieldTotalItems, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalItems(); ok {
		_spec.AddField(openai5hwaketask.FieldTotalItems, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProcessedItems(); ok {
		_spec.SetField(openai5hwaketask.FieldProcessedItems, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProcessedItems(); ok {
		_spec.AddField(openai5hwaketask.FieldProcessedItems, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WokenCount(); ok {
		_spec.SetField(openai5hwaketask.FieldWokenCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWokenCount(); ok {
		_spec.AddField(openai5hwaketask.FieldWokenCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SkippedActiveCount(); ok {
		_spec.SetField(openai5hwaketask.FieldSkippedActiveCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSkippedActiveCount(); ok {
		_spec.AddField(openai5hwaketask.FieldSkippedActiveCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailedCount(); ok {
		_spec.SetField(openai5hwaketask.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailedCount(); ok {
		_spec.AddField(openai5hwaketask.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CancelledCount(); ok {
		_spec.SetField(openai5hwaketask.FieldCancelledCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCancelledCount(); ok {
		_spec.AddField(openai5hwaketask.FieldCancelledCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RequestedByUserID(); ok {
		_spec.SetField(openai5hwaketask.FieldRequestedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestedByUserID(); ok {
		_spec.AddField(openai5hwaketask.FieldRequestedByUserID, field.TypeInt64, value)
	}
	if _u.mutation.RequestedByUserIDCleared() {
		_spec.ClearField(openai5hwaketask.FieldRequestedByUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RequestedByEmail(); ok {
		_spec.SetField(openai5hwaketask.FieldRequestedByEmail, field.TypeString, value)
	}
	if _u.mutation.RequestedByEmailCleared() {
		_spec.ClearField(openai5hwaketask.FieldRequestedByEmail, field.TypeString)
	}
	if value, ok := _u.mutation.LeaseOwner(); ok {
		_spec.SetField(openai5hwaketask.FieldLeaseOwner, field.TypeString, value)
	}
	if _u.mutation.LeaseOwnerCleared() {
		_spec.ClearField(openai5hwaketask.FieldLeaseOwner, field.TypeString)
	}
	if value, ok := _u.mutation.LeaseExpiresAt(); ok {
		_spec.SetField(openai5hwaketask.FieldLeaseExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.LeaseExpiresAtCleared() {
		_spec.ClearField(openai5hwaketask.FieldLeaseExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HeartbeatAt(); ok {
		_spec.SetField(openai5hwaketask.FieldHeartbeatAt, field.TypeTime, value)
	}
	if _u.mutation.HeartbeatAtCleared() {
		_spec.ClearField(openai5hwaketask.FieldHeartbeatAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EarliestResetAt(); ok {
		_spec.SetField(openai5hwaketask.FieldEarliestResetAt, field.TypeTime, value)
	}
	if _u.mutation.EarliestResetAtCleared() {
		_spec.ClearField(openai5hwaketask.FieldEarliestResetAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LatestResetAt(); ok {
		_spec.SetField(openai5hwaketask.FieldLatestResetAt, field.TypeTime, value)
	}
	if _u.mutation.LatestResetAtCleared() {
		_spec.ClearField(openai5hwaketask.FieldLatestResetAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CancelRequestedAt(); ok {
		_spec.SetField(openai5hwaketask.FieldCancelRequestedAt, field.TypeTime, value)
	}
	if _u.mutation.CancelRequestedAtCleared() {
		_spec.ClearField(openai5hwaketask.FieldCancelRequestedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(openai5hwaketask.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(openai5hwaketask.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(openai5hwaketask.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(openai5hwaketask.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(openai5hwaketask.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &OpenAI5hWakeTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openai5hwaketask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
