// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openai5hwakepoollease"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OpenAI5hWakePoolLeaseDelete is the builder for deleting a OpenAI5hWakePoolLease entity.
type OpenAI5hWakePoolLeaseDelete struct {
	config
	hooks    []Hook
	mutation *OpenAI5hWakePoolLeaseMutation
}

// Where appends a list predicates to the OpenAI5hWakePoolLeaseDelete builder.
func (_d *OpenAI5hWakePoolLeaseDelete) Where(ps ...predicate.OpenAI5hWakePoolLease) *OpenAI5hWakePoolLeaseDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OpenAI5hWakePoolLeaseDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OpenAI5hWakePoolLeaseDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OpenAI5hWakePoolLeaseDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(openai5hwakepoollease.Table, sqlgraph.NewFieldSpec(openai5hwakepoollease.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OpenAI5hWakePoolLeaseDeleteOne is the builder for deleting a single OpenAI5hWakePoolLease entity.
type OpenAI5hWakePoolLeaseDeleteOne struct {
	_d *OpenAI5hWakePoolLeaseDelete
}

// Where appends a list predicates to the OpenAI5hWakePoolLeaseDelete builder.
func (_d *OpenAI5hWakePoolLeaseDeleteOne) Where(ps ...predicate.OpenAI5hWakePoolLease) *OpenAI5hWakePoolLeaseDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OpenAI5hWakePoolLeaseDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{openai5hwakepoollease.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OpenAI5hWakePoolLeaseDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
