// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openai5hwakepoollease"
)

// OpenAI5hWakePoolLeaseCreate is the builder for creating a OpenAI5hWakePoolLease entity.
type OpenAI5hWakePoolLeaseCreate struct {
	config
	mutation *OpenAI5hWakePoolLeaseMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetIdentityHash sets the "identity_hash" field.
func (_c *OpenAI5hWakePoolLeaseCreate) SetIdentityHash(v string) *OpenAI5hWakePoolLeaseCreate {
	_c.mutation.SetIdentityHash(v)
	return _c
}

// SetTaskID sets the "task_id" field.
func (_c *OpenAI5hWakePoolLeaseCreate) SetTaskID(v int64) *OpenAI5hWakePoolLeaseCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetItemID sets the "item_id" field.
func (_c *OpenAI5hWakePoolLeaseCreate) SetItemID(v int64) *OpenAI5hWakePoolLeaseCreate {
	_c.mutation.SetItemID(v)
	return _c
}

// SetLeaseOwner sets the "lease_owner" field.
func (_c *OpenAI5hWakePoolLeaseCreate) SetLeaseOwner(v string) *OpenAI5hWakePoolLeaseCreate {
	_c.mutation.SetLeaseOwner(v)
	return _c
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (_c *OpenAI5hWakePoolLeaseCreate) SetLeaseExpiresAt(v time.Time) *OpenAI5hWakePoolLeaseCreate {
	_c.mutation.SetLeaseExpiresAt(v)
	return _c
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (_c *OpenAI5hWakePoolLeaseCreate) SetHeartbeatAt(v time.Time) *OpenAI5hWakePoolLeaseCreate {
	_c.mutation.SetHeartbeatAt(v)
	return _c
}

// SetNillableHeartbeatAt sets the "heartbeat_at" field if the given value is not nil.
func (_c *OpenAI5hWakePoolLeaseCreate) SetNillableHeartbeatAt(v *time.Time) *OpenAI5hWakePoolLeaseCreate {
	if v != nil {
		_c.SetHeartbeatAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OpenAI5hWakePoolLeaseCreate) SetCreatedAt(v time.Time) *OpenAI5hWakePoolLeaseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OpenAI5hWakePoolLeaseCreate) SetNillableCreatedAt(v *time.Time) *OpenAI5hWakePoolLeaseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OpenAI5hWakePoolLeaseCreate) SetUpdatedAt(v time.Time) *OpenAI5hWakePoolLeaseCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OpenAI5hWakePoolLeaseCreate) SetNillableUpdatedAt(v *time.Time) *OpenAI5hWakePoolLeaseCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the OpenAI5hWakePoolLeaseMutation object of the builder.
func (_c *OpenAI5hWakePoolLeaseCreate) Mutation() *OpenAI5hWakePoolLeaseMutation {
	return _c.mutation
}

// Save creates the OpenAI5hWakePoolLease in the database.
func (_c *OpenAI5hWakePoolLeaseCreate) Save(ctx context.Context) (*OpenAI5hWakePoolLease, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OpenAI5hWakePoolLeaseCreate) SaveX(ctx context.Context) *OpenAI5hWakePoolLease {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OpenAI5hWakePoolLeaseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OpenAI5hWakePoolLeaseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OpenAI5hWakePoolLeaseCreate) defaults() {
	if _, ok := _c.mutation.HeartbeatAt(); !ok {
		v := openai5hwakepoollease.DefaultHeartbeatAt()
		_c.mutation.SetHeartbeatAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := openai5hwakepoollease.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := openai5hwakepoollease.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OpenAI5hWakePoolLeaseCreate) check() error {
	if _, ok := _c.mutation.IdentityHash(); !ok {
		return &ValidationError{Name: "identity_hash", err: errors.New(`ent: missing required field "OpenAI5hWakePoolLease.identity_hash"`)}
	}
	if v, ok := _c.mutation.IdentityHash(); ok {
		if err := openai5hwakepoollease.IdentityHashValidator(v); err != nil {
			return &ValidationError{Name: "identity_hash", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakePoolLease.identity_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "OpenAI5hWakePoolLease.task_id"`)}
	}
	if _, ok := _c.mutation.ItemID(); !ok {
		return &ValidationError{Name: "item_id", err: errors.New(`ent: missing required field "OpenAI5hWakePoolLease.item_id"`)}
	}
	if _, ok := _c.mutation.LeaseOwner(); !ok {
		return &ValidationError{Name: "lease_owner", err: errors.New(`ent: missing required field "OpenAI5hWakePoolLease.lease_owner"`)}
	}
	if v, ok := _c.mutation.LeaseOwner(); ok {
		if err := openai5hwakepoollease.LeaseOwnerValidator(v); err != nil {
			return &ValidationError{Name: "lease_owner", err: fmt.Errorf(`ent: validator failed for field "OpenAI5hWakePoolLease.lease_owner": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LeaseExpiresAt(); !ok {
		return &ValidationError{Name: "lease_expires_at", err: errors.New(`ent: missing required field "OpenAI5hWakePoolLease.lease_expires_at"`)}
	}
	if _, ok := _c.mutation.HeartbeatAt(); !ok {
		return &ValidationError{Name: "heartbeat_at", err: errors.New(`ent: missing required field "OpenAI5hWakePoolLease.heartbeat_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OpenAI5hWakePoolLease.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OpenAI5hWakePoolLease.updated_at"`)}
	}
	return nil
}

func (_c *OpenAI5hWakePoolLeaseCreate) sqlSave(ctx context.Context) (*OpenAI5hWakePoolLease, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OpenAI5hWakePoolLeaseCreate) createSpec() (*OpenAI5hWakePoolLease, *sqlgraph.CreateSpec) {
	var (
		_node = &OpenAI5hWakePoolLease{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(openai5hwakepoollease.Table, sqlgraph.NewFieldSpec(openai5hwakepoollease.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.IdentityHash(); ok {
		_spec.SetField(openai5hwakepoollease.FieldIdentityHash, field.TypeString, value)
		_node.IdentityHash = value
	}
	if value, ok := _c.mutation.TaskID(); ok {
		_spec.SetField(openai5hwakepoollease.FieldTaskID, field.TypeInt64, value)
		_node.TaskID = value
	}
	if value, ok := _c.mutation.ItemID(); ok {
		_spec.SetField(openai5hwakepoollease.FieldItemID, field.TypeInt64, value)
		_node.ItemID = value
	}
	if value, ok := _c.mutation.LeaseOwner(); ok {
		_spec.SetField(openai5hwakepoollease.FieldLeaseOwner, field.TypeString, value)
		_node.LeaseOwner = value
	}
	if value, ok := _c.mutation.LeaseExpiresAt(); ok {
		_spec.SetField(openai5hwakepoollease.FieldLeaseExpiresAt, field.TypeTime, value)
		_node.LeaseExpiresAt = value
	}
	if value, ok := _c.mutation.HeartbeatAt(); ok {
		_spec.SetField(openai5hwakepoollease.FieldHeartbeatAt, field.TypeTime, value)
		_node.HeartbeatAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(openai5hwakepoollease.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(openai5hwakepoollease.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OpenAI5hWakePoolLease.Create().
//		SetIdentityHash(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OpenAI5hWakePoolLeaseUpsert) {
//			SetIdentityHash(v+v).
//		}).
//		Exec(ctx)
func (_c *OpenAI5hWakePoolLeaseCreate) OnConflict(opts ...sql.ConflictOption) *OpenAI5hWakePoolLeaseUpsertOne {
	_c.conflict = opts
	return &OpenAI5hWakePoolLeaseUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OpenAI5hWakePoolLease.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OpenAI5hWakePoolLeaseCreate) OnConflictColumns(columns ...string) *OpenAI5hWakePoolLeaseUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OpenAI5hWakePoolLeaseUpsertOne{
		create: _c,
	}
}

type (
	// OpenAI5hWakePoolLeaseUpsertOne is the builder for "upsert"-ing
	//  one OpenAI5hWakePoolLease node.
	OpenAI5hWakePoolLeaseUpsertOne struct {
		create *OpenAI5hWakePoolLeaseCreate
	}

	// OpenAI5hWakePoolLeaseUpsert is the "OnConflict" setter.
	OpenAI5hWakePoolLeaseUpsert struct {
		*sql.UpdateSet
	}
)

// SetIdentityHash sets the "identity_hash" field.
func (u *OpenAI5hWakePoolLeaseUpsert) SetIdentityHash(v string) *OpenAI5hWakePoolLeaseUpsert {
	u.Set(openai5hwakepoollease.FieldIdentityHash, v)
	return u
}

// UpdateIdentityHash sets the "identity_hash" field to the value that was provided on create.
func (u *OpenAI5hWakePoolLeaseUpsert) UpdateIdentityHash() *OpenAI5hWakePoolLeaseUpsert {
	u.SetExcluded(openai5hwakepoollease.FieldIdentityHash)
	return u
}

// SetTaskID sets the "task_id" field.
func (u *OpenAI5hWakePoolLeaseUpsert) SetTaskID(v int64) *OpenAI5hWakePoolLeaseUpsert {
	u.Set(openai5hwakepoollease.FieldTaskID, v)
	return u
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *OpenAI5hWakePoolLeaseUpsert) UpdateTaskID() *OpenAI5hWakePoolLeaseUpsert {
	u.SetExcluded(openai5hwakepoollease.FieldTaskID)
	return u
}

// AddTaskID adds v to the "task_id" field.
func (u *OpenAI5hWakePoolLeaseUpsert) AddTaskID(v int64) *OpenAI5hWakePoolLeaseUpsert {
	u.Add(openai5hwakepoollease.FieldTaskID, v)
	return u
}

// SetItemID sets the "item_id" field.
func (u *OpenAI5hWakePoolLeaseUpsert) SetItemID(v int64) *OpenAI5hWakePoolLeaseUpsert {
	u.Set(openai5hwakepoollease.FieldItemID, v)
	return u
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *OpenAI5hWakePoolLeaseUpsert) UpdateItemID() *OpenAI5hWakePoolLeaseUpsert {
	u.SetExcluded(openai5hwakepoollease.FieldItemID)
	return u
}

// AddItemID adds v to the "item_id" field.
func (u *OpenAI5hWakePoolLeaseUpsert) AddItemID(v int64) *OpenAI5hWakePoolLeaseUpsert {
	u.Add(openai5hwakepoollease.FieldItemID, v)
	return u
}

// SetLeaseOwner sets the "lease_owner" field.
func (u *OpenAI5hWakePoolLeaseUpsert) SetLeaseOwner(v string) *OpenAI5hWakePoolLeaseUpsert {
	u.Set(openai5hwakepoollease.FieldLeaseOwner, v)
	return u
}

// UpdateLeaseOwner sets the "lease_owner" field to the value that was provided on create.
func (u *OpenAI5hWakePoolLeaseUpsert) UpdateLeaseOwner() *OpenAI5hWakePoolLeaseUpsert {
	u.SetExcluded(openai5hwakepoollease.FieldLeaseOwner)
	return u
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (u *OpenAI5hWakePoolLeaseUpsert) SetLeaseExpiresAt(v time.Time) *OpenAI5hWakePoolLeaseUpsert {
	u.Set(openai5hwakepoollease.FieldLeaseExpiresAt, v)
	return u
}

// UpdateLeaseExpiresAt sets the "lease_expires_at" field to the value that was provided on create.
func (u *OpenAI5hWakePoolLeaseUpsert) UpdateLeaseExpiresAt() *OpenAI5hWakePoolLeaseUpsert {
	u.SetExcluded(openai5hwakepoollease.FieldLeaseExpiresAt)
	return u
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (u *OpenAI5hWakePoolLeaseUpsert) SetHeartbeatAt(v time.Time) *OpenAI5hWakePoolLeaseUpsert {
	u.Set(openai5hwakepoollease.FieldHeartbeatAt, v)
	return u
}

// UpdateHeartbeatAt sets the "heartbeat_at" field to the value that was provided on create.
func (u *OpenAI5hWakePoolLeaseUpsert) UpdateHeartbeatAt() *OpenAI5hWakePoolLeaseUpsert {
	u.SetExcluded(openai5hwakepoollease.FieldHeartbeatAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAI5hWakePoolLeaseUpsert) SetUpdatedAt(v time.Time) *OpenAI5hWakePoolLeaseUpsert {
	u.Set(openai5hwakepoollease.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAI5hWakePoolLeaseUpsert) UpdateUpdatedAt() *OpenAI5hWakePoolLeaseUpsert {
	u.SetExcluded(openai5hwakepoollease.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OpenAI5hWakePoolLease.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OpenAI5hWakePoolLeaseUpsertOne) UpdateNewValues() *OpenAI5hWakePoolLeaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(openai5hwakepoollease.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OpenAI5hWakePoolLease.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OpenAI5hWakePoolLeaseUpsertOne) Ignore() *OpenAI5hWakePoolLeaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OpenAI5hWakePoolLeaseUpsertOne) DoNothing() *OpenAI5hWakePoolLeaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OpenAI5hWakePoolLeaseCreate.OnConflict
// documentation for more info.
func (u *OpenAI5hWakePoolLeaseUpsertOne) Update(set func(*OpenAI5hWakePoolLeaseUpsert)) *OpenAI5hWakePoolLeaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OpenAI5hWakePoolLeaseUpsert{UpdateSet: update})
	}))
	return u
}

// SetIdentityHash sets the "identity_hash" field.
func (u *OpenAI5hWakePoolLeaseUpsertOne) SetIdentityHash(v string) *OpenAI5hWakePoolLeaseUpsertOne {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.SetIdentityHash(v)
	})
}

// UpdateIdentityHash sets the "identity_hash" field to the value that was provided on create.
func (u *OpenAI5hWakePoolLeaseUpsertOne) UpdateIdentityHash() *OpenAI5hWakePoolLeaseUpsertOne {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.UpdateIdentityHash()
	})
}

// SetTaskID sets the "task_id" field.
func (u *OpenAI5hWakePoolLeaseUpsertOne) SetTaskID(v int64) *OpenAI5hWakePoolLeaseUpsertOne {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.SetTaskID(v)
	})
}

// AddTaskID adds v to the "task_id" field.
func (u *OpenAI5hWakePoolLeaseUpsertOne) AddTaskID(v int64) *OpenAI5hWakePoolLeaseUpsertOne {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.AddTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *OpenAI5hWakePoolLeaseUpsertOne) UpdateTaskID() *OpenAI5hWakePoolLeaseUpsertOne {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.UpdateTaskID()
	})
}

// SetItemID sets the "item_id" field.
func (u *OpenAI5hWakePoolLeaseUpsertOne) SetItemID(v int64) *OpenAI5hWakePoolLeaseUpsertOne {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.SetItemID(v)
	})
}

// AddItemID adds v to the "item_id" field.
func (u *OpenAI5hWakePoolLeaseUpsertOne) AddItemID(v int64) *OpenAI5hWakePoolLeaseUpsertOne {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.AddItemID(v)
	})
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *OpenAI5hWakePoolLeaseUpsertOne) UpdateItemID() *OpenAI5hWakePoolLeaseUpsertOne {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.UpdateItemID()
	})
}

// SetLeaseOwner sets the "lease_owner" field.
func (u *OpenAI5hWakePoolLeaseUpsertOne) SetLeaseOwner(v string) *OpenAI5hWakePoolLeaseUpsertOne {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.SetLeaseOwner(v)
	})
}

// UpdateLeaseOwner sets the "lease_owner" field to the value that was provided on create.
func (u *OpenAI5hWakePoolLeaseUpsertOne) UpdateLeaseOwner() *OpenAI5hWakePoolLeaseUpsertOne {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.UpdateLeaseOwner()
	})
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (u *OpenAI5hWakePoolLeaseUpsertOne) SetLeaseExpiresAt(v time.Time) *OpenAI5hWakePoolLeaseUpsertOne {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.SetLeaseExpiresAt(v)
	})
}

// UpdateLeaseExpiresAt sets the "lease_expires_at" field to the value that was provided on create.
func (u *OpenAI5hWakePoolLeaseUpsertOne) UpdateLeaseExpiresAt() *OpenAI5hWakePoolLeaseUpsertOne {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.UpdateLeaseExpiresAt()
	})
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (u *OpenAI5hWakePoolLeaseUpsertOne) SetHeartbeatAt(v time.Time) *OpenAI5hWakePoolLeaseUpsertOne {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.SetHeartbeatAt(v)
	})
}

// UpdateHeartbeatAt sets the "heartbeat_at" field to the value that was provided on create.
func (u *OpenAI5hWakePoolLeaseUpsertOne) UpdateHeartbeatAt() *OpenAI5hWakePoolLeaseUpsertOne {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.UpdateHeartbeatAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAI5hWakePoolLeaseUpsertOne) SetUpdatedAt(v time.Time) *OpenAI5hWakePoolLeaseUpsertOne {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAI5hWakePoolLeaseUpsertOne) UpdateUpdatedAt() *OpenAI5hWakePoolLeaseUpsertOne {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *OpenAI5hWakePoolLeaseUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OpenAI5hWakePoolLeaseCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OpenAI5hWakePoolLeaseUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OpenAI5hWakePoolLeaseUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OpenAI5hWakePoolLeaseUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OpenAI5hWakePoolLeaseCreateBulk is the builder for creating many OpenAI5hWakePoolLease entities in bulk.
type OpenAI5hWakePoolLeaseCreateBulk struct {
	config
	err      error
	builders []*OpenAI5hWakePoolLeaseCreate
	conflict []sql.ConflictOption
}

// Save creates the OpenAI5hWakePoolLease entities in the database.
func (_c *OpenAI5hWakePoolLeaseCreateBulk) Save(ctx context.Context) ([]*OpenAI5hWakePoolLease, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OpenAI5hWakePoolLease, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OpenAI5hWakePoolLeaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OpenAI5hWakePoolLeaseCreateBulk) SaveX(ctx context.Context) []*OpenAI5hWakePoolLease {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OpenAI5hWakePoolLeaseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OpenAI5hWakePoolLeaseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OpenAI5hWakePoolLease.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OpenAI5hWakePoolLeaseUpsert) {
//			SetIdentityHash(v+v).
//		}).
//		Exec(ctx)
func (_c *OpenAI5hWakePoolLeaseCreateBulk) OnConflict(opts ...sql.ConflictOption) *OpenAI5hWakePoolLeaseUpsertBulk {
	_c.conflict = opts
	return &OpenAI5hWakePoolLeaseUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OpenAI5hWakePoolLease.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OpenAI5hWakePoolLeaseCreateBulk) OnConflictColumns(columns ...string) *OpenAI5hWakePoolLeaseUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OpenAI5hWakePoolLeaseUpsertBulk{
		create: _c,
	}
}

// OpenAI5hWakePoolLeaseUpsertBulk is the builder for "upsert"-ing
// a bulk of OpenAI5hWakePoolLease nodes.
type OpenAI5hWakePoolLeaseUpsertBulk struct {
	create *OpenAI5hWakePoolLeaseCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OpenAI5hWakePoolLease.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OpenAI5hWakePoolLeaseUpsertBulk) UpdateNewValues() *OpenAI5hWakePoolLeaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(openai5hwakepoollease.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OpenAI5hWakePoolLease.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OpenAI5hWakePoolLeaseUpsertBulk) Ignore() *OpenAI5hWakePoolLeaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OpenAI5hWakePoolLeaseUpsertBulk) DoNothing() *OpenAI5hWakePoolLeaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OpenAI5hWakePoolLeaseCreateBulk.OnConflict
// documentation for more info.
func (u *OpenAI5hWakePoolLeaseUpsertBulk) Update(set func(*OpenAI5hWakePoolLeaseUpsert)) *OpenAI5hWakePoolLeaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OpenAI5hWakePoolLeaseUpsert{UpdateSet: update})
	}))
	return u
}

// SetIdentityHash sets the "identity_hash" field.
func (u *OpenAI5hWakePoolLeaseUpsertBulk) SetIdentityHash(v string) *OpenAI5hWakePoolLeaseUpsertBulk {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.SetIdentityHash(v)
	})
}

// UpdateIdentityHash sets the "identity_hash" field to the value that was provided on create.
func (u *OpenAI5hWakePoolLeaseUpsertBulk) UpdateIdentityHash() *OpenAI5hWakePoolLeaseUpsertBulk {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.UpdateIdentityHash()
	})
}

// SetTaskID sets the "task_id" field.
func (u *OpenAI5hWakePoolLeaseUpsertBulk) SetTaskID(v int64) *OpenAI5hWakePoolLeaseUpsertBulk {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.SetTaskID(v)
	})
}

// AddTaskID adds v to the "task_id" field.
func (u *OpenAI5hWakePoolLeaseUpsertBulk) AddTaskID(v int64) *OpenAI5hWakePoolLeaseUpsertBulk {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.AddTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *OpenAI5hWakePoolLeaseUpsertBulk) UpdateTaskID() *OpenAI5hWakePoolLeaseUpsertBulk {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.UpdateTaskID()
	})
}

// SetItemID sets the "item_id" field.
func (u *OpenAI5hWakePoolLeaseUpsertBulk) SetItemID(v int64) *OpenAI5hWakePoolLeaseUpsertBulk {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.SetItemID(v)
	})
}

// AddItemID adds v to the "item_id" field.
func (u *OpenAI5hWakePoolLeaseUpsertBulk) AddItemID(v int64) *OpenAI5hWakePoolLeaseUpsertBulk {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.AddItemID(v)
	})
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *OpenAI5hWakePoolLeaseUpsertBulk) UpdateItemID() *OpenAI5hWakePoolLeaseUpsertBulk {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.UpdateItemID()
	})
}

// SetLeaseOwner sets the "lease_owner" field.
func (u *OpenAI5hWakePoolLeaseUpsertBulk) SetLeaseOwner(v string) *OpenAI5hWakePoolLeaseUpsertBulk {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.SetLeaseOwner(v)
	})
}

// UpdateLeaseOwner sets the "lease_owner" field to the value that was provided on create.
func (u *OpenAI5hWakePoolLeaseUpsertBulk) UpdateLeaseOwner() *OpenAI5hWakePoolLeaseUpsertBulk {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.UpdateLeaseOwner()
	})
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (u *OpenAI5hWakePoolLeaseUpsertBulk) SetLeaseExpiresAt(v time.Time) *OpenAI5hWakePoolLeaseUpsertBulk {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.SetLeaseExpiresAt(v)
	})
}

// UpdateLeaseExpiresAt sets the "lease_expires_at" field to the value that was provided on create.
func (u *OpenAI5hWakePoolLeaseUpsertBulk) UpdateLeaseExpiresAt() *OpenAI5hWakePoolLeaseUpsertBulk {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.UpdateLeaseExpiresAt()
	})
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (u *OpenAI5hWakePoolLeaseUpsertBulk) SetHeartbeatAt(v time.Time) *OpenAI5hWakePoolLeaseUpsertBulk {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.SetHeartbeatAt(v)
	})
}

// UpdateHeartbeatAt sets the "heartbeat_at" field to the value that was provided on create.
func (u *OpenAI5hWakePoolLeaseUpsertBulk) UpdateHeartbeatAt() *OpenAI5hWakePoolLeaseUpsertBulk {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.UpdateHeartbeatAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAI5hWakePoolLeaseUpsertBulk) SetUpdatedAt(v time.Time) *OpenAI5hWakePoolLeaseUpsertBulk {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAI5hWakePoolLeaseUpsertBulk) UpdateUpdatedAt() *OpenAI5hWakePoolLeaseUpsertBulk {
	return u.Update(func(s *OpenAI5hWakePoolLeaseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *OpenAI5hWakePoolLeaseUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OpenAI5hWakePoolLeaseCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OpenAI5hWakePoolLeaseCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OpenAI5hWakePoolLeaseUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
