// Code generated by ent, DO NOT EDIT.

package openai5hwaketask

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the openai5hwaketask type in the database.
	Label = "open_ai5h_wake_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldEligibleAccountCount holds the string denoting the eligible_account_count field in the database.
	FieldEligibleAccountCount = "eligible_account_count"
	// FieldActiveWindowCount holds the string denoting the active_window_count field in the database.
	FieldActiveWindowCount = "active_window_count"
	// FieldEstimatedRequestCount holds the string denoting the estimated_request_count field in the database.
	FieldEstimatedRequestCount = "estimated_request_count"
	// FieldTotalItems holds the string denoting the total_items field in the database.
	FieldTotalItems = "total_items"
	// FieldProcessedItems holds the string denoting the processed_items field in the database.
	FieldProcessedItems = "processed_items"
	// FieldWokenCount holds the string denoting the woken_count field in the database.
	FieldWokenCount = "woken_count"
	// FieldSkippedActiveCount holds the string denoting the skipped_active_count field in the database.
	FieldSkippedActiveCount = "skipped_active_count"
	// FieldFailedCount holds the string denoting the failed_count field in the database.
	FieldFailedCount = "failed_count"
	// FieldCancelledCount holds the string denoting the cancelled_count field in the database.
	FieldCancelledCount = "cancelled_count"
	// FieldRequestedByUserID holds the string denoting the requested_by_user_id field in the database.
	FieldRequestedByUserID = "requested_by_user_id"
	// FieldRequestedByEmail holds the string denoting the requested_by_email field in the database.
	FieldRequestedByEmail = "requested_by_email"
	// FieldLeaseOwner holds the string denoting the lease_owner field in the database.
	FieldLeaseOwner = "lease_owner"
	// FieldLeaseExpiresAt holds the string denoting the lease_expires_at field in the database.
	FieldLeaseExpiresAt = "lease_expires_at"
	// FieldHeartbeatAt holds the string denoting the heartbeat_at field in the database.
	FieldHeartbeatAt = "heartbeat_at"
	// FieldEarliestResetAt holds the string denoting the earliest_reset_at field in the database.
	FieldEarliestResetAt = "earliest_reset_at"
	// FieldLatestResetAt holds the string denoting the latest_reset_at field in the database.
	FieldLatestResetAt = "latest_reset_at"
	// FieldCancelRequestedAt holds the string denoting the cancel_requested_at field in the database.
	FieldCancelRequestedAt = "cancel_requested_at"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the openai5hwaketask in the database.
	Table = "openai_5h_wake_tasks"
)

// Columns holds all SQL columns for openai5hwaketask fields.
var Columns = []string{
	FieldID,
	FieldStatus,
	FieldEligibleAccountCount,
	FieldActiveWindowCount,
	FieldEstimatedRequestCount,
	FieldTotalItems,
	FieldProcessedItems,
	FieldWokenCount,
	FieldSkippedActiveCount,
	FieldFailedCount,
	FieldCancelledCount,
	FieldRequestedByUserID,
	FieldRequestedByEmail,
	FieldLeaseOwner,
	FieldLeaseExpiresAt,
	FieldHeartbeatAt,
	FieldEarliestResetAt,
	FieldLatestResetAt,
	FieldCancelRequestedAt,
	FieldStartedAt,
	FieldFinishedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultEligibleAccountCount holds the default value on creation for the "eligible_account_count" field.
	DefaultEligibleAccountCount int
	// DefaultActiveWindowCount holds the default value on creation for the "active_window_count" field.
	DefaultActiveWindowCount int
	// DefaultEstimatedRequestCount holds the default value on creation for the "estimated_request_count" field.
	DefaultEstimatedRequestCount int
	// DefaultTotalItems holds the default value on creation for the "total_items" field.
	DefaultTotalItems int
	// DefaultProcessedItems holds the default value on creation for the "processed_items" field.
	DefaultProcessedItems int
	// DefaultWokenCount holds the default value on creation for the "woken_count" field.
	DefaultWokenCount int
	// DefaultSkippedActiveCount holds the default value on creation for the "skipped_active_count" field.
	DefaultSkippedActiveCount int
	// DefaultFailedCount holds the default value on creation for the "failed_count" field.
	DefaultFailedCount int
	// DefaultCancelledCount holds the default value on creation for the "cancelled_count" field.
	DefaultCancelledCount int
	// RequestedByEmailValidator is a validator for the "requested_by_email" field. It is called by the builders before save.
	RequestedByEmailValidator func(string) error
	// LeaseOwnerValidator is a validator for the "lease_owner" field. It is called by the builders before save.
	LeaseOwnerValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the OpenAI5hWakeTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByEligibleAccountCount orders the results by the eligible_account_count field.
func ByEligibleAccountCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEligibleAccountCount, opts...).ToFunc()
}

// ByActiveWindowCount orders the results by the active_window_count field.
func ByActiveWindowCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActiveWindowCount, opts...).ToFunc()
}

// ByEstimatedRequestCount orders the results by the estimated_request_count field.
func ByEstimatedRequestCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstimatedRequestCount, opts...).ToFunc()
}

// ByTotalItems orders the results by the total_items field.
func ByTotalItems(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalItems, opts...).ToFunc()
}

// ByProcessedItems orders the results by the processed_items field.
func ByProcessedItems(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcessedItems, opts...).ToFunc()
}

// ByWokenCount orders the results by the woken_count field.
func ByWokenCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWokenCount, opts...).ToFunc()
}

// BySkippedActiveCount orders the results by the skipped_active_count field.
func BySkippedActiveCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkippedActiveCount, opts...).ToFunc()
}

// ByFailedCount orders the results by the failed_count field.
func ByFailedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailedCount, opts...).ToFunc()
}

// ByCancelledCount orders the results by the cancelled_count field.
func ByCancelledCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelledCount, opts...).ToFunc()
}

// ByRequestedByUserID orders the results by the requested_by_user_id field.
func ByRequestedByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedByUserID, opts...).ToFunc()
}

// ByRequestedByEmail orders the results by the requested_by_email field.
func ByRequestedByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedByEmail, opts...).ToFunc()
}

// ByLeaseOwner orders the results by the lease_owner field.
func ByLeaseOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeaseOwner, opts...).ToFunc()
}

// ByLeaseExpiresAt orders the results by the lease_expires_at field.
func ByLeaseExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeaseExpiresAt, opts...).ToFunc()
}

// ByHeartbeatAt orders the results by the heartbeat_at field.
func ByHeartbeatAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeartbeatAt, opts...).ToFunc()
}

// ByEarliestResetAt orders the results by the earliest_reset_at field.
func ByEarliestResetAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEarliestResetAt, opts...).ToFunc()
}

// ByLatestResetAt orders the results by the latest_reset_at field.
func ByLatestResetAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatestResetAt, opts...).ToFunc()
}

// ByCancelRequestedAt orders the results by the cancel_requested_at field.
func ByCancelRequestedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelRequestedAt, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
