// Code generated by ent, DO NOT EDIT.

package openai5hwaketask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLTE(FieldID, id))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldStatus, v))
}

// EligibleAccountCount applies equality check predicate on the "eligible_account_count" field. It's identical to EligibleAccountCountEQ.
func EligibleAccountCount(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldEligibleAccountCount, v))
}

// ActiveWindowCount applies equality check predicate on the "active_window_count" field. It's identical to ActiveWindowCountEQ.
func ActiveWindowCount(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldActiveWindowCount, v))
}

// EstimatedRequestCount applies equality check predicate on the "estimated_request_count" field. It's identical to EstimatedRequestCountEQ.
func EstimatedRequestCount(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldEstimatedRequestCount, v))
}

// TotalItems applies equality check predicate on the "total_items" field. It's identical to TotalItemsEQ.
func TotalItems(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldTotalItems, v))
}

// ProcessedItems applies equality check predicate on the "processed_items" field. It's identical to ProcessedItemsEQ.
func ProcessedItems(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldProcessedItems, v))
}

// WokenCount applies equality check predicate on the "woken_count" field. It's identical to WokenCountEQ.
func WokenCount(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldWokenCount, v))
}

// SkippedActiveCount applies equality check predicate on the "skipped_active_count" field. It's identical to SkippedActiveCountEQ.
func SkippedActiveCount(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldSkippedActiveCount, v))
}

// FailedCount applies equality check predicate on the "failed_count" field. It's identical to FailedCountEQ.
func FailedCount(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldFailedCount, v))
}

// CancelledCount applies equality check predicate on the "cancelled_count" field. It's identical to CancelledCountEQ.
func CancelledCount(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldCancelledCount, v))
}

// RequestedByUserID applies equality check predicate on the "requested_by_user_id" field. It's identical to RequestedByUserIDEQ.
func RequestedByUserID(v int64) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldRequestedByUserID, v))
}

// RequestedByEmail applies equality check predicate on the "requested_by_email" field. It's identical to RequestedByEmailEQ.
func RequestedByEmail(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldRequestedByEmail, v))
}

// LeaseOwner applies equality check predicate on the "lease_owner" field. It's identical to LeaseOwnerEQ.
func LeaseOwner(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldLeaseOwner, v))
}

// LeaseExpiresAt applies equality check predicate on the "lease_expires_at" field. It's identical to LeaseExpiresAtEQ.
func LeaseExpiresAt(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldLeaseExpiresAt, v))
}

// HeartbeatAt applies equality check predicate on the "heartbeat_at" field. It's identical to HeartbeatAtEQ.
func HeartbeatAt(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldHeartbeatAt, v))
}

// EarliestResetAt applies equality check predicate on the "earliest_reset_at" field. It's identical to EarliestResetAtEQ.
func EarliestResetAt(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldEarliestResetAt, v))
}

// LatestResetAt applies equality check predicate on the "latest_reset_at" field. It's identical to LatestResetAtEQ.
func LatestResetAt(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldLatestResetAt, v))
}

// CancelRequestedAt applies equality check predicate on the "cancel_requested_at" field. It's identical to CancelRequestedAtEQ.
func CancelRequestedAt(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldCancelRequestedAt, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldFinishedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldContainsFold(FieldStatus, v))
}

// EligibleAccountCountEQ applies the EQ predicate on the "eligible_account_count" field.
func EligibleAccountCountEQ(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldEligibleAccountCount, v))
}

// EligibleAccountCountNEQ applies the NEQ predicate on the "eligible_account_count" field.
func EligibleAccountCountNEQ(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNEQ(FieldEligibleAccountCount, v))
}

// EligibleAccountCountIn applies the In predicate on the "eligible_account_count" field.
func EligibleAccountCountIn(vs ...int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIn(FieldEligibleAccountCount, vs...))
}

// EligibleAccountCountNotIn applies the NotIn predicate on the "eligible_account_count" field.
func EligibleAccountCountNotIn(vs ...int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotIn(FieldEligibleAccountCount, vs...))
}

// EligibleAccountCountGT applies the GT predicate on the "eligible_account_count" field.
func EligibleAccountCountGT(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGT(FieldEligibleAccountCount, v))
}

// EligibleAccountCountGTE applies the GTE predicate on the "eligible_account_count" field.
func EligibleAccountCountGTE(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGTE(FieldEligibleAccountCount, v))
}

// EligibleAccountCountLT applies the LT predicate on the "eligible_account_count" field.
func EligibleAccountCountLT(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLT(FieldEligibleAccountCount, v))
}

// EligibleAccountCountLTE applies the LTE predicate on the "eligible_account_count" field.
func EligibleAccountCountLTE(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLTE(FieldEligibleAccountCount, v))
}

// ActiveWindowCountEQ applies the EQ predicate on the "active_window_count" field.
func ActiveWindowCountEQ(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldActiveWindowCount, v))
}

// ActiveWindowCountNEQ applies the NEQ predicate on the "active_window_count" field.
func ActiveWindowCountNEQ(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNEQ(FieldActiveWindowCount, v))
}

// ActiveWindowCountIn applies the In predicate on the "active_window_count" field.
func ActiveWindowCountIn(vs ...int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIn(FieldActiveWindowCount, vs...))
}

// ActiveWindowCountNotIn applies the NotIn predicate on the "active_window_count" field.
func ActiveWindowCountNotIn(vs ...int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotIn(FieldActiveWindowCount, vs...))
}

// ActiveWindowCountGT applies the GT predicate on the "active_window_count" field.
func ActiveWindowCountGT(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGT(FieldActiveWindowCount, v))
}

// ActiveWindowCountGTE applies the GTE predicate on the "active_window_count" field.
func ActiveWindowCountGTE(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGTE(FieldActiveWindowCount, v))
}

// ActiveWindowCountLT applies the LT predicate on the "active_window_count" field.
func ActiveWindowCountLT(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLT(FieldActiveWindowCount, v))
}

// ActiveWindowCountLTE applies the LTE predicate on the "active_window_count" field.
func ActiveWindowCountLTE(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLTE(FieldActiveWindowCount, v))
}

// EstimatedRequestCountEQ applies the EQ predicate on the "estimated_request_count" field.
func EstimatedRequestCountEQ(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldEstimatedRequestCount, v))
}

// EstimatedRequestCountNEQ applies the NEQ predicate on the "estimated_request_count" field.
func EstimatedRequestCountNEQ(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNEQ(FieldEstimatedRequestCount, v))
}

// EstimatedRequestCountIn applies the In predicate on the "estimated_request_count" field.
func EstimatedRequestCountIn(vs ...int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIn(FieldEstimatedRequestCount, vs...))
}

// EstimatedRequestCountNotIn applies the NotIn predicate on the "estimated_request_count" field.
func EstimatedRequestCountNotIn(vs ...int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotIn(FieldEstimatedRequestCount, vs...))
}

// EstimatedRequestCountGT applies the GT predicate on the "estimated_request_count" field.
func EstimatedRequestCountGT(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGT(FieldEstimatedRequestCount, v))
}

// EstimatedRequestCountGTE applies the GTE predicate on the "estimated_request_count" field.
func EstimatedRequestCountGTE(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGTE(FieldEstimatedRequestCount, v))
}

// EstimatedRequestCountLT applies the LT predicate on the "estimated_request_count" field.
func EstimatedRequestCountLT(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLT(FieldEstimatedRequestCount, v))
}

// EstimatedRequestCountLTE applies the LTE predicate on the "estimated_request_count" field.
func EstimatedRequestCountLTE(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLTE(FieldEstimatedRequestCount, v))
}

// TotalItemsEQ applies the EQ predicate on the "total_items" field.
func TotalItemsEQ(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldTotalItems, v))
}

// TotalItemsNEQ applies the NEQ predicate on the "total_items" field.
func TotalItemsNEQ(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNEQ(FieldTotalItems, v))
}

// TotalItemsIn applies the In predicate on the "total_items" field.
func TotalItemsIn(vs ...int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIn(FieldTotalItems, vs...))
}

// TotalItemsNotIn applies the NotIn predicate on the "total_items" field.
func TotalItemsNotIn(vs ...int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotIn(FieldTotalItems, vs...))
}

// TotalItemsGT applies the GT predicate on the "total_items" field.
func TotalItemsGT(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGT(FieldTotalItems, v))
}

// TotalItemsGTE applies the GTE predicate on the "total_items" field.
func TotalItemsGTE(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGTE(FieldTotalItems, v))
}

// TotalItemsLT applies the LT predicate on the "total_items" field.
func TotalItemsLT(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLT(FieldTotalItems, v))
}

// TotalItemsLTE applies the LTE predicate on the "total_items" field.
func TotalItemsLTE(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLTE(FieldTotalItems, v))
}

// ProcessedItemsEQ applies the EQ predicate on the "processed_items" field.
func ProcessedItemsEQ(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldProcessedItems, v))
}

// ProcessedItemsNEQ applies the NEQ predicate on the "processed_items" field.
func ProcessedItemsNEQ(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNEQ(FieldProcessedItems, v))
}

// ProcessedItemsIn applies the In predicate on the "processed_items" field.
func ProcessedItemsIn(vs ...int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIn(FieldProcessedItems, vs...))
}

// ProcessedItemsNotIn applies the NotIn predicate on the "processed_items" field.
func ProcessedItemsNotIn(vs ...int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotIn(FieldProcessedItems, vs...))
}

// ProcessedItemsGT applies the GT predicate on the "processed_items" field.
func ProcessedItemsGT(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGT(FieldProcessedItems, v))
}

// ProcessedItemsGTE applies the GTE predicate on the "processed_items" field.
func ProcessedItemsGTE(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGTE(FieldProcessedItems, v))
}

// ProcessedItemsLT applies the LT predicate on the "processed_items" field.
func ProcessedItemsLT(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLT(FieldProcessedItems, v))
}

// ProcessedItemsLTE applies the LTE predicate on the "processed_items" field.
func ProcessedItemsLTE(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLTE(FieldProcessedItems, v))
}

// WokenCountEQ applies the EQ predicate on the "woken_count" field.
func WokenCountEQ(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldWokenCount, v))
}

// WokenCountNEQ applies the NEQ predicate on the "woken_count" field.
func WokenCountNEQ(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNEQ(FieldWokenCount, v))
}

// WokenCountIn applies the In predicate on the "woken_count" field.
func WokenCountIn(vs ...int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIn(FieldWokenCount, vs...))
}

// WokenCountNotIn applies the NotIn predicate on the "woken_count" field.
func WokenCountNotIn(vs ...int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotIn(FieldWokenCount, vs...))
}

// WokenCountGT applies the GT predicate on the "woken_count" field.
func WokenCountGT(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGT(FieldWokenCount, v))
}

// WokenCountGTE applies the GTE predicate on the "woken_count" field.
func WokenCountGTE(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGTE(FieldWokenCount, v))
}

// WokenCountLT applies the LT predicate on the "woken_count" field.
func WokenCountLT(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLT(FieldWokenCount, v))
}

// WokenCountLTE applies the LTE predicate on the "woken_count" field.
func WokenCountLTE(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLTE(FieldWokenCount, v))
}

// SkippedActiveCountEQ applies the EQ predicate on the "skipped_active_count" field.
func SkippedActiveCountEQ(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldSkippedActiveCount, v))
}

// SkippedActiveCountNEQ applies the NEQ predicate on the "skipped_active_count" field.
func SkippedActiveCountNEQ(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNEQ(FieldSkippedActiveCount, v))
}

// SkippedActiveCountIn applies the In predicate on the "skipped_active_count" field.
func SkippedActiveCountIn(vs ...int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIn(FieldSkippedActiveCount, vs...))
}

// SkippedActiveCountNotIn applies the NotIn predicate on the "skipped_active_count" field.
func SkippedActiveCountNotIn(vs ...int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotIn(FieldSkippedActiveCount, vs...))
}

// SkippedActiveCountGT applies the GT predicate on the "skipped_active_count" field.
func SkippedActiveCountGT(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGT(FieldSkippedActiveCount, v))
}

// SkippedActiveCountGTE applies the GTE predicate on the "skipped_active_count" field.
func SkippedActiveCountGTE(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGTE(FieldSkippedActiveCount, v))
}

// SkippedActiveCountLT applies the LT predicate on the "skipped_active_count" field.
func SkippedActiveCountLT(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLT(FieldSkippedActiveCount, v))
}

// SkippedActiveCountLTE applies the LTE predicate on the "skipped_active_count" field.
func SkippedActiveCountLTE(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLTE(FieldSkippedActiveCount, v))
}

// FailedCountEQ applies the EQ predicate on the "failed_count" field.
func FailedCountEQ(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldFailedCount, v))
}

// FailedCountNEQ applies the NEQ predicate on the "failed_count" field.
func FailedCountNEQ(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNEQ(FieldFailedCount, v))
}

// FailedCountIn applies the In predicate on the "failed_count" field.
func FailedCountIn(vs ...int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIn(FieldFailedCount, vs...))
}

// FailedCountNotIn applies the NotIn predicate on the "failed_count" field.
func FailedCountNotIn(vs ...int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotIn(FieldFailedCount, vs...))
}

// FailedCountGT applies the GT predicate on the "failed_count" field.
func FailedCountGT(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGT(FieldFailedCount, v))
}

// FailedCountGTE applies the GTE predicate on the "failed_count" field.
func FailedCountGTE(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGTE(FieldFailedCount, v))
}

// FailedCountLT applies the LT predicate on the "failed_count" field.
func FailedCountLT(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLT(FieldFailedCount, v))
}

// FailedCountLTE applies the LTE predicate on the "failed_count" field.
func FailedCountLTE(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLTE(FieldFailedCount, v))
}

// CancelledCountEQ applies the EQ predicate on the "cancelled_count" field.
func CancelledCountEQ(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldCancelledCount, v))
}

// CancelledCountNEQ applies the NEQ predicate on the "cancelled_count" field.
func CancelledCountNEQ(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNEQ(FieldCancelledCount, v))
}

// CancelledCountIn applies the In predicate on the "cancelled_count" field.
func CancelledCountIn(vs ...int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIn(FieldCancelledCount, vs...))
}

// CancelledCountNotIn applies the NotIn predicate on the "cancelled_count" field.
func CancelledCountNotIn(vs ...int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotIn(FieldCancelledCount, vs...))
}

// CancelledCountGT applies the GT predicate on the "cancelled_count" field.
func CancelledCountGT(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGT(FieldCancelledCount, v))
}

// CancelledCountGTE applies the GTE predicate on the "cancelled_count" field.
func CancelledCountGTE(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGTE(FieldCancelledCount, v))
}

// CancelledCountLT applies the LT predicate on the "cancelled_count" field.
func CancelledCountLT(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLT(FieldCancelledCount, v))
}

// CancelledCountLTE applies the LTE predicate on the "cancelled_count" field.
func CancelledCountLTE(v int) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLTE(FieldCancelledCount, v))
}

// RequestedByUserIDEQ applies the EQ predicate on the "requested_by_user_id" field.
func RequestedByUserIDEQ(v int64) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldRequestedByUserID, v))
}

// RequestedByUserIDNEQ applies the NEQ predicate on the "requested_by_user_id" field.
func RequestedByUserIDNEQ(v int64) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNEQ(FieldRequestedByUserID, v))
}

// RequestedByUserIDIn applies the In predicate on the "requested_by_user_id" field.
func RequestedByUserIDIn(vs ...int64) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIn(FieldRequestedByUserID, vs...))
}

// RequestedByUserIDNotIn applies the NotIn predicate on the "requested_by_user_id" field.
func RequestedByUserIDNotIn(vs ...int64) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotIn(FieldRequestedByUserID, vs...))
}

// RequestedByUserIDGT applies the GT predicate on the "requested_by_user_id" field.
func RequestedByUserIDGT(v int64) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGT(FieldRequestedByUserID, v))
}

// RequestedByUserIDGTE applies the GTE predicate on the "requested_by_user_id" field.
func RequestedByUserIDGTE(v int64) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGTE(FieldRequestedByUserID, v))
}

// RequestedByUserIDLT applies the LT predicate on the "requested_by_user_id" field.
func RequestedByUserIDLT(v int64) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLT(FieldRequestedByUserID, v))
}

// RequestedByUserIDLTE applies the LTE predicate on the "requested_by_user_id" field.
func RequestedByUserIDLTE(v int64) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLTE(FieldRequestedByUserID, v))
}

// RequestedByUserIDIsNil applies the IsNil predicate on the "requested_by_user_id" field.
func RequestedByUserIDIsNil() predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIsNull(FieldRequestedByUserID))
}

// RequestedByUserIDNotNil applies the NotNil predicate on the "requested_by_user_id" field.
func RequestedByUserIDNotNil() predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotNull(FieldRequestedByUserID))
}

// RequestedByEmailEQ applies the EQ predicate on the "requested_by_email" field.
func RequestedByEmailEQ(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldRequestedByEmail, v))
}

// RequestedByEmailNEQ applies the NEQ predicate on the "requested_by_email" field.
func RequestedByEmailNEQ(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNEQ(FieldRequestedByEmail, v))
}

// RequestedByEmailIn applies the In predicate on the "requested_by_email" field.
func RequestedByEmailIn(vs ...string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIn(FieldRequestedByEmail, vs...))
}

// RequestedByEmailNotIn applies the NotIn predicate on the "requested_by_email" field.
func RequestedByEmailNotIn(vs ...string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotIn(FieldRequestedByEmail, vs...))
}

// RequestedByEmailGT applies the GT predicate on the "requested_by_email" field.
func RequestedByEmailGT(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGT(FieldRequestedByEmail, v))
}

// RequestedByEmailGTE applies the GTE predicate on the "requested_by_email" field.
func RequestedByEmailGTE(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGTE(FieldRequestedByEmail, v))
}

// RequestedByEmailLT applies the LT predicate on the "requested_by_email" field.
func RequestedByEmailLT(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLT(FieldRequestedByEmail, v))
}

// RequestedByEmailLTE applies the LTE predicate on the "requested_by_email" field.
func RequestedByEmailLTE(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLTE(FieldRequestedByEmail, v))
}

// RequestedByEmailContains applies the Contains predicate on the "requested_by_email" field.
func RequestedByEmailContains(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldContains(FieldRequestedByEmail, v))
}

// RequestedByEmailHasPrefix applies the HasPrefix predicate on the "requested_by_email" field.
func RequestedByEmailHasPrefix(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldHasPrefix(FieldRequestedByEmail, v))
}

// RequestedByEmailHasSuffix applies the HasSuffix predicate on the "requested_by_email" field.
func RequestedByEmailHasSuffix(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldHasSuffix(FieldRequestedByEmail, v))
}

// RequestedByEmailIsNil applies the IsNil predicate on the "requested_by_email" field.
func RequestedByEmailIsNil() predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIsNull(FieldRequestedByEmail))
}

// RequestedByEmailNotNil applies the NotNil predicate on the "requested_by_email" field.
func RequestedByEmailNotNil() predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotNull(FieldRequestedByEmail))
}

// RequestedByEmailEqualFold applies the EqualFold predicate on the "requested_by_email" field.
func RequestedByEmailEqualFold(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEqualFold(FieldRequestedByEmail, v))
}

// RequestedByEmailContainsFold applies the ContainsFold predicate on the "requested_by_email" field.
func RequestedByEmailContainsFold(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldContainsFold(FieldRequestedByEmail, v))
}

// LeaseOwnerEQ applies the EQ predicate on the "lease_owner" field.
func LeaseOwnerEQ(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldLeaseOwner, v))
}

// LeaseOwnerNEQ applies the NEQ predicate on the "lease_owner" field.
func LeaseOwnerNEQ(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNEQ(FieldLeaseOwner, v))
}

// LeaseOwnerIn applies the In predicate on the "lease_owner" field.
func LeaseOwnerIn(vs ...string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIn(FieldLeaseOwner, vs...))
}

// LeaseOwnerNotIn applies the NotIn predicate on the "lease_owner" field.
func LeaseOwnerNotIn(vs ...string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotIn(FieldLeaseOwner, vs...))
}

// LeaseOwnerGT applies the GT predicate on the "lease_owner" field.
func LeaseOwnerGT(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGT(FieldLeaseOwner, v))
}

// LeaseOwnerGTE applies the GTE predicate on the "lease_owner" field.
func LeaseOwnerGTE(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGTE(FieldLeaseOwner, v))
}

// LeaseOwnerLT applies the LT predicate on the "lease_owner" field.
func LeaseOwnerLT(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLT(FieldLeaseOwner, v))
}

// LeaseOwnerLTE applies the LTE predicate on the "lease_owner" field.
func LeaseOwnerLTE(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLTE(FieldLeaseOwner, v))
}

// LeaseOwnerContains applies the Contains predicate on the "lease_owner" field.
func LeaseOwnerContains(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldContains(FieldLeaseOwner, v))
}

// LeaseOwnerHasPrefix applies the HasPrefix predicate on the "lease_owner" field.
func LeaseOwnerHasPrefix(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldHasPrefix(FieldLeaseOwner, v))
}

// LeaseOwnerHasSuffix applies the HasSuffix predicate on the "lease_owner" field.
func LeaseOwnerHasSuffix(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldHasSuffix(FieldLeaseOwner, v))
}

// LeaseOwnerIsNil applies the IsNil predicate on the "lease_owner" field.
func LeaseOwnerIsNil() predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIsNull(FieldLeaseOwner))
}

// LeaseOwnerNotNil applies the NotNil predicate on the "lease_owner" field.
func LeaseOwnerNotNil() predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotNull(FieldLeaseOwner))
}

// LeaseOwnerEqualFold applies the EqualFold predicate on the "lease_owner" field.
func LeaseOwnerEqualFold(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEqualFold(FieldLeaseOwner, v))
}

// LeaseOwnerContainsFold applies the ContainsFold predicate on the "lease_owner" field.
func LeaseOwnerContainsFold(v string) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldContainsFold(FieldLeaseOwner, v))
}

// LeaseExpiresAtEQ applies the EQ predicate on the "lease_expires_at" field.
func LeaseExpiresAtEQ(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtNEQ applies the NEQ predicate on the "lease_expires_at" field.
func LeaseExpiresAtNEQ(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNEQ(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtIn applies the In predicate on the "lease_expires_at" field.
func LeaseExpiresAtIn(vs ...time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIn(FieldLeaseExpiresAt, vs...))
}

// LeaseExpiresAtNotIn applies the NotIn predicate on the "lease_expires_at" field.
func LeaseExpiresAtNotIn(vs ...time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotIn(FieldLeaseExpiresAt, vs...))
}

// LeaseExpiresAtGT applies the GT predicate on the "lease_expires_at" field.
func LeaseExpiresAtGT(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGT(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtGTE applies the GTE predicate on the "lease_expires_at" field.
func LeaseExpiresAtGTE(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGTE(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtLT applies the LT predicate on the "lease_expires_at" field.
func LeaseExpiresAtLT(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLT(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtLTE applies the LTE predicate on the "lease_expires_at" field.
func LeaseExpiresAtLTE(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLTE(FieldLeaseExpiresAt, v))
}

// LeaseExpiresAtIsNil applies the IsNil predicate on the "lease_expires_at" field.
func LeaseExpiresAtIsNil() predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIsNull(FieldLeaseExpiresAt))
}

// LeaseExpiresAtNotNil applies the NotNil predicate on the "lease_expires_at" field.
func LeaseExpiresAtNotNil() predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotNull(FieldLeaseExpiresAt))
}

// HeartbeatAtEQ applies the EQ predicate on the "heartbeat_at" field.
func HeartbeatAtEQ(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldHeartbeatAt, v))
}

// HeartbeatAtNEQ applies the NEQ predicate on the "heartbeat_at" field.
func HeartbeatAtNEQ(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNEQ(FieldHeartbeatAt, v))
}

// HeartbeatAtIn applies the In predicate on the "heartbeat_at" field.
func HeartbeatAtIn(vs ...time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIn(FieldHeartbeatAt, vs...))
}

// HeartbeatAtNotIn applies the NotIn predicate on the "heartbeat_at" field.
func HeartbeatAtNotIn(vs ...time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotIn(FieldHeartbeatAt, vs...))
}

// HeartbeatAtGT applies the GT predicate on the "heartbeat_at" field.
func HeartbeatAtGT(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGT(FieldHeartbeatAt, v))
}

// HeartbeatAtGTE applies the GTE predicate on the "heartbeat_at" field.
func HeartbeatAtGTE(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGTE(FieldHeartbeatAt, v))
}

// HeartbeatAtLT applies the LT predicate on the "heartbeat_at" field.
func HeartbeatAtLT(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLT(FieldHeartbeatAt, v))
}

// HeartbeatAtLTE applies the LTE predicate on the "heartbeat_at" field.
func HeartbeatAtLTE(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLTE(FieldHeartbeatAt, v))
}

// HeartbeatAtIsNil applies the IsNil predicate on the "heartbeat_at" field.
func HeartbeatAtIsNil() predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIsNull(FieldHeartbeatAt))
}

// HeartbeatAtNotNil applies the NotNil predicate on the "heartbeat_at" field.
func HeartbeatAtNotNil() predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotNull(FieldHeartbeatAt))
}

// EarliestResetAtEQ applies the EQ predicate on the "earliest_reset_at" field.
func EarliestResetAtEQ(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldEarliestResetAt, v))
}

// EarliestResetAtNEQ applies the NEQ predicate on the "earliest_reset_at" field.
func EarliestResetAtNEQ(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNEQ(FieldEarliestResetAt, v))
}

// EarliestResetAtIn applies the In predicate on the "earliest_reset_at" field.
func EarliestResetAtIn(vs ...time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIn(FieldEarliestResetAt, vs...))
}

// EarliestResetAtNotIn applies the NotIn predicate on the "earliest_reset_at" field.
func EarliestResetAtNotIn(vs ...time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotIn(FieldEarliestResetAt, vs...))
}

// EarliestResetAtGT applies the GT predicate on the "earliest_reset_at" field.
func EarliestResetAtGT(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGT(FieldEarliestResetAt, v))
}

// EarliestResetAtGTE applies the GTE predicate on the "earliest_reset_at" field.
func EarliestResetAtGTE(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGTE(FieldEarliestResetAt, v))
}

// EarliestResetAtLT applies the LT predicate on the "earliest_reset_at" field.
func EarliestResetAtLT(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLT(FieldEarliestResetAt, v))
}

// EarliestResetAtLTE applies the LTE predicate on the "earliest_reset_at" field.
func EarliestResetAtLTE(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLTE(FieldEarliestResetAt, v))
}

// EarliestResetAtIsNil applies the IsNil predicate on the "earliest_reset_at" field.
func EarliestResetAtIsNil() predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIsNull(FieldEarliestResetAt))
}

// EarliestResetAtNotNil applies the NotNil predicate on the "earliest_reset_at" field.
func EarliestResetAtNotNil() predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotNull(FieldEarliestResetAt))
}

// LatestResetAtEQ applies the EQ predicate on the "latest_reset_at" field.
func LatestResetAtEQ(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldLatestResetAt, v))
}

// LatestResetAtNEQ applies the NEQ predicate on the "latest_reset_at" field.
func LatestResetAtNEQ(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNEQ(FieldLatestResetAt, v))
}

// LatestResetAtIn applies the In predicate on the "latest_reset_at" field.
func LatestResetAtIn(vs ...time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIn(FieldLatestResetAt, vs...))
}

// LatestResetAtNotIn applies the NotIn predicate on the "latest_reset_at" field.
func LatestResetAtNotIn(vs ...time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotIn(FieldLatestResetAt, vs...))
}

// LatestResetAtGT applies the GT predicate on the "latest_reset_at" field.
func LatestResetAtGT(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGT(FieldLatestResetAt, v))
}

// LatestResetAtGTE applies the GTE predicate on the "latest_reset_at" field.
func LatestResetAtGTE(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGTE(FieldLatestResetAt, v))
}

// LatestResetAtLT applies the LT predicate on the "latest_reset_at" field.
func LatestResetAtLT(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLT(FieldLatestResetAt, v))
}

// LatestResetAtLTE applies the LTE predicate on the "latest_reset_at" field.
func LatestResetAtLTE(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLTE(FieldLatestResetAt, v))
}

// LatestResetAtIsNil applies the IsNil predicate on the "latest_reset_at" field.
func LatestResetAtIsNil() predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIsNull(FieldLatestResetAt))
}

// LatestResetAtNotNil applies the NotNil predicate on the "latest_reset_at" field.
func LatestResetAtNotNil() predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotNull(FieldLatestResetAt))
}

// CancelRequestedAtEQ applies the EQ predicate on the "cancel_requested_at" field.
func CancelRequestedAtEQ(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldCancelRequestedAt, v))
}

// CancelRequestedAtNEQ applies the NEQ predicate on the "cancel_requested_at" field.
func CancelRequestedAtNEQ(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNEQ(FieldCancelRequestedAt, v))
}

// CancelRequestedAtIn applies the In predicate on the "cancel_requested_at" field.
func CancelRequestedAtIn(vs ...time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIn(FieldCancelRequestedAt, vs...))
}

// CancelRequestedAtNotIn applies the NotIn predicate on the "cancel_requested_at" field.
func CancelRequestedAtNotIn(vs ...time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotIn(FieldCancelRequestedAt, vs...))
}

// CancelRequestedAtGT applies the GT predicate on the "cancel_requested_at" field.
func CancelRequestedAtGT(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGT(FieldCancelRequestedAt, v))
}

// CancelRequestedAtGTE applies the GTE predicate on the "cancel_requested_at" field.
func CancelRequestedAtGTE(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGTE(FieldCancelRequestedAt, v))
}

// CancelRequestedAtLT applies the LT predicate on the "cancel_requested_at" field.
func CancelRequestedAtLT(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLT(FieldCancelRequestedAt, v))
}

// CancelRequestedAtLTE applies the LTE predicate on the "cancel_requested_at" field.
func CancelRequestedAtLTE(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLTE(FieldCancelRequestedAt, v))
}

// CancelRequestedAtIsNil applies the IsNil predicate on the "cancel_requested_at" field.
func CancelRequestedAtIsNil() predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIsNull(FieldCancelRequestedAt))
}

// CancelRequestedAtNotNil applies the NotNil predicate on the "cancel_requested_at" field.
func CancelRequestedAtNotNil() predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotNull(FieldCancelRequestedAt))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotNull(FieldStartedAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotNull(FieldFinishedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OpenAI5hWakeTask) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OpenAI5hWakeTask) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OpenAI5hWakeTask) predicate.OpenAI5hWakeTask {
	return predicate.OpenAI5hWakeTask(sql.NotPredicates(p))
}
